In [616]:
import pandas as pd
import numpy as np
from os import listdir
import math
import matplotlib.pyplot as plt
files = [f for f in listdir('/home/ictd/nishant/research/Project/Data/original/Wholesale/WB/')]
files.sort()
#files=files[-18:]
#print(files)
#newfile = open('/home/ictd/Downloads/Minor Project-potato/Minor Project/time_series_analysis/crawler/data/wholesaleData/wholesalepotatodatalucknow2019.csv','w')
lines = []
for j in range(0,len(files)):
    file = files[j]
    filename='/home/ictd/nishant/research/Project/Data/original/Wholesale/WB/'+file
    #print(filename)
    df=pd.read_csv(filename,header=None, error_bad_lines=False)
    df=df[1:]
    df[[0]]=df[[0]].fillna(method='ffill')
    df[[1]]=df[[1]].fillna(method='ffill')
    df=df[df[0]=='Kalyani']
    lines.append(df)
    print(df)
    #print(lines[j])
#print(lines[17])
dk=pd.concat(lines)

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3    4    5    6   7
316  Kalyani  08/04/2008   30  Chandermukhi  580  600  580 NaN
317  Kalyani  08/04/2008  NaN         Jyoti  400  420  400 NaN
318  Kalyani  09/04/2008   30  Chandermukhi  580  600  580 NaN
319  Kalyani  09/04/2008  NaN         Jyoti  380  400  380 NaN
320  Kalyani  10/04/2008   30  Chandermukhi  580  600  580 NaN
321  Kalyani  10/04/2008  NaN         Jyoti  380  400  380 NaN
322  Kalyani  11/04/2008   30  Chandermukhi  580  600  580 NaN
323  Kalyani  11/04/2008  NaN         Jyoti  400  420  400 NaN
324  Kalyani  12/04/2008   30  Chandermukhi  580  600  580 NaN
325  Kalyani  12/04/2008  NaN         Jyoti  400  420  400 NaN
326  Kalyani  13/04/2008   30  Chandermukhi  550  600  580 NaN
327  Kalyani  13/04/2008  NaN         Jyoti  400  420  400 NaN
328  Kalyani  14/04/2008   30  Chandermukhi  580  600  580 NaN
329  Kalyani  14/04/2008  NaN         Jyoti  400  420  400 NaN
330  Kalyani  15/04/2008   35  Chandermukhi  550  600  580 NaN
331  Kalyani  15/04/2008  NaN         Jyoti  400  420  410 NaN
332  Kalyani  16/04/2008   30  Chandermukhi  560  600  580 NaN
333  Kalyani  16/04/2008  NaN         Jyoti  400  420  410 NaN
334  Kalyani  17/04/2008   30  Chandermukhi  570  600  580 NaN
335  Kalyani  17/04/2008  NaN         Jyoti  400  420  410 NaN
336  Kalyani  18/04/2008   30  Chandermukhi  570  600  580 NaN
337  Kalyani  18/04/2008  NaN         Jyoti  400  420  410 NaN
338  Kalyani  19/04/2008   30  Chandermukhi  570  600  580 NaN
339  Kalyani  19/04/2008  NaN         Jyoti  400  420  410 NaN
340  Kalyani  20/04/2008   30  Chandermukhi  570  600  580 NaN
341  Kalyani  20/04/2008  NaN         Jyoti  400  420  410 NaN
342  Kalyani  21/04/2008   30  Chandermukhi  570  600  580 NaN
343  Kalyani  21/04/2008  NaN         Jyoti  400  420  410 NaN
344  Kalyani  22/04/2008   30  Chandermukhi  570  600  580 NaN
345  Kalyani  22/04/2008  NaN         Jyoti  400  420  410 NaN
346  Kalyani  23/04/2008   30  Chandermukhi  570  600  580 NaN
347  Kalyani  23/04/2008  NaN         Jyoti  400  420  410 NaN
348  Kalyani  24/04/2008   30  Chandermukhi  570  600  580 NaN
349  Kalyani  24/04/2008  NaN         Jyoti  400  420  410 NaN
350  Kalyani  25/04/2008   30  Chandermukhi  560  600  580 NaN
351  Kalyani  25/04/2008  NaN         Jyoti  400  420  410 NaN
352  Kalyani  26/04/2008   30  Chandermukhi  560  600  580 NaN
353  Kalyani  26/04/2008  NaN         Jyoti  400  420  410 NaN
354  Kalyani  27/04/2008   30  Chandermukhi  550  580  570 NaN
355  Kalyani  27/04/2008  NaN         Jyoti  400  420  410 NaN
356  Kalyani  28/04/2008   30  Chandermukhi  550  580  570 NaN
357  Kalyani  28/04/2008  NaN         Jyoti  400  420  410 NaN
358  Kalyani  29/04/2008   30  Chandermukhi  550  580  570 NaN
359  Kalyani  29/04/2008  NaN         Jyoti  400  410  400 NaN
360  Kalyani  30/04/2008   30  Chandermukhi  550  580  570 NaN
361  Kalyani  30/04/2008  NaN         Jyoti  400  410  400 NaN
           0           1    2             3    4    5    6   7
438  Kalyani  01/08/2008   25  Chandermukhi  550  560  550 NaN
439  Kalyani  01/08/2008  NaN         Jyoti  350  360  350 NaN
440  Kalyani  02/08/2008   25                 NR   NR   NR NaN
441  Kalyani  03/08/2008   25                 NR   NR   NR NaN
442  Kalyani  04/08/2008   25                 NR   NR   NR NaN
443  Kalyani  05/08/2008   25                 NR   NR   NR NaN
444  Kalyani  06/08/2008   25                 NR   NR   NR NaN
445  Kalyani  07/08/2008   25                 NR   NR   NR NaN
446  Kalyani  08/08/2008   25                 NR   NR   NR NaN
447  Kalyani  09/08/2008   25  Chandermukhi  530  540  530 NaN
448  Kalyani  09/08/2008  NaN         Jyoti  330  340  330 NaN
449  Kalyani  10/08/2008   25  Chandermukhi  530  540  530 NaN
450  Kalyani  10/08/2008  NaN         Jyoti  330  340  330 NaN
451  Kalyani  11/08/2008   25  Chandermukhi  530  540  530 NaN
452  Kalyani  11/08/2008  NaN         Jyoti  320  330  320 NaN
453  Kalyani  12/08/2008   25  Chandermukhi  530  540  530 NaN
454  Kalyani  12/08/2008  NaN         Jyoti  320  330  320 NaN
455  Kalyani  13/08/2008   25  Chandermukhi  530  540  530 NaN
456  Kalyani  13/08/2008  NaN         Jyoti  320  330  320 NaN
457  Kalyani  14/08/2008   25  Chandermukhi  520  540  530 NaN
458  Kalyani  14/08/2008  NaN         Jyoti  320  330  320 NaN
459  Kalyani  15/08/2008   25  Chandermukhi  500  520  500 NaN
460  Kalyani  15/08/2008  NaN         Jyoti  300  320  300 NaN
461  Kalyani  16/08/2008   25  Chandermukhi  500  520  500 NaN
462  Kalyani  16/08/2008  NaN         Jyoti  300  310  300 NaN
463  Kalyani  17/08/2008   25  Chandermukhi  530  540  530 NaN
464  Kalyani  17/08/2008  NaN         Jyoti  330  340  330 NaN
465  Kalyani  18/08/2008   25  Chandermukhi  530  540  530 NaN
466  Kalyani  18/08/2008  NaN         Jyoti  330  340  330 NaN
467  Kalyani  19/08/2008   25  Chandermukhi  530  540  530 NaN
468  Kalyani  19/08/2008  NaN         Jyoti  330  340  330 NaN
469  Kalyani  21/08/2008   25  Chandermukhi  530  540  540 NaN
470  Kalyani  21/08/2008  NaN         Jyoti  330  340  330 NaN
471  Kalyani  22/08/2008   25  Chandermukhi  530  540  540 NaN
472  Kalyani  22/08/2008  NaN         Jyoti  330  340  330 NaN
473  Kalyani  23/08/2008   25  Chandermukhi  510  520  520 NaN
474  Kalyani  23/08/2008  NaN         Jyoti  320  340  330 NaN
475  Kalyani  24/08/2008   25  Chandermukhi  510  520  520 NaN
476  Kalyani  24/08/2008  NaN         Jyoti  320  340  330 NaN
477  Kalyani  25/08/2008   25  Chandermukhi  510  520  520 NaN
478  Kalyani  25/08/2008  NaN         Jyoti  320  330  330 NaN
479  Kalyani  26/08/2008   25  Chandermukhi  510  520  520 NaN
480  Kalyani  26/08/2008  NaN         Jyoti  320  330  330 NaN
481  Kalyani  27/08/2008   25  Chandermukhi  510  520  520 NaN
482  Kalyani  27/08/2008  NaN         Jyoti  320  330  330 NaN
483  Kalyani  28/08/2008   25  Chandermukhi  500  520  520 NaN
484  Kalyani  28/08/2008  NaN         Jyoti  310  320  320 NaN
485  Kalyani  29/08/2008   25  Chandermukhi  500  520  520 NaN
486  Kalyani  29/08/2008  NaN         Jyoti  310  320  320 NaN
487  Kalyani  30/08/2008   25  Chandermukhi  500  510  500 NaN
488  Kalyani  30/08/2008  NaN         Jyoti  320  330  320 NaN
489  Kalyani  31/08/2008   25  Chandermukhi  500  510  500 NaN
490  Kalyani  31/08/2008  NaN         Jyoti  320  330  320 NaN
           0           1    2             3    4    5    6   7
392  Kalyani  01/12/2008   30  Chandermukhi  790  800  800 NaN
393  Kalyani  01/12/2008  NaN         Jyoti  370  380  380 NaN
394  Kalyani  02/12/2008   30  Chandermukhi  790  800  800 NaN
395  Kalyani  02/12/2008  NaN         Jyoti  370  380  380 NaN
396  Kalyani  03/12/2008   25  Chandermukhi  780  800  800 NaN
397  Kalyani  03/12/2008  NaN         Jyoti  370  380  380 NaN
398  Kalyani  04/12/2008   30  Chandermukhi  780  800  800 NaN
399  Kalyani  04/12/2008  NaN         Jyoti  370  380  380 NaN
400  Kalyani  05/12/2008   30  Chandermukhi  770  780  780 NaN
401  Kalyani  05/12/2008  NaN         Jyoti  360  370  370 NaN
402  Kalyani  06/12/2008   30  Chandermukhi  770  780  770 NaN
403  Kalyani  06/12/2008  NaN         Jyoti  360  370  370 NaN
404  Kalyani  07/12/2008   30  Chandermukhi  760  770  760 NaN
405  Kalyani  07/12/2008  NaN         Jyoti  350  360  360 NaN
406  Kalyani  08/12/2008   30  Chandermukhi  740  750  740 NaN
407  Kalyani  08/12/2008  NaN         Jyoti  350  360  360 NaN
408  Kalyani  09/12/2008   30  Chandermukhi  740  750  740 NaN
409  Kalyani  09/12/2008  NaN         Jyoti  340  350  350 NaN
410  Kalyani  10/12/2008   30  Chandermukhi  720  740  730 NaN
411  Kalyani  10/12/2008  NaN         Jyoti  330  350  340 NaN
412  Kalyani  11/12/2008   30  Chandermukhi  720  740  730 NaN
413  Kalyani  11/12/2008  NaN         Jyoti  320  340  330 NaN
414  Kalyani  12/12/2008   30  Chandermukhi  700  720  700 NaN
415  Kalyani  12/12/2008  NaN         Jyoti  300  320  310 NaN
416  Kalyani  13/12/2008   30  Chandermukhi  680  700  680 NaN
417  Kalyani  13/12/2008  NaN         Jyoti  300  320  310 NaN
418  Kalyani  14/12/2008   25  Chandermukhi  680  700  680 NaN
419  Kalyani  14/12/2008  NaN         Jyoti  290  300  300 NaN
420  Kalyani  15/12/2008   30  Chandermukhi  680  700  700 NaN
421  Kalyani  15/12/2008  NaN         Jyoti  290  300  300 NaN
422  Kalyani  16/12/2008   25  Chandermukhi  680  700  700 NaN
423  Kalyani  16/12/2008  NaN         Jyoti  300  320  300 NaN
424  Kalyani  17/12/2008   25  Chandermukhi  700  720  700 NaN
425  Kalyani  17/12/2008  NaN         Jyoti  320  340  320 NaN
426  Kalyani  18/12/2008   25  Chandermukhi  700  720  700 NaN
427  Kalyani  18/12/2008  NaN         Jyoti  320  340  330 NaN
428  Kalyani  19/12/2008   30  Chandermukhi  700  720  700 NaN
429  Kalyani  19/12/2008  NaN         Jyoti  320  340  330 NaN
430  Kalyani  20/12/2008   25  Chandermukhi  720  740  720 NaN
431  Kalyani  20/12/2008  NaN         Jyoti  320  340  330 NaN
432  Kalyani  21/12/2008   25  Chandermukhi  730  750  740 NaN
433  Kalyani  21/12/2008  NaN         Jyoti  320  340  330 NaN
434  Kalyani  22/12/2008   25  Chandermukhi  730  750  740 NaN
435  Kalyani  22/12/2008  NaN         Jyoti  320  340  330 NaN
436  Kalyani  23/12/2008   25  Chandermukhi  730  750  740 NaN
437  Kalyani  23/12/2008  NaN         Jyoti  320  340  330 NaN
438  Kalyani  24/12/2008   25  Chandermukhi  740  760  750 NaN
439  Kalyani  24/12/2008  NaN         Jyoti  320  340  330 NaN
440  Kalyani  25/12/2008   30  Chandermukhi  780  800  780 NaN
441  Kalyani  25/12/2008  NaN         Jyoti  330  340  340 NaN
442  Kalyani  26/12/2008   25  Chandermukhi  780  800  800 NaN
443  Kalyani  26/12/2008  NaN         Jyoti  330  340  340 NaN
444  Kalyani  27/12/2008   25                 NR   NR   NR NaN
445  Kalyani  28/12/2008   25                 NR   NR   NR NaN
446  Kalyani  29/12/2008   20                 NR   NR   NR NaN
447  Kalyani  30/12/2008   25                 NR   NR   NR NaN
448  Kalyani  31/12/2008   25                 NR   NR   NR NaN

           0           1     2             3    4    5    6   7
363  Kalyani  05/02/2008     8  Chandermukhi  600  610  605 NaN
364  Kalyani  05/02/2008   NaN         Jyoti  500  520  510 NaN
365  Kalyani  07/02/2008     8  Chandermukhi  600  640  630 NaN
366  Kalyani  08/02/2008    20  Chandermukhi  580  610  600 NaN
367  Kalyani  08/02/2008   NaN         Jyoti  400  420  410 NaN
368  Kalyani  09/02/2008    25  Chandermukhi  585  620  600 NaN
369  Kalyani  09/02/2008   NaN         Jyoti  420  450  430 NaN
370  Kalyani  10/02/2008    25  Chandermukhi  590  630  600 NaN
371  Kalyani  10/02/2008   NaN         Jyoti  420  450  430 NaN
372  Kalyani  11/02/2008    20  Chandermukhi  580  620  590 NaN
373  Kalyani  11/02/2008   NaN         Jyoti  400  440  430 NaN
374  Kalyani  12/02/2008  22.5         Jyoti  440  460  450 NaN
375  Kalyani  13/02/2008    25  Chandermukhi  550  600  590 NaN
376  Kalyani  13/02/2008   NaN         Jyoti  400  420  400 NaN
377  Kalyani  14/02/2008    25  Chandermukhi  560  600  590 NaN
378  Kalyani  14/02/2008   NaN         Jyoti  400  420  400 NaN
379  Kalyani  15/02/2008    30  Chandermukhi  580  620  600 NaN
380  Kalyani  15/02/2008   NaN         Jyoti  400  430  400 NaN
381  Kalyani  16/02/2008    25  Chandermukhi  530  580  550 NaN
382  Kalyani  16/02/2008   NaN         Jyoti  360  400  380 NaN
383  Kalyani  17/02/2008    20  Chandermukhi  540  600  580 NaN
384  Kalyani  17/02/2008   NaN         Jyoti  400  420  400 NaN
385  Kalyani  18/02/2008    20  Chandermukhi  540  600  550 NaN
386  Kalyani  18/02/2008   NaN         Jyoti  380  420  400 NaN
387  Kalyani  19/02/2008   2.5  Chandermukhi  540  600  550 NaN
388  Kalyani  19/02/2008   NaN         Jyoti  380  420  400 NaN
389  Kalyani  20/02/2008    25  Chandermukhi  510  550  540 NaN
390  Kalyani  20/02/2008   NaN         Jyoti  380  420  400 NaN
391  Kalyani  21/02/2008    23  Chandermukhi  510  560  540 NaN
392  Kalyani  21/02/2008   NaN         Jyoti  380  420  400 NaN
393  Kalyani  22/02/2008    25  Chandermukhi  540  600  580 NaN
394  Kalyani  22/02/2008   NaN         Jyoti  400  450  430 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3    4    5    6   7
391  Kalyani  01/07/2008   30  Chandermukhi  540  560  550 NaN
392  Kalyani  01/07/2008  NaN         Jyoti  320  340  340 NaN
393  Kalyani  02/07/2008   25  Chandermukhi  540  560  550 NaN
394  Kalyani  02/07/2008  NaN         Jyoti  320  360  340 NaN
395  Kalyani  03/07/2008   30  Chandermukhi  550  560  550 NaN
396  Kalyani  03/07/2008  NaN         Jyoti  340  350  350 NaN
397  Kalyani  04/07/2008   25  Chandermukhi  540  550  550 NaN
398  Kalyani  04/07/2008  NaN         Jyoti  340  350  350 NaN
399  Kalyani  06/07/2008   25  Chandermukhi  550  570  560 NaN
400  Kalyani  06/07/2008  NaN         Jyoti  350  360  360 NaN
401  Kalyani  07/07/2008   25  Chandermukhi  560  570  570 NaN
402  Kalyani  07/07/2008  NaN         Jyoti  350  360  350 NaN
403  Kalyani  08/07/2008   25  Chandermukhi  560  580  580 NaN
404  Kalyani  08/07/2008  NaN         Jyoti  350  360  360 NaN
405  Kalyani  09/07/2008   25  Chandermukhi  560  580  580 NaN
406  Kalyani  09/07/2008  NaN         Jyoti  350  360  360 NaN
407  Kalyani  10/07/2008   25  Chandermukhi  560  580  580 NaN
408  Kalyani  10/07/2008  NaN         Jyoti  350  360  360 NaN
409  Kalyani  11/07/2008   25  Chandermukhi  550  560  550 NaN
410  Kalyani  11/07/2008  NaN         Jyoti  350  360  350 NaN
411  Kalyani  12/07/2008   25  Chandermukhi  550  560  550 NaN
412  Kalyani  12/07/2008  NaN         Jyoti  360  370  360 NaN
413  Kalyani  13/07/2008   25  Chandermukhi  550  560  550 NaN
414  Kalyani  13/07/2008  NaN         Jyoti  350  370  360 NaN
415  Kalyani  14/07/2008   25  Chandermukhi  550  570  560 NaN
416  Kalyani  14/07/2008  NaN         Jyoti  380  400  390 NaN
417  Kalyani  15/07/2008   25  Chandermukhi  550  570  550 NaN
418  Kalyani  15/07/2008  NaN         Jyoti  380  400  390 NaN
419  Kalyani  16/07/2008   25  Chandermukhi  550  570  550 NaN
420  Kalyani  16/07/2008  NaN         Jyoti  380  400  390 NaN
421  Kalyani  17/07/2008   25  Chandermukhi  550  570  550 NaN
422  Kalyani  17/07/2008  NaN         Jyoti  380  400  390 NaN
423  Kalyani  18/07/2008   25  Chandermukhi  550  570  550 NaN
424  Kalyani  18/07/2008  NaN         Jyoti  380  400  390 NaN
425  Kalyani  19/07/2008   25  Chandermukhi  550  570  550 NaN
426  Kalyani  19/07/2008  NaN         Jyoti  380  400  390 NaN
427  Kalyani  20/07/2008   25  Chandermukhi  550  570  550 NaN
428  Kalyani  20/07/2008  NaN         Jyoti  380  400  390 NaN
429  Kalyani  21/07/2008   25  Chandermukhi  550  560  560 NaN
430  Kalyani  21/07/2008  NaN         Jyoti  380  390  380 NaN
431  Kalyani  22/07/2008   25  Chandermukhi  550  560  560 NaN
432  Kalyani  22/07/2008  NaN         Jyoti  380  390  380 NaN
433  Kalyani  23/07/2008   25  Chandermukhi  560  580  580 NaN
434  Kalyani  23/07/2008  NaN         Jyoti  370  390  380 NaN
435  Kalyani  24/07/2008   25  Chandermukhi  560  580  580 NaN
436  Kalyani  24/07/2008  NaN         Jyoti  370  390  380 NaN
437  Kalyani  25/07/2008   25  Chandermukhi  560  580  580 NaN
438  Kalyani  25/07/2008  NaN         Jyoti  380  390  380 NaN
439  Kalyani  26/07/2008   30  Chandermukhi  560  580  580 NaN
440  Kalyani  26/07/2008  NaN         Jyoti  380  390  380 NaN
441  Kalyani  27/07/2008   25  Chandermukhi  560  580  580 NaN
442  Kalyani  27/07/2008  NaN         Jyoti  380  390  380 NaN
443  Kalyani  28/07/2008   20  Chandermukhi  570  580  580 NaN
444  Kalyani  28/07/2008  NaN         Jyoti  380  390  380 NaN
445  Kalyani  29/07/2008   30  Chandermukhi  570  580  580 NaN
446  Kalyani  29/07/2008  NaN         Jyoti  380  390  380 NaN
447  Kalyani  30/07/2008   25  Chandermukhi  560  570  560 NaN
448  Kalyani  30/07/2008  NaN         Jyoti  370  380  380 NaN
449  Kalyani  31/07/2008   25  Chandermukhi  560  570  560 NaN
450  Kalyani  31/07/2008  NaN         Jyoti  370  380  380 NaN
           0           1    2             3    4    5    6   7
406  Kalyani  16/06/2008   25  Chandermukhi  580  600  600 NaN
407  Kalyani  16/06/2008  NaN         Jyoti  380  400  400 NaN
408  Kalyani  17/06/2008   30  Chandermukhi  580  600  600 NaN
409  Kalyani  17/06/2008  NaN         Jyoti  380  400  400 NaN
410  Kalyani  18/06/2008   20  Chandermukhi  580  600  580 NaN
411  Kalyani  18/06/2008  NaN         Jyoti  380  400  380 NaN
412  Kalyani  19/06/2008   25  Chandermukhi  580  600  580 NaN
413  Kalyani  19/06/2008  NaN         Jyoti  380  400  380 NaN
414  Kalyani  20/06/2008   25  Chandermukhi  580  600  580 NaN
415  Kalyani  20/06/2008  NaN         Jyoti  380  400  380 NaN
416  Kalyani  21/06/2008   25  Chandermukhi  580  600  580 NaN
417  Kalyani  21/06/2008  NaN         Jyoti  360  380  380 NaN
418  Kalyani  22/06/2008   25  Chandermukhi  580  600  580 NaN
419  Kalyani  22/06/2008  NaN         Jyoti  360  380  380 NaN
420  Kalyani  23/06/2008   30  Chandermukhi  580  600  580 NaN
421  Kalyani  23/06/2008  NaN         Jyoti  360  380  370 NaN
422  Kalyani  24/06/2008   30  Chandermukhi  580  600  580 NaN
423  Kalyani  24/06/2008  NaN         Jyoti  350  360  360 NaN
424  Kalyani  25/06/2008   30  Chandermukhi  550  600  580 NaN
425  Kalyani  25/06/2008  NaN         Jyoti  350  380  360 NaN
426  Kalyani  26/06/2008   30  Chandermukhi  550  600  580 NaN
427  Kalyani  26/06/2008  NaN         Jyoti  350  360  360 NaN
428  Kalyani  27/06/2008   30  Chandermukhi  550  600  580 NaN
429  Kalyani  27/06/2008  NaN         Jyoti  350  380  360 NaN
430  Kalyani  28/06/2008   25  Chandermukhi  560  600  580 NaN
431  Kalyani  28/06/2008  NaN         Jyoti  350  360  360 NaN
432  Kalyani  29/06/2008   30  Chandermukhi  550  600  580 NaN
433  Kalyani  29/06/2008  NaN         Jyoti  350  360  360 NaN
434  Kalyani  30/06/2008   30  Chandermukhi  550  600  580 NaN
435  Kalyani  30/06/2008  NaN         Jyoti  350  360  360 NaN
           0           1    2             3    4    5    6   7
349  Kalyani  01/03/2008   30  Chandermukhi  520  580  560 NaN
350  Kalyani  01/03/2008  NaN         Jyoti  370  400  385 NaN
351  Kalyani  02/03/2008   30  Chandermukhi  520  580  560 NaN
352  Kalyani  02/03/2008  NaN         Jyoti  370  400  385 NaN
353  Kalyani  03/03/2008   25  Chandermukhi  520  580  560 NaN
354  Kalyani  03/03/2008  NaN         Jyoti  370  400  390 NaN
355  Kalyani  04/03/2008   30  Chandermukhi  530  570  550 NaN
356  Kalyani  04/03/2008  NaN         Jyoti  350  380  370 NaN
357  Kalyani  05/03/2008   30  Chandermukhi  540  560  550 NaN
358  Kalyani  05/03/2008  NaN         Jyoti  370  410  390 NaN
359  Kalyani  06/03/2008   30  Chandermukhi  530  570  550 NaN
360  Kalyani  06/03/2008  NaN         Jyoti  350  390  370 NaN
361  Kalyani  07/03/2008   25  Chandermukhi  540  560  550 NaN
362  Kalyani  07/03/2008  NaN         Jyoti  350  390  375 NaN
363  Kalyani  08/03/2008   30  Chandermukhi  540  560  550 NaN
364  Kalyani  08/03/2008  NaN         Jyoti  330  400  370 NaN
365  Kalyani  09/03/2008   25  Chandermukhi  540  560  550 NaN
366  Kalyani  09/03/2008  NaN         Jyoti  330  360  350 NaN
367  Kalyani  10/03/2008   25  Chandermukhi  540  570  560 NaN
368  Kalyani  10/03/2008  NaN         Jyoti  320  360  350 NaN
369  Kalyani  11/03/2008   35  Chandermukhi  560  580  570 NaN
370  Kalyani  11/03/2008  NaN         Jyoti  320  360  340 NaN
371  Kalyani  12/03/2008   30  Chandermukhi  560  590  580 NaN
372  Kalyani  12/03/2008  NaN         Jyoti  320  360  350 NaN
373  Kalyani  13/03/2008   30  Chandermukhi  330  380  360 NaN
374  Kalyani  13/03/2008  NaN         Jyoti  320  380  360 NaN
375  Kalyani  14/03/2008   30  Chandermukhi  570  600  590 NaN
376  Kalyani  14/03/2008  NaN         Jyoti  330  380  360 NaN
377  Kalyani  15/03/2008   30  Chandermukhi  540  580  560 NaN
378  Kalyani  15/03/2008  NaN         Jyoti  320  350  330 NaN
379  Kalyani  16/03/2008   30  Chandermukhi  540  580  560 NaN
380  Kalyani  16/03/2008  NaN         Jyoti  300  330  330 NaN
381  Kalyani  17/03/2008   25  Chandermukhi  540  580  560 NaN
382  Kalyani  17/03/2008  NaN         Jyoti  300  320  320 NaN
383  Kalyani  18/03/2008   30  Chandermukhi  530  570  550 NaN
384  Kalyani  18/03/2008  NaN         Jyoti  290  320  300 NaN
385  Kalyani  19/03/2008   30  Chandermukhi  500  530  520 NaN
386  Kalyani  19/03/2008  NaN         Jyoti  280  300  300 NaN
387  Kalyani  20/03/2008   30  Chandermukhi  500  530  520 NaN
388  Kalyani  20/03/2008  NaN         Jyoti  280  300  300 NaN
389  Kalyani  21/03/2008   30  Chandermukhi  500  540  520 NaN
390  Kalyani  21/03/2008  NaN         Jyoti  280  300  300 NaN
391  Kalyani  22/03/2008   25  Chandermukhi  510  550  530 NaN
392  Kalyani  22/03/2008  NaN         Jyoti  270  300  285 NaN
393  Kalyani  23/03/2008   25  Chandermukhi  510  550  530 NaN
394  Kalyani  23/03/2008  NaN         Jyoti  280  300  300 NaN
395  Kalyani  24/03/2008   30  Chandermukhi  520  560  530 NaN
396  Kalyani  24/03/2008  NaN         Jyoti  300  320  310 NaN
397  Kalyani  25/03/2008   25  Chandermukhi  500  540  520 NaN
398  Kalyani  25/03/2008  NaN         Jyoti  300  320  300 NaN
399  Kalyani  26/03/2008   25  Chandermukhi  500  540  520 NaN
400  Kalyani  26/03/2008  NaN         Jyoti  300  320  300 NaN
401  Kalyani  27/03/2008   25  Chandermukhi  480  520  500 NaN
402  Kalyani  27/03/2008  NaN         Jyoti  280  300  300 NaN
403  Kalyani  28/03/2008   25  Chandermukhi  480  520  500 NaN
404  Kalyani  28/03/2008  NaN         Jyoti  300  320  300 NaN

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3    4    5    6   7
489  Kalyani  01/11/2008   25  Chandermukhi  620  630  620 NaN
490  Kalyani  01/11/2008  NaN         Jyoti  320  330  330 NaN
491  Kalyani  02/11/2008   25  Chandermukhi  630  650  650 NaN
492  Kalyani  02/11/2008  NaN         Jyoti  320  330  330 NaN
493  Kalyani  03/11/2008   25  Chandermukhi  640  700  670 NaN
494  Kalyani  03/11/2008  NaN         Jyoti  320  330  330 NaN
495  Kalyani  04/11/2008   25  Chandermukhi  640  700  670 NaN
496  Kalyani  04/11/2008  NaN         Jyoti  320  330  330 NaN
497  Kalyani  05/11/2008   25  Chandermukhi  640  680  670 NaN
498  Kalyani  05/11/2008  NaN         Jyoti  320  330  330 NaN
499  Kalyani  06/11/2008   25  Chandermukhi  640  680  670 NaN
500  Kalyani  06/11/2008  NaN         Jyoti  320  330  330 NaN
501  Kalyani  07/11/2008   25  Chandermukhi  650  680  670 NaN
502  Kalyani  07/11/2008  NaN         Jyoti  320  330  330 NaN
503  Kalyani  09/11/2008   25  Chandermukhi  650  680  670 NaN
504  Kalyani  09/11/2008  NaN         Jyoti  320  330  330 NaN
           0           1   2             3    4    5    6   7
465  Kalyani  01/10/2008  25  Chandermukhi  520  530  530 NaN
466  Kalyani  02/10/2008  25  Chandermukhi  530  560  550 NaN
467  Kalyani  03/10/2008  25  Chandermukhi  540  560  550 NaN
           0           1    2             3    4    5    6   7
508  Kalyani  01/09/2008   25  Chandermukhi  500  510  500 NaN
509  Kalyani  01/09/2008  NaN         Jyoti  320  330  320 NaN
510  Kalyani  02/09/2008   25  Chandermukhi  500  510  500 NaN
511  Kalyani  02/09/2008  NaN         Jyoti  320  330  320 NaN
512  Kalyani  03/09/2008   25  Chandermukhi  530  540  530 NaN
513  Kalyani  03/09/2008  NaN         Jyoti  330  340  330 NaN
514  Kalyani  04/09/2008   25  Chandermukhi  530  540  530 NaN
515  Kalyani  04/09/2008  NaN         Jyoti  330  340  330 NaN
516  Kalyani  05/09/2008   25  Chandermukhi  530  550  540 NaN
517  Kalyani  05/09/2008  NaN         Jyoti  330  340  330 NaN
518  Kalyani  06/09/2008   25  Chandermukhi  530  550  540 NaN
519  Kalyani  06/09/2008  NaN         Jyoti  330  340  330 NaN
520  Kalyani  07/09/2008   20  Chandermukhi  530  550  540 NaN
521  Kalyani  07/09/2008  NaN         Jyoti  330  340  330 NaN
522  Kalyani  08/09/2008   25  Chandermukhi  530  550  540 NaN
523  Kalyani  08/09/2008  NaN         Jyoti  330  350  340 NaN
524  Kalyani  09/09/2008   25  Chandermukhi  530  550  540 NaN
525  Kalyani  09/09/2008  NaN         Jyoti  330  350  340 NaN
526  Kalyani  10/09/2008   25  Chandermukhi  530  550  540 NaN
527  Kalyani  10/09/2008  NaN         Jyoti  330  350  340 NaN
528  Kalyani  11/09/2008   25  Chandermukhi  530  550  540 NaN
529  Kalyani  11/09/2008  NaN         Jyoti  320  340  330 NaN
530  Kalyani  12/09/2008   25  Chandermukhi  530  550  540 NaN
531  Kalyani  12/09/2008  NaN         Jyoti  320  340  330 NaN
532  Kalyani  13/09/2008   25  Chandermukhi  530  540  530 NaN
533  Kalyani  13/09/2008  NaN         Jyoti  320  330  330 NaN
534  Kalyani  14/09/2008   25  Chandermukhi  520  530  520 NaN
535  Kalyani  14/09/2008  NaN         Jyoti  320  330  330 NaN
536  Kalyani  15/09/2008   25  Chandermukhi  520  530  520 NaN
537  Kalyani  15/09/2008  NaN         Jyoti  320  330  330 NaN
538  Kalyani  16/09/2008   30  Chandermukhi  520  530  530 NaN
539  Kalyani  16/09/2008  NaN         Jyoti  320  330  330 NaN
540  Kalyani  17/09/2008   25  Chandermukhi  520  530  530 NaN
541  Kalyani  17/09/2008  NaN         Jyoti  320  330  330 NaN
542  Kalyani  18/09/2008   25  Chandermukhi  520  530  520 NaN
543  Kalyani  18/09/2008  NaN         Jyoti  320  330  320 NaN
544  Kalyani  19/09/2008   25  Chandermukhi  520  530  520 NaN
545  Kalyani  19/09/2008  NaN         Jyoti  320  330  320 NaN
546  Kalyani  20/09/2008   25  Chandermukhi  510  520  520 NaN
547  Kalyani  20/09/2008  NaN         Jyoti  310  320  320 NaN
548  Kalyani  21/09/2008   25  Chandermukhi  510  520  520 NaN
549  Kalyani  21/09/2008  NaN         Jyoti  310  320  320 NaN
550  Kalyani  22/09/2008   25  Chandermukhi  510  520  520 NaN
551  Kalyani  22/09/2008  NaN         Jyoti  300  310  310 NaN
552  Kalyani  23/09/2008   25  Chandermukhi  510  520  520 NaN
553  Kalyani  23/09/2008  NaN         Jyoti  300  310  310 NaN
554  Kalyani  24/09/2008   25  Chandermukhi  520  530  520 NaN
555  Kalyani  24/09/2008  NaN         Jyoti  320  330  320 NaN
556  Kalyani  25/09/2008   25  Chandermukhi  520  530  520 NaN
557  Kalyani  25/09/2008  NaN         Jyoti  320  330  320 NaN
558  Kalyani  26/09/2008   25  Chandermukhi  520  530  530 NaN
559  Kalyani  26/09/2008  NaN         Jyoti  320  330  330 NaN
560  Kalyani  27/09/2008   20  Chandermukhi  520  530  530 NaN
561  Kalyani  27/09/2008  NaN         Jyoti  320  330  320 NaN
562  Kalyani  28/09/2008   25  Chandermukhi  520  530  530 NaN
563  Kalyani  28/09/2008  NaN         Jyoti  320  330  320 NaN
564  Kalyani  29/09/2008   25  Chandermukhi  520  530  530 NaN
565  Kalyani  29/09/2008  NaN         Jyoti  320  330  320 NaN
566  Kalyani  30/09/2008   25  Chandermukhi  520  530  520 NaN
567  Kalyani  30/09/2008  NaN         Jyoti  320  330  320 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3    4    5    6   7
377  Kalyani  01/01/2009   25  Chandermukhi  700  740  720 NaN
378  Kalyani  01/01/2009  NaN         Jyoti  330  340  330 NaN
379  Kalyani  02/01/2009   25  Chandermukhi  700  740  720 NaN
380  Kalyani  02/01/2009  NaN         Jyoti  330  340  330 NaN
381  Kalyani  03/01/2009   25  Chandermukhi  700  740  720 NaN
382  Kalyani  03/01/2009  NaN         Jyoti  390  400  390 NaN
383  Kalyani  04/01/2009   25  Chandermukhi  700  720  720 NaN
384  Kalyani  04/01/2009  NaN         Jyoti  410  440  430 NaN
385  Kalyani  05/01/2009   20  Chandermukhi  680  700  700 NaN
386  Kalyani  05/01/2009  NaN         Jyoti  430  440  430 NaN
387  Kalyani  06/01/2009   25  Chandermukhi  680  700  700 NaN
388  Kalyani  06/01/2009  NaN         Jyoti  430  440  430 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3    4    5    6   7
657  Kalyani  01/08/2010   30  Chandermukhi  680  710  700 NaN
658  Kalyani  01/08/2010  NaN         Jyoti  440  460  450 NaN
659  Kalyani  02/08/2010   30  Chandermukhi  690  710  700 NaN
660  Kalyani  02/08/2010  NaN         Jyoti  460  480  470 NaN
661  Kalyani  03/08/2010   28  Chandermukhi  690  710  700 NaN
662  Kalyani  03/08/2010  NaN         Jyoti  460  480  470 NaN
663  Kalyani  04/08/2010   28  Chandermukhi  690  710  700 NaN
664  Kalyani  04/08/2010  NaN         Jyoti  460  480  470 NaN
665  Kalyani  05/08/2010   30  Chandermukhi  690  710  700 NaN
666  Kalyani  05/08/2010  NaN         Jyoti  460  480  470 NaN
667  Kalyani  06/08/2010   30  Chandermukhi  690  710  700 NaN
668  Kalyani  06/08/2010  NaN         Jyoti  460  480  470 NaN
669  Kalyani  07/08/2010   30  Chandermukhi  670  690  680 NaN
670  Kalyani  07/08/2010  NaN         Jyoti  440  460  450 NaN
671  Kalyani  08/08/2010   30  Chandermukhi  670  690  680 NaN
672  Kalyani  08/08/2010  NaN         Jyoti  440  460  450 NaN
673  Kalyani  09/08/2010   30  Chandermukhi  670  690  680 NaN
674  Kalyani  09/08/2010  NaN         Jyoti  440  460  450 NaN
675  Kalyani  10/08/2010   30  Chandermukhi  670  690  680 NaN
676  Kalyani  10/08/2010  NaN         Jyoti  440  460  450 NaN
677  Kalyani  11/08/2010   30         Jyoti  440  460  450 NaN
678  Kalyani  12/08/2010   30  Chandermukhi  670  690  680 NaN
679  Kalyani  12/08/2010  NaN         Jyoti  440  460  450 NaN
680  Kalyani  12/08/2010  NaN         Other  670  690  680 NaN
681  Kalyani  13/08/2010   30  Chandermukhi  670  690  680 NaN
682  Kalyani  13/08/2010  NaN         Jyoti  440  460  450 NaN
683  Kalyani  14/08/2010   30  Chandermukhi  670  690  680 NaN
684  Kalyani  14/08/2010  NaN         Jyoti  440  460  450 NaN
685  Kalyani  15/08/2010   30  Chandermukhi  670  690  680 NaN
686  Kalyani  15/08/2010  NaN         Jyoti  440  460  450 NaN
..       ...         ...  ...           ...  ...  ...  ...  ..
689  Kalyani  17/08/2010   20  Chandermukhi  670  690  680 NaN
690  Kalyani  17/08/2010  NaN         Jyoti  440  460  450 NaN
691  Kalyani  18/08/2010   25  Chandermukhi  670  690  680 NaN
692  Kalyani  18/08/2010  NaN         Jyoti  440  460  450 NaN
693  Kalyani  19/08/2010   25  Chandermukhi  670  690  680 NaN
694  Kalyani  19/08/2010  NaN         Jyoti  440  460  450 NaN
695  Kalyani  20/08/2010   25  Chandermukhi  670  690  680 NaN
696  Kalyani  20/08/2010  NaN         Jyoti  440  460  450 NaN
697  Kalyani  21/08/2010   30  Chandermukhi  680  700  690 NaN
698  Kalyani  21/08/2010  NaN         Jyoti  440  460  450 NaN
699  Kalyani  22/08/2010   30  Chandermukhi  680  700  690 NaN
700  Kalyani  22/08/2010  NaN         Jyoti  450  470  460 NaN
701  Kalyani  23/08/2010   20  Chandermukhi  700  730  720 NaN
702  Kalyani  23/08/2010  NaN         Jyoti  470  490  480 NaN
703  Kalyani  24/08/2010   20  Chandermukhi  700  730  720 NaN
704  Kalyani  24/08/2010  NaN         Jyoti  490  510  500 NaN
705  Kalyani  25/08/2010   15  Chandermukhi  700  730  720 NaN
706  Kalyani  25/08/2010  NaN         Jyoti  490  510  500 NaN
707  Kalyani  26/08/2010   20  Chandermukhi  700  730  720 NaN
708  Kalyani  26/08/2010  NaN         Jyoti  490  510  500 NaN
709  Kalyani  27/08/2010   20  Chandermukhi  700  720  710 NaN
710  Kalyani  27/08/2010  NaN         Jyoti  490  510  500 NaN
711  Kalyani  28/08/2010   20  Chandermukhi  700  720  710 NaN
712  Kalyani  28/08/2010  NaN         Jyoti  490  510  500 NaN
713  Kalyani  29/08/2010   20  Chandermukhi  700  720  710 NaN
714  Kalyani  29/08/2010  NaN         Jyoti  490  510  500 NaN
715  Kalyani  30/08/2010   20  Chandermukhi  700  720  710 NaN
716  Kalyani  30/08/2010  NaN         Jyoti  490  510  500 NaN
717  Kalyani  31/08/2010   20  Chandermukhi  700  720  710 NaN
718  Kalyani  31/08/2010  NaN         Jyoti  490  510  500 NaN

[62 rows x 8 columns]

           0           1    2             3    4    5    6   7
710  Kalyani  01/12/2010   23  Chandermukhi  840  860  850 NaN
711  Kalyani  01/12/2010  NaN         Jyoti  640  660  650 NaN
712  Kalyani  02/12/2010   23  Chandermukhi  860  880  870 NaN
713  Kalyani  02/12/2010  NaN         Jyoti  640  660  650 NaN
714  Kalyani  03/12/2010   24  Chandermukhi  820  840  830 NaN
715  Kalyani  03/12/2010  NaN         Jyoti  640  660  650 NaN
716  Kalyani  04/12/2010   24  Chandermukhi  820  840  830 NaN
717  Kalyani  04/12/2010  NaN         Jyoti  640  660  650 NaN
718  Kalyani  05/12/2010   24  Chandermukhi  820  840  830 NaN
719  Kalyani  05/12/2010  NaN         Jyoti  630  650  640 NaN
720  Kalyani  06/12/2010   24  Chandermukhi  830  850  840 NaN
721  Kalyani  06/12/2010  NaN         Jyoti  630  650  640 NaN
722  Kalyani  07/12/2010   23  Chandermukhi  830  850  840 NaN
723  Kalyani  07/12/2010  NaN         Jyoti  630  650  640 NaN
724  Kalyani  08/12/2010   23  Chandermukhi  830  850  840 NaN
725  Kalyani  08/12/2010  NaN         Jyoti  630  650  640 NaN
726  Kalyani  09/12/2010   25  Chandermukhi  830  850  840 NaN
727  Kalyani  09/12/2010  NaN         Jyoti  630  650  640 NaN
728  Kalyani  10/12/2010   25  Chandermukhi  830  850  840 NaN
729  Kalyani  10/12/2010  NaN         Jyoti  630  650  640 NaN
730  Kalyani  11/12/2010   24  Chandermukhi  830  850  840 NaN
731  Kalyani  11/12/2010  NaN         Jyoti  630  650  640 NaN
732  Kalyani  12/12/2010   25  Chandermukhi  800  840  820 NaN
733  Kalyani  12/12/2010  NaN         Jyoti  630  650  640 NaN
734  Kalyani  13/12/2010   22  Chandermukhi  800  840  820 NaN
735  Kalyani  13/12/2010  NaN         Jyoti  630  650  640 NaN
736  Kalyani  14/12/2010   23  Chandermukhi  800  840  820 NaN
737  Kalyani  14/12/2010  NaN         Jyoti  630  650  640 NaN
738  Kalyani  15/12/2010   25  Chandermukhi  800  840  820 NaN
739  Kalyani  15/12/2010  NaN         Jyoti  630  660  650 NaN
740  Kalyani  16/12/2010   25         Jyoti  630  660  650 NaN
741  Kalyani  17/12/2010   26  Chandermukhi  820  860  840 NaN
742  Kalyani  17/12/2010  NaN         Jyoti  620  640  630 NaN
743  Kalyani  18/12/2010   24  Chandermukhi  820  860  840 NaN
744  Kalyani  18/12/2010  NaN         Jyoti  620  640  630 NaN
745  Kalyani  19/12/2010   24  Chandermukhi  820  860  840 NaN
746  Kalyani  19/12/2010  NaN         Jyoti  620  660  640 NaN
747  Kalyani  20/12/2010   25  Chandermukhi  820  860  840 NaN
748  Kalyani  20/12/2010  NaN         Jyoti  620  660  640 NaN
749  Kalyani  21/12/2010   25  Chandermukhi  880  920  900 NaN
750  Kalyani  21/12/2010  NaN         Jyoti  620  660  640 NaN
751  Kalyani  22/12/2010   24  Chandermukhi  880  920  900 NaN
752  Kalyani  22/12/2010  NaN         Jyoti  620  660  640 NaN
753  Kalyani  23/12/2010   25  Chandermukhi  880  920  900 NaN
754  Kalyani  23/12/2010  NaN         Jyoti  620  660  640 NaN
755  Kalyani  24/12/2010   30                 NR   NR   NR NaN
756  Kalyani  25/12/2010   30                 NR   NR   NR NaN
757  Kalyani  26/12/2010   40                 NR   NR   NR NaN
758  Kalyani  27/12/2010   40                 NR   NR   NR NaN
759  Kalyani  28/12/2010   40                 NR   NR   NR NaN
760  Kalyani  29/12/2010   40                 NR   NR   NR NaN
761  Kalyani  30/12/2010   40                 NR   NR   NR NaN
762  Kalyani  31/12/2010   35                 NR   NR   NR NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3     4     5     6   7
567  Kalyani  01/11/2010   24         Jyoti   630   650   640 NaN
568  Kalyani  02/11/2010   25         Jyoti   620   640   630 NaN
569  Kalyani  03/11/2010   24         Jyoti   610   630   620 NaN
570  Kalyani  04/11/2010   24         Jyoti   610   630   620 NaN
571  Kalyani  05/11/2010   24         Jyoti   610   630   620 NaN
572  Kalyani  06/11/2010   24         Jyoti   610   630   620 NaN
573  Kalyani  07/11/2010   24  Chandermukhi   750   780   770 NaN
574  Kalyani  07/11/2010  NaN         Jyoti   620   640   630 NaN
575  Kalyani  08/11/2010   22  Chandermukhi   765   790   780 NaN
576  Kalyani  08/11/2010  NaN         Jyoti   630   650   640 NaN
577  Kalyani  09/11/2010   22  Chandermukhi   765   790   780 NaN
578  Kalyani  09/11/2010  NaN         Jyoti   630   650   640 NaN
579  Kalyani  10/11/2010   23  Chandermukhi   750   770   760 NaN
580  Kalyani  10/11/2010  NaN         Jyoti   610   625   625 NaN
581  Kalyani  11/11/2010   23  Chandermukhi   740   750   740 NaN
582  Kalyani  11/11/2010  NaN         Jyoti   600   620   620 NaN
583  Kalyani  12/11/2010   23  Chandermukhi   730   750   740 NaN
584  Kalyani  12/11/2010  NaN         Jyoti   590   610   600 NaN
585  Kalyani  13/11/2010   25  Chandermukhi   730   750   740 NaN
586  Kalyani  13/11/2010  NaN         Jyoti   590   620   600 NaN
587  Kalyani  14/11/2010   25  Chandermukhi   730   750   740 NaN
588  Kalyani  14/11/2010  NaN         Jyoti   600   620   610 NaN
589  Kalyani  15/11/2010   23  Chandermukhi   780   800   790 NaN
590  Kalyani  15/11/2010  NaN         Jyoti   680   700   690 NaN
591  Kalyani  16/11/2010   23  Chandermukhi   800   840   820 NaN
592  Kalyani  16/11/2010  NaN         Jyoti   700   730   720 NaN
593  Kalyani  17/11/2010   23  Chandermukhi   810   840   820 NaN
594  Kalyani  17/11/2010  NaN         Jyoti   710   740   725 NaN
595  Kalyani  18/11/2010   23  Chandermukhi   820   840   830 NaN
596  Kalyani  18/11/2010  NaN         Jyoti   720   740   730 NaN
597  Kalyani  19/11/2010   22  Chandermukhi   825   850   840 NaN
598  Kalyani  19/11/2010  NaN         Jyoti   725   750   740 NaN
599  Kalyani  20/11/2010   22  Chandermukhi   825   850   840 NaN
600  Kalyani  20/11/2010  NaN         Jyoti   730   760   745 NaN
601  Kalyani  21/11/2010   22  Chandermukhi   825   850   840 NaN
602  Kalyani  21/11/2010  NaN         Jyoti   740   760   750 NaN
603  Kalyani  21/11/2010  NaN         Other  2600  2750  2700 NaN
604  Kalyani  22/11/2010   22  Chandermukhi   825   850   840 NaN
605  Kalyani  22/11/2010  NaN         Jyoti   740   760   750 NaN
606  Kalyani  23/11/2010   22  Chandermukhi   840   880   860 NaN
607  Kalyani  23/11/2010  NaN         Jyoti   740   770   760 NaN
608  Kalyani  23/11/2010  NaN         Other  1900  1950  1950 NaN
609  Kalyani  24/11/2010   25  Chandermukhi   880   910   900 NaN
610  Kalyani  24/11/2010  NaN         Jyoti   740   760   750 NaN
611  Kalyani  26/11/2010   25  Chandermukhi   850   890   870 NaN
612  Kalyani  26/11/2010  NaN         Jyoti   700   740   720 NaN
613  Kalyani  27/11/2010   25  Chandermukhi   820   860   840 NaN
614  Kalyani  27/11/2010  NaN         Jyoti   660   700   680 NaN
615  Kalyani  28/11/2010   25  Chandermukhi   800   830   820 NaN
616  Kalyani  28/11/2010  NaN         Jyoti   640   680   660 NaN
617  Kalyani  29/11/2010   23  Chandermukhi   790   810   800 NaN
618  Kalyani  29/11/2010  NaN         Jyoti   640   680   660 NaN
619  Kalyani  30/11/2010   23  Chandermukhi   830   850   840 NaN
620  Kalyani  30/11/2010  NaN         Jyoti   640   660   650 NaN
           0           1    2             3     4     5     6   7
484  Kalyani  01/10/2010   22  Chandermukhi   900   930   920 NaN
485  Kalyani  01/10/2010  NaN         Jyoti   720   750   740 NaN
486  Kalyani  02/10/2010   22  Chandermukhi   900   930   920 NaN
487  Kalyani  02/10/2010  NaN         Jyoti   730   760   750 NaN
488  Kalyani  03/10/2010   22  Chandermukhi   870   900   880 NaN
489  Kalyani  03/10/2010  NaN         Jyoti   720   750   730 NaN
490  Kalyani  04/10/2010   22  Chandermukhi   870   900   880 NaN
491  Kalyani  04/10/2010  NaN         Jyoti   720   750   730 NaN
492  Kalyani  05/10/2010   22  Chandermukhi   870   900   880 NaN
493  Kalyani  05/10/2010  NaN         Jyoti   720   750   730 NaN
494  Kalyani  06/10/2010   22  Chandermukhi   870   900   880 NaN
495  Kalyani  06/10/2010  NaN         Jyoti   720   750   730 NaN
496  Kalyani  07/10/2010   22  Chandermukhi   870   900   880 NaN
497  Kalyani  07/10/2010  NaN         Jyoti   720   750   730 NaN
498  Kalyani  08/10/2010   22  Chandermukhi   870   900   880 NaN
499  Kalyani  08/10/2010  NaN         Jyoti   720   750   730 NaN
500  Kalyani  09/10/2010   22  Chandermukhi   870   900   880 NaN
501  Kalyani  09/10/2010  NaN         Jyoti   720   750   730 NaN
502  Kalyani  10/10/2010   25  Chandermukhi   870   900   880 NaN
503  Kalyani  10/10/2010  NaN         Jyoti   710   730   720 NaN
504  Kalyani  11/10/2010   25  Chandermukhi   870   900   880 NaN
505  Kalyani  11/10/2010  NaN         Jyoti   690   710   700 NaN
506  Kalyani  12/10/2010   25  Chandermukhi   870   900   880 NaN
507  Kalyani  12/10/2010  NaN         Jyoti   690   710   700 NaN
508  Kalyani  13/10/2010   25  Chandermukhi   850   860   860 NaN
509  Kalyani  13/10/2010  NaN         Jyoti   690   710   700 NaN
510  Kalyani  14/10/2010   25  Chandermukhi   840   860   860 NaN
511  Kalyani  14/10/2010  NaN         Jyoti   700   720   720 NaN
512  Kalyani  15/10/2010   23  Chandermukhi   850   880   880 NaN
513  Kalyani  15/10/2010  NaN         Jyoti   700   720   720 NaN
514  Kalyani  16/10/2010   23  Chandermukhi   850   880   880 NaN
515  Kalyani  16/10/2010  NaN         Jyoti   700   720   720 NaN
516  Kalyani  16/10/2010  NaN         Other  1900  2000  1950 NaN
517  Kalyani  17/10/2010   23  Chandermukhi   850   890   880 NaN
518  Kalyani  17/10/2010  NaN         Jyoti   700   720   720 NaN
519  Kalyani  18/10/2010   23  Chandermukhi   850   900   880 NaN
520  Kalyani  18/10/2010  NaN         Jyoti   700   720   720 NaN
521  Kalyani  19/10/2010   23  Chandermukhi   850   900   880 NaN
522  Kalyani  19/10/2010  NaN         Jyoti   700   730   720 NaN
523  Kalyani  20/10/2010   23  Chandermukhi   850   900   880 NaN
524  Kalyani  20/10/2010  NaN         Jyoti   710   740   730 NaN
525  Kalyani  21/10/2010   25  Chandermukhi   860   920   900 NaN
526  Kalyani  21/10/2010  NaN         Jyoti   720   760   740 NaN
527  Kalyani  22/10/2010   23  Chandermukhi   920   950   940 NaN
528  Kalyani  22/10/2010  NaN         Jyoti   725   750   740 NaN
529  Kalyani  23/10/2010   23  Chandermukhi   920   950   940 NaN
530  Kalyani  23/10/2010  NaN         Jyoti   725   750   740 NaN
531  Kalyani  24/10/2010   24  Chandermukhi   910   940   930 NaN
532  Kalyani  24/10/2010  NaN         Jyoti   710   740   720 NaN
533  Kalyani  25/10/2010   24  Chandermukhi   910   940   930 NaN
534  Kalyani  25/10/2010  NaN         Jyoti   710   740   725 NaN
535  Kalyani  26/10/2010   24  Chandermukhi   910   940   930 NaN
536  Kalyani  26/10/2010  NaN         Jyoti   710   740   725 NaN
537  Kalyani  27/10/2010   24  Chandermukhi   900   920   910 NaN
538  Kalyani  27/10/2010  NaN         Jyoti   700   720   710 NaN
539  Kalyani  28/10/2010   24  Chandermukhi   900   920   910 NaN
540  Kalyani  28/10/2010  NaN         Jyoti   700   720   710 NaN
541  Kalyani  29/10/2010   24         Jyoti   650   670   660 NaN
542  Kalyani  30/10/2010   24         Jyoti   640   660   650 NaN
543  Kalyani  31/10/2010   25         Jyoti   630   650   640 NaN

           0           1    2             3     4     5     6   7
561  Kalyani  01/09/2010   20  Chandermukhi   750   770   760 NaN
562  Kalyani  01/09/2010  NaN         Jyoti   520   550   540 NaN
563  Kalyani  02/09/2010   17  Chandermukhi   760   790   780 NaN
564  Kalyani  02/09/2010  NaN         Jyoti   550   570   560 NaN
565  Kalyani  03/09/2010   18  Chandermukhi   730   770   750 NaN
566  Kalyani  03/09/2010  NaN         Jyoti   540   570   550 NaN
567  Kalyani  04/09/2010   20  Chandermukhi   720   760   740 NaN
568  Kalyani  04/09/2010  NaN         Jyoti   520   560   540 NaN
569  Kalyani  05/09/2010   20  Chandermukhi   700   750   720 NaN
570  Kalyani  05/09/2010  NaN         Jyoti   500   550   530 NaN
571  Kalyani  06/09/2010   18  Chandermukhi   720   760   740 NaN
572  Kalyani  06/09/2010  NaN         Jyoti   500   550   530 NaN
573  Kalyani  07/09/2010   18  Chandermukhi   720   760   740 NaN
574  Kalyani  07/09/2010  NaN         Jyoti   500   550   530 NaN
575  Kalyani  08/09/2010   21  Chandermukhi   725   780   750 NaN
576  Kalyani  08/09/2010  NaN         Jyoti   550   570   560 NaN
577  Kalyani  09/09/2010   20  Chandermukhi   730   780   760 NaN
578  Kalyani  09/09/2010  NaN         Jyoti   550   570   560 NaN
579  Kalyani  10/09/2010   18  Chandermukhi   730   780   760 NaN
580  Kalyani  10/09/2010  NaN         Jyoti   560   600   580 NaN
581  Kalyani  11/09/2010   21  Chandermukhi   750   800   780 NaN
582  Kalyani  11/09/2010  NaN         Jyoti   560   600   580 NaN
583  Kalyani  12/09/2010   20  Chandermukhi   750   800   780 NaN
584  Kalyani  12/09/2010  NaN         Jyoti   570   610   590 NaN
585  Kalyani  13/09/2010   18  Chandermukhi   750   820   800 NaN
586  Kalyani  13/09/2010  NaN         Jyoti   580   610   600 NaN
587  Kalyani  14/09/2010   18  Chandermukhi   750   820   800 NaN
588  Kalyani  14/09/2010  NaN         Jyoti   580   610   600 NaN
589  Kalyani  15/09/2010   20  Chandermukhi   750   770   760 NaN
590  Kalyani  15/09/2010  NaN         Jyoti   580   600   590 NaN
591  Kalyani  16/09/2010   20  Chandermukhi   750   770   760 NaN
592  Kalyani  16/09/2010  NaN         Jyoti   580   600   590 NaN
593  Kalyani  17/09/2010   20  Chandermukhi   750   770   760 NaN
594  Kalyani  17/09/2010  NaN         Jyoti   580   600   590 NaN
595  Kalyani  18/09/2010   20  Chandermukhi   750   770   760 NaN
596  Kalyani  18/09/2010  NaN         Jyoti   580   600   590 NaN
597  Kalyani  19/09/2010   22  Chandermukhi   750   770   760 NaN
598  Kalyani  19/09/2010  NaN         Jyoti   580   600   590 NaN
599  Kalyani  20/09/2010   20  Chandermukhi   750   800   780 NaN
600  Kalyani  20/09/2010  NaN         Jyoti   580   625   600 NaN
601  Kalyani  21/09/2010   20  Chandermukhi   780   825   800 NaN
602  Kalyani  21/09/2010  NaN         Jyoti   600   650   640 NaN
603  Kalyani  22/09/2010   20  Chandermukhi   825   850   850 NaN
604  Kalyani  22/09/2010  NaN         Jyoti   630   650   650 NaN
605  Kalyani  23/09/2010   22  Chandermukhi   825   850   850 NaN
606  Kalyani  23/09/2010  NaN         Jyoti   640   660   660 NaN
607  Kalyani  24/09/2010   20  Chandermukhi  1000  1050  1030 NaN
608  Kalyani  24/09/2010  NaN         Jyoti   800   850   850 NaN
609  Kalyani  25/09/2010   25  Chandermukhi  1000  1050  1030 NaN
610  Kalyani  25/09/2010  NaN         Jyoti   880   920   900 NaN
611  Kalyani  26/09/2010   25  Chandermukhi  1000  1050  1030 NaN
612  Kalyani  26/09/2010  NaN         Jyoti   880   900   900 NaN
613  Kalyani  27/09/2010   20  Chandermukhi  1030  1050  1050 NaN
614  Kalyani  27/09/2010  NaN         Jyoti   880   900   900 NaN
615  Kalyani  28/09/2010   20  Chandermukhi  1030  1050  1050 NaN
616  Kalyani  28/09/2010  NaN         Jyoti   880   900   900 NaN
617  Kalyani  29/09/2010   20  Chandermukhi   950  1030  1000 NaN
618  Kalyani  29/09/2010  NaN         Jyoti   800   880   850 NaN
619  Kalyani  30/09/2010   25  Chandermukhi   900   950   930 NaN
620  Kalyani  30/09/2010  NaN         Jyoti   700   750   750 NaN
           0           1    2             3    4    5    6   7
657  Kalyani  01/04/2011   30  Chandermukhi  660  680  670 NaN
658  Kalyani  01/04/2011  NaN         Jyoti  460  480  470 NaN
659  Kalyani  02/04/2011   30  Chandermukhi  660  680  670 NaN
660  Kalyani  02/04/2011  NaN         Jyoti  480  500  490 NaN
661  Kalyani  03/04/2011   30  Chandermukhi  670  690  680 NaN
662  Kalyani  03/04/2011  NaN         Jyoti  490  510  500 NaN
663  Kalyani  04/04/2011   30  Chandermukhi  680  700  690 NaN
664  Kalyani  04/04/2011  NaN         Jyoti  500  520  510 NaN
665  Kalyani  05/04/2011   30  Chandermukhi  690  720  710 NaN
666  Kalyani  05/04/2011  NaN         Jyoti  500  520  510 NaN
667  Kalyani  06/04/2011   28  Chandermukhi  730  740  740 NaN
668  Kalyani  06/04/2011  NaN         Jyoti  520  540  530 NaN
669  Kalyani  07/04/2011   28  Chandermukhi  730  740  740 NaN
670  Kalyani  07/04/2011  NaN         Jyoti  530  540  540 NaN
671  Kalyani  08/04/2011   30  Chandermukhi  730  740  740 NaN
672  Kalyani  08/04/2011  NaN         Jyoti  530  540  540 NaN
673  Kalyani  09/04/2011   30  Chandermukhi  730  740  740 NaN
674  Kalyani  09/04/2011  NaN         Jyoti  530  540  540 NaN
675  Kalyani  10/04/2011   30  Chandermukhi  720  730  730 NaN
676  Kalyani  10/04/2011  NaN         Jyoti  520  530  530 NaN
677  Kalyani  11/04/2011   30  Chandermukhi  720  730  730 NaN
678  Kalyani  11/04/2011  NaN         Jyoti  520  530  530 NaN
679  Kalyani  12/04/2011   30  Chandermukhi  720  730  730 NaN
680  Kalyani  12/04/2011  NaN         Jyoti  520  530  530 NaN
681  Kalyani  13/04/2011   30  Chandermukhi  730  750  740 NaN
682  Kalyani  13/04/2011  NaN         Jyoti  530  550  540 NaN
683  Kalyani  14/04/2011   28  Chandermukhi  740  760  750 NaN
684  Kalyani  14/04/2011  NaN         Jyoti  540  560  550 NaN
685  Kalyani  15/04/2011   28  Chandermukhi  750  770  760 NaN
686  Kalyani  15/04/2011  NaN         Jyoti  550  570  560 NaN
687  Kalyani  16/04/2011   28  Chandermukhi  760  780  770 NaN
688  Kalyani  16/04/2011  NaN         Jyoti  560  580  570 NaN
689  Kalyani  17/04/2011   27  Chandermukhi  760  780  770 NaN
690  Kalyani  17/04/2011  NaN         Jyoti  570  580  580 NaN
691  Kalyani  18/04/2011   27  Chandermukhi  760  780  770 NaN
692  Kalyani  18/04/2011  NaN         Jyoti  570  580  580 NaN
693  Kalyani  19/04/2011   27  Chandermukhi  760  780  770 NaN
694  Kalyani  19/04/2011  NaN         Jyoti  570  580  580 NaN
695  Kalyani  20/04/2011   25  Chandermukhi  780  800  790 NaN
696  Kalyani  20/04/2011  NaN         Jyoti  580  600  590 NaN
697  Kalyani  21/04/2011   25  Chandermukhi  790  800  800 NaN
698  Kalyani  21/04/2011  NaN         Jyoti  590  600  600 NaN
699  Kalyani  22/04/2011   25  Chandermukhi  790  800  800 NaN
700  Kalyani  22/04/2011  NaN         Jyoti  590  600  600 NaN
701  Kalyani  23/04/2011   27  Chandermukhi  790  800  800 NaN
702  Kalyani  23/04/2011  NaN         Jyoti  590  600  600 NaN
703  Kalyani  24/04/2011   27  Chandermukhi  790  800  800 NaN
704  Kalyani  24/04/2011  NaN         Jyoti  590  600  600 NaN
705  Kalyani  25/04/2011   25  Chandermukhi  790  800  800 NaN
706  Kalyani  25/04/2011  NaN         Jyoti  590  600  600 NaN
707  Kalyani  26/04/2011   25  Chandermukhi  790  800  800 NaN
708  Kalyani  26/04/2011  NaN         Jyoti  590  600  600 NaN
709  Kalyani  27/04/2011   23  Chandermukhi  780  790  790 NaN
710  Kalyani  27/04/2011  NaN         Jyoti  580  590  590 NaN
711  Kalyani  28/04/2011   23  Chandermukhi  770  780  780 NaN
712  Kalyani  28/04/2011  NaN         Jyoti  570  580  580 NaN
713  Kalyani  29/04/2011   23  Chandermukhi  770  780  780 NaN
714  Kalyani  29/04/2011  NaN         Jyoti  570  580  580 NaN
715  Kalyani  30/04/2011   25  Chandermukhi  770  780  780 NaN
716  Kalyani  30/04/2011  NaN         Jyoti  570  580  580 NaN
           0           1    2             3    4    5    6   7
744  Kalyani  01/08/2011   28  Chandermukhi  800  850  830 NaN
745  Kalyani  01/08/2011  NaN         Jyoti  500  600  550 NaN
746  Kalyani  02/08/2011   28  Chandermukhi  800  850  830 NaN
747  Kalyani  02/08/2011  NaN         Jyoti  500  600  550 NaN
748  Kalyani  03/08/2011   27  Chandermukhi  800  850  830 NaN
749  Kalyani  03/08/2011  NaN         Jyoti  450  550  500 NaN
750  Kalyani  04/08/2011   28  Chandermukhi  800  860  830 NaN
751  Kalyani  04/08/2011  NaN         Jyoti  500  600  550 NaN
752  Kalyani  10/08/2011   30  Chandermukhi  800  860  840 NaN
753  Kalyani  10/08/2011  NaN         Jyoti  550  600  590 NaN
754  Kalyani  11/08/2011   30  Chandermukhi  850  920  900 NaN
755  Kalyani  11/08/2011  NaN         Jyoti  550  650  600 NaN
756  Kalyani  12/08/2011    3  Chandermukhi  880  920  900 NaN
757  Kalyani  12/08/2011  NaN         Jyoti  550  650  600 NaN
758  Kalyani  13/08/2011   30  Chandermukhi  880  920  900 NaN
759  Kalyani  13/08/2011  NaN         Jyoti  550  650  600 NaN
760  Kalyani  14/08/2011   28  Chandermukhi  840  880  860 NaN
761  Kalyani  14/08/2011  NaN         Jyoti  520  560  540 NaN
762  Kalyani  16/08/2011   28  Chandermukhi  830  880  850 NaN
763  Kalyani  16/08/2011  NaN         Jyoti  600  640  620 NaN
764  Kalyani  17/08/2011   28  Chandermukhi  830  880  850 NaN
765  Kalyani  17/08/2011  NaN         Jyoti  600  640  620 NaN
766  Kalyani  18/08/2011   28  Chandermukhi  830  880  850 NaN
767  Kalyani  18/08/2011  NaN         Jyoti  600  640  620 NaN
768  Kalyani  19/08/2011   28  Chandermukhi  850  880  860 NaN
769  Kalyani  19/08/2011  NaN         Jyoti  600  640  640 NaN
770  Kalyani  20/08/2011   28  Chandermukhi  850  880  860 NaN
771  Kalyani  20/08/2011  NaN         Jyoti  600  640  620 NaN
772  Kalyani  21/08/2011   28  Chandermukhi  850  880  860 NaN
773  Kalyani  21/08/2011  NaN         Jyoti  550  600  580 NaN
774  Kalyani  22/08/2011   29  Chandermukhi  850  880  860 NaN
775  Kalyani  22/08/2011  NaN         Jyoti  550  600  580 NaN
776  Kalyani  23/08/2011   28  Chandermukhi  860  960  940 NaN
777  Kalyani  23/08/2011  NaN         Jyoti  550  650  600 NaN
778  Kalyani  24/08/2011   23  Chandermukhi  900  940  920 NaN
779  Kalyani  24/08/2011  NaN         Jyoti  580  620  600 NaN
780  Kalyani  25/08/2011   25  Chandermukhi  900  940  920 NaN
781  Kalyani  25/08/2011  NaN         Jyoti  580  620  600 NaN
782  Kalyani  26/08/2011   20  Chandermukhi  900  940  920 NaN
783  Kalyani  26/08/2011  NaN         Jyoti  580  620  600 NaN
784  Kalyani  27/08/2011   28  Chandermukhi  900  940  920 NaN
785  Kalyani  27/08/2011  NaN         Jyoti  580  620  600 NaN
786  Kalyani  28/08/2011   20  Chandermukhi  900  950  930 NaN
787  Kalyani  28/08/2011  NaN         Jyoti  580  620  600 NaN
788  Kalyani  29/08/2011   20  Chandermukhi  900  950  930 NaN
789  Kalyani  29/08/2011  NaN         Jyoti  580  620  600 NaN
790  Kalyani  30/08/2011   30  Chandermukhi  900  950  930 NaN
791  Kalyani  30/08/2011  NaN         Jyoti  600  650  630 NaN
792  Kalyani  31/08/2011   28  Chandermukhi  900  950  930 NaN
793  Kalyani  31/08/2011  NaN         Jyoti  580  620  600 NaN

           0           1    2             3    4    5    6   7
611  Kalyani  01/12/2011   20  Chandermukhi  700  800  750 NaN
612  Kalyani  01/12/2011  NaN         Jyoti  400  450  430 NaN
613  Kalyani  02/12/2011   20  Chandermukhi  700  800  750 NaN
614  Kalyani  02/12/2011  NaN         Jyoti  400  450  430 NaN
615  Kalyani  03/12/2011   20  Chandermukhi  700  800  750 NaN
616  Kalyani  03/12/2011  NaN         Jyoti  400  450  430 NaN
617  Kalyani  04/12/2011   20  Chandermukhi  700  800  750 NaN
618  Kalyani  04/12/2011  NaN         Jyoti  400  450  430 NaN
619  Kalyani  05/12/2011   20  Chandermukhi  700  800  750 NaN
620  Kalyani  05/12/2011  NaN         Jyoti  400  450  430 NaN
621  Kalyani  10/12/2011   25  Chandermukhi  700  800  750 NaN
622  Kalyani  10/12/2011  NaN         Jyoti  300  340  320 NaN
623  Kalyani  11/12/2011   25  Chandermukhi  700  800  750 NaN
624  Kalyani  11/12/2011  NaN         Jyoti  300  340  320 NaN
625  Kalyani  12/12/2011   22  Chandermukhi  700  800  750 NaN
626  Kalyani  12/12/2011  NaN         Jyoti  300  340  320 NaN
627  Kalyani  14/12/2011   25  Chandermukhi  700  800  750 NaN
628  Kalyani  14/12/2011  NaN         Jyoti  300  340  320 NaN
629  Kalyani  15/12/2011   25  Chandermukhi  700  800  750 NaN
630  Kalyani  15/12/2011  NaN         Jyoti  300  340  320 NaN
631  Kalyani  16/12/2011   25  Chandermukhi  700  800  750 NaN
632  Kalyani  16/12/2011  NaN         Jyoti  300  340  320 NaN
633  Kalyani  17/12/2011   10  Chandermukhi  820  860  840 NaN
634  Kalyani  17/12/2011  NaN         Jyoti  240  280  260 NaN
635  Kalyani  19/12/2011   10  Chandermukhi  820  860  840 NaN
636  Kalyani  19/12/2011  NaN         Jyoti  240  280  260 NaN
637  Kalyani  20/12/2011   10  Chandermukhi  820  860  840 NaN
638  Kalyani  20/12/2011  NaN         Jyoti  240  280  260 NaN
639  Kalyani  21/12/2011   10  Chandermukhi  820  860  840 NaN
640  Kalyani  21/12/2011  NaN         Jyoti  280  300  280 NaN
641  Kalyani  22/12/2011   10  Chandermukhi  820  860  840 NaN
642  Kalyani  22/12/2011  NaN         Jyoti  280  300  280 NaN
643  Kalyani  23/12/2011   10  Chandermukhi  820  860  840 NaN
644  Kalyani  23/12/2011  NaN         Jyoti  280  300  280 NaN
645  Kalyani  24/12/2011   10  Chandermukhi  820  860  840 NaN
646  Kalyani  24/12/2011  NaN         Jyoti  280  300  280 NaN
647  Kalyani  25/12/2011   10  Chandermukhi  800  840  820 NaN
648  Kalyani  25/12/2011  NaN         Jyoti  280  300  280 NaN
649  Kalyani  26/12/2011   10  Chandermukhi  800  840  820 NaN
650  Kalyani  26/12/2011  NaN         Jyoti  280  300  280 NaN
651  Kalyani  27/12/2011   10  Chandermukhi  780  840  800 NaN
652  Kalyani  27/12/2011  NaN         Jyoti  300  340  320 NaN
653  Kalyani  28/12/2011   10  Chandermukhi  780  840  800 NaN
654  Kalyani  28/12/2011  NaN         Jyoti  300  340  320 NaN
655  Kalyani  30/12/2011   10  Chandermukhi  800  850  830 NaN
656  Kalyani  30/12/2011  NaN         Jyoti  300  340  320 NaN
657  Kalyani  31/12/2011   10  Chandermukhi  800  850  830 NaN
658  Kalyani  31/12/2011  NaN         Jyoti  300  340  320 NaN
           0           1    2             3    4    5    6   7
610  Kalyani  01/02/2011   25         Jyoti  410  430  420 NaN
611  Kalyani  02/02/2011   25         Jyoti  410  430  420 NaN
612  Kalyani  03/02/2011   25         Jyoti  410  430  420 NaN
613  Kalyani  04/02/2011   25         Jyoti  410  430  420 NaN
614  Kalyani  05/02/2011   25         Jyoti  300  310  310 NaN
615  Kalyani  06/02/2011   25         Jyoti  330  350  340 NaN
616  Kalyani  07/02/2011   25         Jyoti  360  380  370 NaN
617  Kalyani  08/02/2011   25         Jyoti  360  380  370 NaN
618  Kalyani  09/02/2011   35  Chandermukhi  550  560  560 NaN
619  Kalyani  09/02/2011  NaN         Jyoti  350  370  360 NaN
620  Kalyani  10/02/2011   35  Chandermukhi  550  560  560 NaN
621  Kalyani  10/02/2011  NaN         Jyoti  350  370  360 NaN
622  Kalyani  11/02/2011   30  Chandermukhi  550  560  560 NaN
623  Kalyani  11/02/2011  NaN         Jyoti  350  370  360 NaN
624  Kalyani  12/02/2011   30  Chandermukhi  550  560  560 NaN
625  Kalyani  12/02/2011  NaN         Jyoti  350  370  360 NaN
626  Kalyani  13/02/2011   30  Chandermukhi  540  560  550 NaN
627  Kalyani  13/02/2011  NaN         Jyoti  340  360  350 NaN
628  Kalyani  14/02/2011   30  Chandermukhi  530  550  540 NaN
629  Kalyani  14/02/2011  NaN         Jyoti  340  360  350 NaN
630  Kalyani  15/02/2011   30  Chandermukhi  520  540  530 NaN
631  Kalyani  15/02/2011  NaN         Jyoti  340  360  350 NaN
632  Kalyani  16/02/2011   30  Chandermukhi  500  520  510 NaN
633  Kalyani  16/02/2011  NaN         Jyoti  340  350  340 NaN
634  Kalyani  17/02/2011   30  Chandermukhi  500  510  500 NaN
635  Kalyani  17/02/2011  NaN         Jyoti  340  350  340 NaN
636  Kalyani  23/02/2011   30  Chandermukhi  540  550  550 NaN
637  Kalyani  23/02/2011  NaN         Jyoti  480  500  490 NaN
638  Kalyani  24/02/2011   30  Chandermukhi  550  560  560 NaN
639  Kalyani  24/02/2011  NaN         Jyoti  480  520  500 NaN
640  Kalyani  25/02/2011   30  Chandermukhi  560  570  570 NaN
641  Kalyani  25/02/2011  NaN         Jyoti  490  510  500 NaN
642  Kalyani  26/02/2011   30  Chandermukhi  570  590  580 NaN
643  Kalyani  26/02/2011  NaN         Jyoti  480  500  490 NaN
644  Kalyani  27/02/2011   32  Chandermukhi  590  610  600 NaN
645  Kalyani  27/02/2011  NaN         Jyoti  470  480  480 NaN
646  Kalyani  28/02/2011   32  Chandermukhi  600  620  610 NaN
647  Kalyani  28/02/2011  NaN         Jyoti  470  480  480 NaN
           0           1    2             3    4    5    6   7
692  Kalyani  01/01/2011   40  Chandermukhi  850  950  900 NaN
693  Kalyani  01/01/2011  NaN         Jyoti  640  680  660 NaN
694  Kalyani  02/01/2011   50  Chandermukhi  850  950  900 NaN
695  Kalyani  02/01/2011  NaN         Jyoti  640  680  660 NaN
696  Kalyani  03/01/2011   50  Chandermukhi  850  950  900 NaN
697  Kalyani  03/01/2011  NaN         Jyoti  640  680  660 NaN
698  Kalyani  04/01/2011   40  Chandermukhi  850  950  900 NaN
699  Kalyani  04/01/2011  NaN         Jyoti  640  680  660 NaN
700  Kalyani  20/01/2011   20         Jyoti  400  450  430 NaN
701  Kalyani  21/01/2011   20         Jyoti  400  450  430 NaN
702  Kalyani  22/01/2011   20         Jyoti  400  450  430 NaN
703  Kalyani  23/01/2011   20         Jyoti  420  460  440 NaN
704  Kalyani  24/01/2011   20         Jyoti  420  460  440 NaN
705  Kalyani  25/01/2011   20         Jyoti  420  460  440 NaN
           0           1   2      3    4    5    6   7
783  Kalyani  01/07/2011  28  Jyoti  630  650  650 NaN
784  Kalyani  02/07/2011  28  Jyoti  630  650  650 NaN
785  Kalyani  03/07/2011  27  Jyoti  620  640  640 NaN
786  Kalyani  04/07/2011  27  Jyoti  620  640  640 NaN
787  Kalyani  05/07/2011  28  Jyoti  600  650  620 NaN
788  Kalyani  06/07/2011  28  Jyoti  600  640  620 NaN
789  Kalyani  07/07/2011  28  Jyoti  620  640  640 NaN
790  Kalyani  08/07/2011  27  Jyoti  620  640  620 NaN
791  Kalyani  09/07/2011  28  Jyoti  600  640  620 NaN
792  Kalyani  10/07/2011  28  Jyoti  600  640  620 NaN
793  Kalyani  11/07/2011  28  Jyoti  600  640  620 NaN
794  Kalyani  12/07/2011  29  Jyoti  600  640  620 NaN
795  Kalyani  13/07/2011  29  Jyoti  600  640  620 NaN
796  Kalyani  14/07/2011  28  Jyoti  600  640  620 NaN
797  Kalyani  15/07/2011  28  Jyoti  600  640  620 NaN
798  Kalyani  16/07/2011  28  Jyoti  600  640  620 NaN
799  Kalyani  17/07/2011  28  Jyoti  600  640  620 NaN
800  Kalyani  18/07/2011  28  Jyoti  600  640  620 NaN
801  Kalyani  19/07/2011  28  Jyoti  600  640  620 NaN
802  Kalyani  20/07/2011  28  Jyoti  600  640  620 NaN
803  Kalyani  21/07/2011  28  Jyoti  600  640  640 NaN
804  Kalyani  22/07/2011  29  Jyoti  550  600  580 NaN
805  Kalyani  23/07/2011  29  Jyoti  550  600  580 NaN
806  Kalyani  24/07/2011  30  Jyoti  550  600  580 NaN
807  Kalyani  25/07/2011  30  Jyoti  550  600  580 NaN
808  Kalyani  26/07/2011  30  Jyoti  550  600  580 NaN
809  Kalyani  27/07/2011  28  Jyoti  550  600  580 NaN
810  Kalyani  28/07/2011  28  Jyoti  550  600  580 NaN
811  Kalyani  29/07/2011  28  Jyoti  500  600  550 NaN
812  Kalyani  30/07/2011  28  Jyoti  500  600  550 NaN
813  Kalyani  31/07/2011  27  Jyoti  500  600  550 NaN

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2             3    4    5    6   7
724  Kalyani  01/03/2011   32  Chandermukhi  620  630  630 NaN
725  Kalyani  01/03/2011  NaN         Jyoti  470  480  480 NaN
726  Kalyani  02/03/2011   32  Chandermukhi  630  640  640 NaN
727  Kalyani  02/03/2011  NaN         Jyoti  470  480  480 NaN
728  Kalyani  03/03/2011   32  Chandermukhi  630  640  640 NaN
729  Kalyani  03/03/2011  NaN         Jyoti  450  460  460 NaN
730  Kalyani  04/03/2011   30  Chandermukhi  630  640  640 NaN
731  Kalyani  04/03/2011  NaN         Jyoti  480  510  500 NaN
732  Kalyani  05/03/2011   32  Chandermukhi  630  640  640 NaN
733  Kalyani  05/03/2011  NaN         Jyoti  480  510  500 NaN
734  Kalyani  06/03/2011   32  Chandermukhi  630  640  640 NaN
735  Kalyani  06/03/2011  NaN         Jyoti  500  520  510 NaN
736  Kalyani  07/03/2011   30  Chandermukhi  630  640  640 NaN
737  Kalyani  07/03/2011  NaN         Jyoti  520  540  530 NaN
738  Kalyani  08/03/2011   30  Chandermukhi  630  640  640 NaN
739  Kalyani  08/03/2011  NaN         Jyoti  530  540  540 NaN
740  Kalyani  09/03/2011   30  Chandermukhi  630  640  640 NaN
741  Kalyani  09/03/2011  NaN         Jyoti  530  540  540 NaN
742  Kalyani  10/03/2011   30  Chandermukhi  630  640  640 NaN
743  Kalyani  10/03/2011  NaN         Jyoti  530  540  540 NaN
744  Kalyani  11/03/2011   30  Chandermukhi  640  680  660 NaN
745  Kalyani  11/03/2011  NaN         Jyoti  520  540  530 NaN
746  Kalyani  12/03/2011   32  Chandermukhi  660  690  680 NaN
747  Kalyani  12/03/2011  NaN         Jyoti  520  540  530 NaN
748  Kalyani  13/03/2011   32  Chandermukhi  680  700  690 NaN
749  Kalyani  13/03/2011  NaN         Jyoti  530  550  540 NaN
750  Kalyani  14/03/2011   30  Chandermukhi  690  720  710 NaN
751  Kalyani  14/03/2011  NaN         Jyoti  530  540  540 NaN
752  Kalyani  15/03/2011   30  Chandermukhi  700  720  710 NaN
753  Kalyani  15/03/2011  NaN         Jyoti  530  550  540 NaN
..       ...         ...  ...           ...  ...  ...  ...  ..
756  Kalyani  17/03/2011   32  Chandermukhi  680  700  690 NaN
757  Kalyani  17/03/2011  NaN         Jyoti  500  520  510 NaN
758  Kalyani  18/03/2011   32  Chandermukhi  670  700  680 NaN
759  Kalyani  18/03/2011  NaN         Jyoti  480  500  490 NaN
760  Kalyani  19/03/2011   32  Chandermukhi  670  700  680 NaN
761  Kalyani  19/03/2011  NaN         Jyoti  460  480  470 NaN
762  Kalyani  20/03/2011   32  Chandermukhi  670  700  680 NaN
763  Kalyani  20/03/2011  NaN         Jyoti  450  470  460 NaN
764  Kalyani  21/03/2011   32  Chandermukhi  670  700  680 NaN
765  Kalyani  21/03/2011  NaN         Jyoti  440  460  450 NaN
766  Kalyani  22/03/2011   32  Chandermukhi  670  700  680 NaN
767  Kalyani  22/03/2011  NaN         Jyoti  440  460  450 NaN
768  Kalyani  23/03/2011   30  Chandermukhi  650  670  660 NaN
769  Kalyani  23/03/2011  NaN         Jyoti  440  460  450 NaN
770  Kalyani  24/03/2011   32  Chandermukhi  640  660  650 NaN
771  Kalyani  24/03/2011  NaN         Jyoti  440  460  450 NaN
772  Kalyani  25/03/2011   30  Chandermukhi  640  660  650 NaN
773  Kalyani  25/03/2011  NaN         Jyoti  440  460  450 NaN
774  Kalyani  26/03/2011   30  Chandermukhi  640  660  650 NaN
775  Kalyani  26/03/2011  NaN         Jyoti  440  460  450 NaN
776  Kalyani  27/03/2011   32  Chandermukhi  640  660  650 NaN
777  Kalyani  27/03/2011  NaN         Jyoti  440  460  450 NaN
778  Kalyani  28/03/2011   30  Chandermukhi  640  660  650 NaN
779  Kalyani  28/03/2011  NaN         Jyoti  440  460  450 NaN
780  Kalyani  29/03/2011   30  Chandermukhi  640  660  650 NaN
781  Kalyani  29/03/2011  NaN         Jyoti  440  460  450 NaN
782  Kalyani  30/03/2011   32  Chandermukhi  650  670  660 NaN
783  Kalyani  30/03/2011  NaN         Jyoti  440  460  450 NaN
784  Kalyani  31/03/2011   32  Chandermukhi  660  680  670 NaN
785  Kalyani  31/03/2011  NaN         Jyoti  450  470  460 NaN

[62 rows x 8 columns]
           0           1    2             3    4    5    6   7
731  Kalyani  01/05/2011   25         Jyoti  590  600  600 NaN
732  Kalyani  02/05/2011   25         Jyoti  590  600  600 NaN
733  Kalyani  03/05/2011   20         Jyoti  600  620  610 NaN
734  Kalyani  04/05/2011   18         Jyoti  620  640  630 NaN
735  Kalyani  05/05/2011   17         Jyoti  650  670  660 NaN
736  Kalyani  06/05/2011   18  Chandermukhi  840  880  860 NaN
737  Kalyani  06/05/2011  NaN         Jyoti  650  670  660 NaN
738  Kalyani  07/05/2011   20  Chandermukhi  840  880  860 NaN
739  Kalyani  07/05/2011  NaN         Jyoti  650  670  660 NaN
740  Kalyani  08/05/2011   20  Chandermukhi  850  880  870 NaN
741  Kalyani  08/05/2011  NaN         Jyoti  650  670  660 NaN
742  Kalyani  09/05/2011   18  Chandermukhi  850  880  870 NaN
743  Kalyani  09/05/2011  NaN         Jyoti  660  680  670 NaN
744  Kalyani  10/05/2011   18  Chandermukhi  850  880  870 NaN
745  Kalyani  10/05/2011  NaN         Jyoti  660  680  670 NaN
746  Kalyani  11/05/2011  1.8  Chandermukhi  850  880  870 NaN
747  Kalyani  11/05/2011  NaN         Jyoti  660  680  670 NaN
748  Kalyani  12/05/2011   18  Chandermukhi  850  880  870 NaN
749  Kalyani  12/05/2011  NaN         Jyoti  660  680  670 NaN
750  Kalyani  13/05/2011   18  Chandermukhi  880  900  890 NaN
751  Kalyani  13/05/2011  NaN         Jyoti  690  700  700 NaN
752  Kalyani  14/05/2011   16  Chandermukhi  890  900  900 NaN
753  Kalyani  14/05/2011  NaN         Jyoti  700  710  700 NaN
754  Kalyani  15/05/2011   16  Chandermukhi  900  910  910 NaN
755  Kalyani  15/05/2011  NaN         Jyoti  700  720  710 NaN
756  Kalyani  16/05/2011   16  Chandermukhi  910  920  920 NaN
757  Kalyani  16/05/2011  NaN         Jyoti  710  720  710 NaN
758  Kalyani  17/05/2011   18  Chandermukhi  910  920  920 NaN
759  Kalyani  17/05/2011  NaN         Jyoti  710  730  720 NaN
760  Kalyani  18/05/2011   18  Chandermukhi  900  910  900 NaN
761  Kalyani  18/05/2011  NaN         Jyoti  700  720  710 NaN
762  Kalyani  19/05/2011   18  Chandermukhi  880  900  890 NaN
763  Kalyani  19/05/2011  NaN         Jyoti  690  700  700 NaN
764  Kalyani  20/05/2011   18  Chandermukhi  870  880  880 NaN
765  Kalyani  20/05/2011  NaN         Jyoti  700  710  710 NaN
766  Kalyani  21/05/2011   16  Chandermukhi  880  890  890 NaN
767  Kalyani  21/05/2011  NaN         Jyoti  700  710  710 NaN
768  Kalyani  22/05/2011   16  Chandermukhi  880  890  890 NaN
769  Kalyani  22/05/2011  NaN         Jyoti  710  720  720 NaN
770  Kalyani  23/05/2011   16  Chandermukhi  890  900  900 NaN
771  Kalyani  23/05/2011  NaN         Jyoti  710  720  720 NaN
772  Kalyani  24/05/2011   16  Chandermukhi  890  900  900 NaN
773  Kalyani  24/05/2011  NaN         Jyoti  710  720  720 NaN
774  Kalyani  25/05/2011   16  Chandermukhi  890  900  900 NaN
775  Kalyani  25/05/2011  NaN         Jyoti  710  720  720 NaN
776  Kalyani  26/05/2011   16  Chandermukhi  890  900  900 NaN
777  Kalyani  26/05/2011  NaN         Jyoti  710  720  720 NaN
           0           1    2             3    4    5    6   7
732  Kalyani  01/11/2011   20  Chandermukhi  660  700  680 NaN
733  Kalyani  01/11/2011  NaN         Jyoti  420  460  440 NaN
734  Kalyani  02/11/2011   20  Chandermukhi  660  700  680 NaN
735  Kalyani  02/11/2011  NaN         Jyoti  420  460  440 NaN
736  Kalyani  03/11/2011   20  Chandermukhi  660  700  680 NaN
737  Kalyani  03/11/2011  NaN         Jyoti  420  460  440 NaN
738  Kalyani  04/11/2011   20  Chandermukhi  660  700  680 NaN
739  Kalyani  04/11/2011  NaN         Jyoti  420  460  440 NaN
740  Kalyani  05/11/2011   20  Chandermukhi  660  700  680 NaN
741  Kalyani  05/11/2011  NaN         Jyoti  420  460  440 NaN
742  Kalyani  06/11/2011   20  Chandermukhi  660  700  680 NaN
743  Kalyani  06/11/2011  NaN         Jyoti  420  460  440 NaN
744  Kalyani  07/11/2011   20  Chandermukhi  600  680  660 NaN
745  Kalyani  07/11/2011  NaN         Jyoti  400  440  420 NaN
746  Kalyani  08/11/2011   20  Chandermukhi  600  650  630 NaN
747  Kalyani  08/11/2011  NaN         Jyoti  400  450  430 NaN
748  Kalyani  09/11/2011   20  Chandermukhi  600  680  660 NaN
749  Kalyani  09/11/2011  NaN         Jyoti  400  440  420 NaN
750  Kalyani  10/11/2011   20  Chandermukhi  600  680  660 NaN
751  Kalyani  10/11/2011  NaN         Jyoti  400  440  420 NaN
752  Kalyani  11/11/2011   20  Chandermukhi  600  660  640 NaN
753  Kalyani  11/11/2011  NaN         Jyoti  380  420  400 NaN
754  Kalyani  12/11/2011   20  Chandermukhi  580  640  620 NaN
755  Kalyani  12/11/2011  NaN         Jyoti  380  420  400 NaN
756  Kalyani  13/11/2011   20  Chandermukhi  560  620  580 NaN
757  Kalyani  13/11/2011  NaN         Jyoti  370  410  390 NaN
758  Kalyani  14/11/2011   20  Chandermukhi  560  600  580 NaN
759  Kalyani  14/11/2011  NaN         Jyoti  370  400  380 NaN
760  Kalyani  15/11/2011   20  Chandermukhi  560  620  580 NaN
761  Kalyani  15/11/2011  NaN         Jyoti  360  400  380 NaN
762  Kalyani  16/11/2011   20  Chandermukhi  560  620  580 NaN
763  Kalyani  16/11/2011  NaN         Jyoti  360  400  380 NaN
764  Kalyani  17/11/2011   20  Chandermukhi  560  620  580 NaN
765  Kalyani  17/11/2011  NaN         Jyoti  360  400  380 NaN
766  Kalyani  18/11/2011   20  Chandermukhi  560  600  580 NaN
767  Kalyani  18/11/2011  NaN         Jyoti  360  400  380 NaN
768  Kalyani  19/11/2011   20  Chandermukhi  380  420  400 NaN
769  Kalyani  19/11/2011  NaN         Jyoti  550  650  600 NaN
770  Kalyani  20/11/2011   20  Chandermukhi  400  450  430 NaN
771  Kalyani  20/11/2011  NaN         Jyoti  700  800  750 NaN
772  Kalyani  21/11/2011   20  Chandermukhi  400  450  430 NaN
773  Kalyani  21/11/2011  NaN         Jyoti  700  800  750 NaN
774  Kalyani  22/11/2011   20  Chandermukhi  650  720  680 NaN
775  Kalyani  22/11/2011  NaN         Jyoti  400  450  430 NaN
776  Kalyani  24/11/2011   20  Chandermukhi  700  800  750 NaN
777  Kalyani  24/11/2011  NaN         Jyoti  420  460  440 NaN
778  Kalyani  26/11/2011   20  Chandermukhi  700  800  750 NaN
779  Kalyani  26/11/2011  NaN         Jyoti  420  460  440 NaN
780  Kalyani  27/11/2011   20  Chandermukhi  700  800  750 NaN
781  Kalyani  27/11/2011  NaN         Jyoti  400  450  430 NaN
782  Kalyani  28/11/2011   20  Chandermukhi  700  800  750 NaN
783  Kalyani  28/11/2011  NaN         Jyoti  400  450  430 NaN
784  Kalyani  29/11/2011   20  Chandermukhi  700  800  750 NaN
785  Kalyani  29/11/2011  NaN         Jyoti  400  450  430 NaN
786  Kalyani  30/11/2011   20  Chandermukhi  700  800  750 NaN
787  Kalyani  30/11/2011  NaN         Jyoti  400  450  430 NaN

           0           1    2             3    4     5    6   7
606  Kalyani  01/10/2011   15  Chandermukhi  800   900  850 NaN
607  Kalyani  01/10/2011  NaN         Jyoti  550   650  600 NaN
608  Kalyani  02/10/2011   15  Chandermukhi  900   920  900 NaN
609  Kalyani  02/10/2011  NaN         Jyoti  600   620  600 NaN
610  Kalyani  03/10/2011   15  Chandermukhi  900   920  900 NaN
611  Kalyani  03/10/2011  NaN         Jyoti  600   620  600 NaN
612  Kalyani  05/10/2011   15  Chandermukhi  940   980  960 NaN
613  Kalyani  05/10/2011  NaN         Jyoti  600   640  620 NaN
614  Kalyani  06/10/2011   15  Chandermukhi  960  1000  980 NaN
615  Kalyani  06/10/2011  NaN         Jyoti  640   680  660 NaN
616  Kalyani  07/10/2011   15  Chandermukhi  960  1000  980 NaN
617  Kalyani  07/10/2011  NaN         Jyoti  640   680  660 NaN
618  Kalyani  08/10/2011   15  Chandermukhi  960  1000  980 NaN
619  Kalyani  08/10/2011  NaN         Jyoti  660   700  680 NaN
620  Kalyani  09/10/2011   15  Chandermukhi  960  1000  980 NaN
621  Kalyani  09/10/2011  NaN         Jyoti  650   750  700 NaN
622  Kalyani  10/10/2011   15  Chandermukhi  870   970  900 NaN
623  Kalyani  10/10/2011  NaN         Jyoti  600   680  650 NaN
624  Kalyani  11/10/2011   15  Chandermukhi  900   960  930 NaN
625  Kalyani  11/10/2011  NaN         Jyoti  600   680  650 NaN
626  Kalyani  12/10/2011   15  Chandermukhi  900   940  920 NaN
627  Kalyani  12/10/2011  NaN         Jyoti  600   660  640 NaN
628  Kalyani  13/10/2011   15  Chandermukhi  900   940  920 NaN
629  Kalyani  13/10/2011  NaN         Jyoti  620   660  640 NaN
630  Kalyani  14/10/2011   15  Chandermukhi  900   940  920 NaN
631  Kalyani  14/10/2011  NaN         Jyoti  620   660  640 NaN
632  Kalyani  15/10/2011   15  Chandermukhi  900   940  920 NaN
633  Kalyani  15/10/2011  NaN         Jyoti  620   660  640 NaN
634  Kalyani  16/10/2011   15  Chandermukhi  900   920  910 NaN
635  Kalyani  16/10/2011  NaN         Jyoti  550   600  580 NaN
636  Kalyani  17/10/2011   15  Chandermukhi  850   900  880 NaN
637  Kalyani  17/10/2011  NaN         Jyoti  550   600  580 NaN
638  Kalyani  18/10/2011   20  Chandermukhi  750   780  760 NaN
639  Kalyani  18/10/2011  NaN         Jyoti  500   550  530 NaN
640  Kalyani  19/10/2011    2  Chandermukhi  720   760  740 NaN
641  Kalyani  19/10/2011  NaN         Jyoti  480   520  500 NaN
642  Kalyani  20/10/2011   20  Chandermukhi  680   720  700 NaN
643  Kalyani  20/10/2011  NaN         Jyoti  430   480  450 NaN
644  Kalyani  21/10/2011   20  Chandermukhi  680   720  700 NaN
645  Kalyani  21/10/2011  NaN         Jyoti  420   470  450 NaN
646  Kalyani  22/10/2011   20  Chandermukhi  650   700  680 NaN
647  Kalyani  22/10/2011  NaN         Jyoti  400   440  420 NaN
648  Kalyani  23/10/2011   20  Chandermukhi  680   720  700 NaN
649  Kalyani  23/10/2011  NaN         Jyoti  420   460  440 NaN
650  Kalyani  24/10/2011   20  Chandermukhi  680   720  700 NaN
651  Kalyani  24/10/2011  NaN         Jyoti  420   460  440 NaN
652  Kalyani  25/10/2011   20  Chandermukhi  700   740  720 NaN
653  Kalyani  25/10/2011  NaN         Jyoti  450   480  460 NaN
654  Kalyani  26/10/2011   20  Chandermukhi  700   740  720 NaN
655  Kalyani  26/10/2011  NaN         Jyoti  450   480  460 NaN
656  Kalyani  27/10/2011   20  Chandermukhi  700   740  720 NaN
657  Kalyani  27/10/2011  NaN         Jyoti  430   450  430 NaN
658  Kalyani  28/10/2011   20  Chandermukhi  700   740  720 NaN
659  Kalyani  28/10/2011  NaN         Jyoti  430   450  430 NaN
660  Kalyani  29/10/2011   20  Chandermukhi  700   740  720 NaN
661  Kalyani  29/10/2011  NaN         Jyoti  430   450  430 NaN
662  Kalyani  30/10/2011   20  Chandermukhi  660   700  680 NaN
663  Kalyani  30/10/2011  NaN         Jyoti  420   460  440 NaN
664  Kalyani  31/10/2011   20  Chandermukhi  660   700  680 NaN
665  Kalyani  31/10/2011  NaN         Jyoti  420   460  440 NaN
           0           1     2             3    4    5    6   7
759  Kalyani  01/09/2011    30  Chandermukhi  900  950  920 NaN
760  Kalyani  01/09/2011   NaN         Jyoti  600  650  630 NaN
761  Kalyani  02/09/2011    30  Chandermukhi  900  950  920 NaN
762  Kalyani  02/09/2011   NaN         Jyoti  550  600  580 NaN
763  Kalyani  03/09/2011    20  Chandermukhi  800  900  850 NaN
764  Kalyani  03/09/2011   NaN         Jyoti  550  650  600 NaN
765  Kalyani  04/09/2011    20  Chandermukhi  850  900  880 NaN
766  Kalyani  04/09/2011   NaN         Jyoti  600  620  610 NaN
767  Kalyani  05/09/2011    20  Chandermukhi  800  900  850 NaN
768  Kalyani  05/09/2011   NaN         Jyoti  600  630  610 NaN
769  Kalyani  06/09/2011    22  Chandermukhi  850  900  880 NaN
770  Kalyani  06/09/2011   NaN         Jyoti  600  620  610 NaN
771  Kalyani  07/09/2011    22  Chandermukhi  850  900  880 NaN
772  Kalyani  07/09/2011   NaN         Jyoti  600  620  610 NaN
773  Kalyani  08/09/2011    22  Chandermukhi  820  880  860 NaN
774  Kalyani  08/09/2011   NaN         Jyoti  580  600  600 NaN
775  Kalyani  09/09/2011    22  Chandermukhi  800  900  850 NaN
776  Kalyani  09/09/2011   NaN         Jyoti  580  600  600 NaN
777  Kalyani  10/09/2011    22  Chandermukhi  820  880  860 NaN
778  Kalyani  10/09/2011   NaN         Jyoti  580  600  600 NaN
779  Kalyani  11/09/2011    22  Chandermukhi  850  900  870 NaN
780  Kalyani  11/09/2011   NaN         Jyoti  600  630  610 NaN
781  Kalyani  12/09/2011    22         Jyoti  580  600  600 NaN
782  Kalyani  14/09/2011  22.5  Chandermukhi  820  880  860 NaN
783  Kalyani  14/09/2011   NaN         Jyoti  590  630  600 NaN
784  Kalyani  15/09/2011    20  Chandermukhi  850  950  900 NaN
785  Kalyani  15/09/2011   NaN         Jyoti  600  650  620 NaN
786  Kalyani  16/09/2011    20  Chandermukhi  850  950  900 NaN
787  Kalyani  16/09/2011   NaN         Jyoti  600  650  620 NaN
788  Kalyani  17/09/2011    20  Chandermukhi  700  800  750 NaN
789  Kalyani  17/09/2011   NaN         Jyoti  500  600  550 NaN
790  Kalyani  18/09/2011    20  Chandermukhi  700  800  750 NaN
791  Kalyani  18/09/2011   NaN         Jyoti  500  600  550 NaN
792  Kalyani  19/09/2011    20  Chandermukhi  700  800  750 NaN
793  Kalyani  19/09/2011   NaN         Jyoti  500  600  550 NaN
794  Kalyani  20/09/2011    20  Chandermukhi  820  860  840 NaN
795  Kalyani  20/09/2011   NaN         Jyoti  500  600  550 NaN
796  Kalyani  21/09/2011    20  Chandermukhi  740  840  800 NaN
797  Kalyani  21/09/2011   NaN         Jyoti  500  600  550 NaN
798  Kalyani  22/09/2011    22  Chandermukhi  740  840  800 NaN
799  Kalyani  22/09/2011   NaN         Jyoti  500  600  550 NaN
800  Kalyani  23/09/2011    20  Chandermukhi  750  850  800 NaN
801  Kalyani  23/09/2011   NaN         Jyoti  500  600  550 NaN
802  Kalyani  24/09/2011    20  Chandermukhi  750  850  800 NaN
803  Kalyani  24/09/2011   NaN         Jyoti  500  600  550 NaN
804  Kalyani  25/09/2011    20  Chandermukhi  750  850  800 NaN
805  Kalyani  25/09/2011   NaN         Jyoti  550  650  600 NaN
806  Kalyani  26/09/2011    20  Chandermukhi  800  900  850 NaN
807  Kalyani  26/09/2011   NaN         Jyoti  500  600  550 NaN
808  Kalyani  27/09/2011    20  Chandermukhi  800  900  850 NaN
809  Kalyani  27/09/2011   NaN         Jyoti  500  600  550 NaN
810  Kalyani  28/09/2011    20  Chandermukhi  800  900  850 NaN
811  Kalyani  28/09/2011   NaN         Jyoti  550  650  600 NaN
812  Kalyani  29/09/2011    25  Chandermukhi  800  900  850 NaN
813  Kalyani  29/09/2011   NaN         Jyoti  550  650  600 NaN
814  Kalyani  30/09/2011    25  Chandermukhi  800  900  850 NaN
815  Kalyani  30/09/2011   NaN         Jyoti  550  650  600 NaN
           0           1    2             3     4     5     6   7
840  Kalyani  01/04/2012    6  Chandermukhi  1150  1200  1180 NaN
841  Kalyani  01/04/2012  NaN         Jyoti  1000  1060  1040 NaN
842  Kalyani  02/04/2012    6  Chandermukhi  1150  1200  1180 NaN
843  Kalyani  02/04/2012  NaN         Jyoti  1000  1080  1060 NaN
844  Kalyani  03/04/2012    6  Chandermukhi  1150  1200  1180 NaN
845  Kalyani  03/04/2012  NaN         Jyoti  1000  1080  1060 NaN
846  Kalyani  04/04/2012    6  Chandermukhi  1150  1200  1180 NaN
847  Kalyani  04/04/2012  NaN         Jyoti  1000  1080  1060 NaN
848  Kalyani  05/04/2012    6  Chandermukhi  1150  1200  1180 NaN
849  Kalyani  05/04/2012  NaN         Jyoti  1000  1080  1060 NaN
850  Kalyani  06/04/2012    5  Chandermukhi  1180  1250  1200 NaN
851  Kalyani  06/04/2012  NaN         Jyoti  1000  1100  1070 NaN
852  Kalyani  09/04/2012    5  Chandermukhi  1160  1200  1180 NaN
853  Kalyani  09/04/2012  NaN         Jyoti  1000  1040  1020 NaN
854  Kalyani  10/04/2012    6  Chandermukhi  1160  1200  1180 NaN
855  Kalyani  10/04/2012  NaN         Jyoti  1000  1040  1020 NaN
856  Kalyani  11/04/2012    6         Jyoti   900  1020  1000 NaN
857  Kalyani  12/04/2012    5  Chandermukhi  1140  1180  1160 NaN
858  Kalyani  12/04/2012  NaN         Jyoti   900  1020  1000 NaN
859  Kalyani  13/04/2012    5  Chandermukhi  1100  1150  1130 NaN
860  Kalyani  13/04/2012  NaN         Jyoti   960  1000   980 NaN
861  Kalyani  14/04/2012  5.5  Chandermukhi  1100  1150  1130 NaN
862  Kalyani  14/04/2012  NaN         Jyoti   960  1000   980 NaN
863  Kalyani  15/04/2012    6  Chandermukhi  1100  1150  1130 NaN
864  Kalyani  15/04/2012  NaN         Jyoti  1000  1060  1040 NaN
865  Kalyani  16/04/2012  5.5  Chandermukhi  1140  1180  1160 NaN
866  Kalyani  16/04/2012  NaN         Jyoti  1040  1080  1060 NaN
867  Kalyani  17/04/2012    6  Chandermukhi  1160  1200  1180 NaN
868  Kalyani  17/04/2012  NaN         Jyoti  1050  1100  1080 NaN
869  Kalyani  18/04/2012    5  Chandermukhi  1180  1220  1200 NaN
870  Kalyani  18/04/2012  NaN         Jyoti   980  1020  1000 NaN
871  Kalyani  19/04/2012    6  Chandermukhi  1180  1220  1200 NaN
872  Kalyani  19/04/2012  NaN         Jyoti   980  1020  1000 NaN
873  Kalyani  20/04/2012    6  Chandermukhi  1180  1220  1200 NaN
874  Kalyani  20/04/2012  NaN         Jyoti   980  1020  1000 NaN
875  Kalyani  21/04/2012    6  Chandermukhi  1180  1220  1200 NaN
876  Kalyani  21/04/2012  NaN         Jyoti   980  1020  1000 NaN
877  Kalyani  23/04/2012    6  Chandermukhi  1150  1200  1180 NaN
878  Kalyani  23/04/2012  NaN         Jyoti   960  1000   980 NaN
879  Kalyani  24/04/2012   10  Chandermukhi  1180  1220  1200 NaN
880  Kalyani  24/04/2012  NaN         Jyoti   980  1020  1000 NaN
881  Kalyani  25/04/2012    8  Chandermukhi  1180  1220  1200 NaN
882  Kalyani  25/04/2012  NaN         Jyoti   980  1020  1000 NaN
883  Kalyani  26/04/2012    9  Chandermukhi  1180  1220  1200 NaN
884  Kalyani  26/04/2012  NaN         Jyoti   980  1020  1000 NaN
885  Kalyani  29/04/2012   10  Chandermukhi  1200  1240  1220 NaN
886  Kalyani  29/04/2012  NaN         Jyoti  1000  1100  1050 NaN
887  Kalyani  30/04/2012   15  Chandermukhi  1200  1240  1220 NaN
888  Kalyani  30/04/2012  NaN         Jyoti  1000  1100  1050 NaN

           0           1    2             3     4     5     6   7
844  Kalyani  01/08/2012    5  Chandermukhi  1240  1280  1260 NaN
845  Kalyani  01/08/2012  NaN         Jyoti  1140  1180  1160 NaN
846  Kalyani  02/08/2012  5.5  Chandermukhi  1240  1280  1260 NaN
847  Kalyani  02/08/2012  NaN         Jyoti  1140  1180  1160 NaN
848  Kalyani  03/08/2012    5  Chandermukhi  1260  1300  1280 NaN
849  Kalyani  03/08/2012  NaN         Jyoti  1160  1200  1180 NaN
850  Kalyani  06/08/2012    2  Chandermukhi  1460  1500  1480 NaN
851  Kalyani  06/08/2012  NaN         Jyoti  1260  1300  1280 NaN
852  Kalyani  07/08/2012  2.5  Chandermukhi  1460  1500  1480 NaN
853  Kalyani  07/08/2012  NaN         Jyoti  1260  1300  1280 NaN
854  Kalyani  08/08/2012  2.5  Chandermukhi  1460  1500  1480 NaN
855  Kalyani  08/08/2012  NaN         Jyoti  1260  1300  1280 NaN
856  Kalyani  09/08/2012  2.5  Chandermukhi  1460  1500  1480 NaN
857  Kalyani  09/08/2012  NaN         Jyoti  1260  1300  1280 NaN
858  Kalyani  10/08/2012    3  Chandermukhi  1460  1500  1480 NaN
859  Kalyani  10/08/2012  NaN         Jyoti  1260  1300  1280 NaN
860  Kalyani  13/08/2012    3  Chandermukhi  1460  1500  1480 NaN
861  Kalyani  13/08/2012  NaN         Jyoti  1260  1300  1280 NaN
862  Kalyani  14/08/2012  126  Chandermukhi  1460  1500  1480 NaN
863  Kalyani  14/08/2012  NaN         Jyoti  1260  1300  1280 NaN
864  Kalyani  15/08/2012  2.5  Chandermukhi  1460  1500  1480 NaN
865  Kalyani  15/08/2012  NaN         Jyoti  1260  1300  1280 NaN
866  Kalyani  16/08/2012  2.5  Chandermukhi  1460  1500  1480 NaN
867  Kalyani  16/08/2012  NaN         Jyoti  1260  1300  1280 NaN
868  Kalyani  19/08/2012  2.5  Chandermukhi  1200  1250  1230 NaN
869  Kalyani  19/08/2012  NaN         Jyoti  1100  1150  1130 NaN
870  Kalyani  20/08/2012    3  Chandermukhi  1200  1250  1230 NaN
871  Kalyani  20/08/2012  NaN         Jyoti  1100  1150  1130 NaN
872  Kalyani  21/08/2012    3  Chandermukhi  1200  1250  1230 NaN
873  Kalyani  21/08/2012  NaN         Jyoti  1100  1150  1130 NaN
874  Kalyani  22/08/2012    3  Chandermukhi  1200  1250  1230 NaN
875  Kalyani  22/08/2012  NaN         Jyoti  1100  1150  1130 NaN
876  Kalyani  23/08/2012  2.5  Chandermukhi  1200  1250  1230 NaN
877  Kalyani  23/08/2012  NaN         Jyoti  1100  1150  1130 NaN
878  Kalyani  24/08/2012  2.5  Chandermukhi  1130  1160  1150 NaN
879  Kalyani  24/08/2012  NaN         Jyoti  1030  1060  1050 NaN
880  Kalyani  25/08/2012    5  Chandermukhi  1130  1160  1150 NaN
881  Kalyani  25/08/2012  NaN         Jyoti  1030  1060  1050 NaN
882  Kalyani  26/08/2012    5  Chandermukhi  1130  1160  1150 NaN
883  Kalyani  26/08/2012  NaN         Jyoti  1030  1060  1050 NaN
884  Kalyani  27/08/2012    5  Chandermukhi  1130  1160  1150 NaN
885  Kalyani  27/08/2012  NaN         Jyoti  1030  1060  1050 NaN
886  Kalyani  28/08/2012    5  Chandermukhi  1130  1160  1150 NaN
887  Kalyani  28/08/2012  NaN         Jyoti  1030  1060  1050 NaN
888  Kalyani  29/08/2012    5  Chandermukhi  1130  1160  1150 NaN
889  Kalyani  29/08/2012  NaN         Jyoti  1030  1060  1050 NaN
890  Kalyani  30/08/2012  5.5  Chandermukhi  1130  1160  1150 NaN
891  Kalyani  30/08/2012  NaN         Jyoti  1030  1060  1050 NaN
892  Kalyani  31/08/2012    6  Chandermukhi  1130  1160  1150 NaN
893  Kalyani  31/08/2012  NaN         Jyoti  1030  1060  1050 NaN
           0           1    2             3     4     5     6   7
756  Kalyani  01/12/2012    5  Chandermukhi  1300  1360  1340 NaN
757  Kalyani  01/12/2012  NaN         Jyoti  1100  1160  1140 NaN
758  Kalyani  02/12/2012    5  Chandermukhi  1300  1360  1340 NaN
759  Kalyani  02/12/2012  NaN         Jyoti  1100  1160  1140 NaN
760  Kalyani  03/12/2012    5  Chandermukhi  1300  1360  1340 NaN
761  Kalyani  03/12/2012  NaN         Jyoti  1100  1160  1140 NaN
762  Kalyani  04/12/2012    5  Chandermukhi  1300  1360  1340 NaN
763  Kalyani  04/12/2012  NaN         Jyoti  1100  1160  1140 NaN
764  Kalyani  05/12/2012    5  Chandermukhi  1260  1320  1280 NaN
765  Kalyani  05/12/2012  NaN         Jyoti  1060  1120  1080 NaN
766  Kalyani  07/12/2012    5  Chandermukhi  1260  1320  1280 NaN
767  Kalyani  07/12/2012  NaN         Jyoti  1060  1120  1080 NaN
768  Kalyani  08/12/2012    5  Chandermukhi  1260  1320  1280 NaN
769  Kalyani  08/12/2012  NaN         Jyoti  1060  1100  1080 NaN
770  Kalyani  09/12/2012    5  Chandermukhi  1260  1320  1280 NaN
771  Kalyani  09/12/2012  NaN         Jyoti  1060  1100  1080 NaN
772  Kalyani  10/12/2012    6  Chandermukhi  1260  1320  1280 NaN
773  Kalyani  10/12/2012  NaN         Jyoti  1040  1060  1060 NaN
774  Kalyani  11/12/2012  5.5  Chandermukhi  1180  1260  1240 NaN
775  Kalyani  11/12/2012  NaN         Jyoti  1040  1060  1060 NaN
776  Kalyani  12/12/2012    5  Chandermukhi  1180  1260  1240 NaN
777  Kalyani  12/12/2012  NaN         Jyoti  1040  1060  1060 NaN
778  Kalyani  14/12/2012    6  Chandermukhi  1180  1260  1240 NaN
779  Kalyani  14/12/2012  NaN         Jyoti  1020  1060  1040 NaN
780  Kalyani  15/12/2012    6  Chandermukhi  1180  1260  1240 NaN
781  Kalyani  15/12/2012  NaN         Jyoti  1020  1060  1040 NaN
782  Kalyani  16/12/2012    6  Chandermukhi  1180  1260  1240 NaN
783  Kalyani  16/12/2012  NaN         Jyoti  1020  1060  1040 NaN
784  Kalyani  17/12/2012    6  Chandermukhi  1180  1260  1240 NaN
785  Kalyani  17/12/2012  NaN         Jyoti  1020  1060  1040 NaN
786  Kalyani  18/12/2012    6  Chandermukhi  1180  1260  1240 NaN
787  Kalyani  18/12/2012  NaN         Jyoti  1020  1060  1040 NaN
788  Kalyani  19/12/2012    6  Chandermukhi  1180  1260  1240 NaN
789  Kalyani  19/12/2012  NaN         Jyoti  1020  1060  1040 NaN
790  Kalyani  20/12/2012    6  Chandermukhi  1180  1260  1240 NaN
791  Kalyani  20/12/2012  NaN         Jyoti  1020  1060  1040 NaN
792  Kalyani  21/12/2012    6  Chandermukhi  1180  1260  1240 NaN
793  Kalyani  21/12/2012  NaN         Jyoti  1020  1060  1040 NaN
794  Kalyani  22/12/2012  5.5  Chandermukhi  1180  1260  1240 NaN
           0           1    2             3    4    5    6   7
755  Kalyani  01/02/2012   18         Jyoti  380  420  400 NaN
756  Kalyani  03/02/2012    8  Chandermukhi  680  720  700 NaN
757  Kalyani  03/02/2012  NaN         Jyoti  480  520  500 NaN
758  Kalyani  04/02/2012    8  Chandermukhi  680  720  700 NaN
759  Kalyani  04/02/2012  NaN         Jyoti  480  520  500 NaN
760  Kalyani  05/02/2012   10         Jyoti  380  420  400 NaN
761  Kalyani  09/02/2012   10  Chandermukhi  680  720  700 NaN
762  Kalyani  09/02/2012  NaN         Jyoti  480  520  500 NaN
763  Kalyani  10/02/2012   10  Chandermukhi  680  720  700 NaN
764  Kalyani  10/02/2012  NaN         Jyoti  480  520  500 NaN
765  Kalyani  11/02/2012   12  Chandermukhi  650  750  700 NaN
766  Kalyani  11/02/2012  NaN         Jyoti  480  520  500 NaN
767  Kalyani  12/02/2012   12  Chandermukhi  650  750  700 NaN
768  Kalyani  12/02/2012  NaN         Jyoti  480  520  500 NaN
769  Kalyani  13/02/2012   12  Chandermukhi  680  720  700 NaN
770  Kalyani  13/02/2012  NaN         Jyoti  480  520  500 NaN
771  Kalyani  14/02/2012   10  Chandermukhi  680  720  700 NaN
772  Kalyani  14/02/2012  NaN         Jyoti  480  520  500 NaN
773  Kalyani  15/02/2012   12  Chandermukhi  680  700  700 NaN
774  Kalyani  15/02/2012  NaN         Jyoti  480  520  500 NaN
775  Kalyani  16/02/2012   10  Chandermukhi  680  720  700 NaN
776  Kalyani  16/02/2012  NaN         Jyoti  480  520  500 NaN
777  Kalyani  17/02/2012   10  Chandermukhi  680  720  700 NaN
778  Kalyani  17/02/2012  NaN         Jyoti  480  520  500 NaN
779  Kalyani  18/02/2012   10  Chandermukhi  680  720  700 NaN
780  Kalyani  18/02/2012  NaN         Jyoti  450  500  480 NaN
781  Kalyani  19/02/2012   12  Chandermukhi  680  720  700 NaN
782  Kalyani  19/02/2012  NaN         Jyoti  430  480  450 NaN
783  Kalyani  20/02/2012   15  Chandermukhi  680  720  700 NaN
784  Kalyani  20/02/2012  NaN         Jyoti  400  420  400 NaN
785  Kalyani  21/02/2012   15  Chandermukhi  680  720  700 NaN
786  Kalyani  21/02/2012  NaN         Jyoti  400  420  400 NaN
787  Kalyani  22/02/2012   10  Chandermukhi  680  720  700 NaN
788  Kalyani  22/02/2012  NaN         Jyoti  400  420  400 NaN
789  Kalyani  23/02/2012   12  Chandermukhi  680  720  700 NaN
790  Kalyani  23/02/2012  NaN         Jyoti  400  420  400 NaN
791  Kalyani  24/02/2012   12  Chandermukhi  680  720  700 NaN
792  Kalyani  24/02/2012  NaN         Jyoti  400  420  400 NaN
793  Kalyani  25/02/2012   10  Chandermukhi  680  720  700 NaN
794  Kalyani  25/02/2012  NaN         Jyoti  400  420  400 NaN
795  Kalyani  26/02/2012   10  Chandermukhi  680  720  700 NaN
796  Kalyani  26/02/2012  NaN         Jyoti  400  420  400 NaN
797  Kalyani  27/02/2012   10  Chandermukhi  680  720  700 NaN
798  Kalyani  27/02/2012  NaN         Jyoti  400  440  420 NaN
799  Kalyani  29/02/2012    6  Chandermukhi  680  720  700 NaN
800  Kalyani  29/02/2012  NaN         Jyoti  480  520  500 NaN

           0           1    2             3    4    5    6   7
754  Kalyani  05/01/2012   10                 NR   NR   NR NaN
755  Kalyani  06/01/2012   10  Chandermukhi  650  700  680 NaN
756  Kalyani  06/01/2012  NaN         Jyoti  220  260  240 NaN
757  Kalyani  07/01/2012   10  Chandermukhi  650  700  680 NaN
758  Kalyani  07/01/2012  NaN         Jyoti  220  260  240 NaN
759  Kalyani  08/01/2012   10  Chandermukhi  650  700  680 NaN
760  Kalyani  08/01/2012  NaN         Jyoti  220  260  240 NaN
761  Kalyani  09/01/2012   10  Chandermukhi  650  700  680 NaN
762  Kalyani  09/01/2012  NaN         Jyoti  220  260  240 NaN
763  Kalyani  10/01/2012   10  Chandermukhi  650  700  680 NaN
764  Kalyani  10/01/2012  NaN         Jyoti  220  260  240 NaN
765  Kalyani  11/01/2012   10  Chandermukhi  650  700  680 NaN
766  Kalyani  11/01/2012  NaN         Jyoti  220  260  240 NaN
767  Kalyani  12/01/2012   10  Chandermukhi  650  700  680 NaN
768  Kalyani  12/01/2012  NaN         Jyoti  220  260  240 NaN
769  Kalyani  13/01/2012   10  Chandermukhi  650  700  680 NaN
770  Kalyani  13/01/2012  NaN         Jyoti  220  260  240 NaN
771  Kalyani  14/01/2012   10  Chandermukhi  650  700  680 NaN
772  Kalyani  14/01/2012  NaN         Jyoti  220  260  240 NaN
773  Kalyani  15/01/2012   10  Chandermukhi  650  700  680 NaN
774  Kalyani  15/01/2012  NaN         Jyoti  220  260  240 NaN
775  Kalyani  16/01/2012   10  Chandermukhi  680  720  700 NaN
776  Kalyani  16/01/2012  NaN         Jyoti  280  300  300 NaN
777  Kalyani  17/01/2012   12  Chandermukhi  680  720  700 NaN
778  Kalyani  17/01/2012  NaN         Jyoti  280  300  300 NaN
779  Kalyani  18/01/2012   10  Chandermukhi  700  750  730 NaN
780  Kalyani  18/01/2012  NaN         Jyoti  300  340  320 NaN
781  Kalyani  19/01/2012   10  Chandermukhi  700  750  730 NaN
782  Kalyani  19/01/2012  NaN         Jyoti  300  340  320 NaN
783  Kalyani  20/01/2012   10  Chandermukhi  700  750  730 NaN
784  Kalyani  20/01/2012  NaN         Jyoti  300  340  320 NaN
785  Kalyani  21/01/2012   20         Jyoti  350  380  360 NaN
786  Kalyani  22/01/2012   18         Jyoti  350  380  360 NaN
787  Kalyani  23/01/2012   18         Jyoti  380  420  400 NaN
788  Kalyani  24/01/2012   18         Jyoti  380  420  400 NaN
789  Kalyani  25/01/2012   15         Jyoti  380  420  400 NaN
790  Kalyani  26/01/2012   18         Jyoti  380  420  400 NaN
791  Kalyani  27/01/2012   18         Jyoti  380  420  400 NaN
792  Kalyani  28/01/2012   18         Jyoti  380  420  400 NaN
793  Kalyani  29/01/2012   18         Jyoti  380  420  400 NaN
794  Kalyani  30/01/2012   18         Jyoti  400  420  400 NaN
795  Kalyani  31/01/2012   15         Jyoti  380  420  400 NaN
           0           1    2             3     4     5     6   7
848  Kalyani  02/07/2012    7  Chandermukhi  1400  1440  1420 NaN
849  Kalyani  02/07/2012  NaN         Jyoti  1200  1240  1220 NaN
850  Kalyani  03/07/2012    7  Chandermukhi  1400  1440  1420 NaN
851  Kalyani  03/07/2012  NaN         Jyoti  1200  1240  1220 NaN
852  Kalyani  04/07/2012    7  Chandermukhi  1400  1420  1400 NaN
853  Kalyani  04/07/2012  NaN         Jyoti  1180  1230  1200 NaN
854  Kalyani  05/07/2012    7  Chandermukhi  1300  1400  1350 NaN
855  Kalyani  05/07/2012  NaN         Jyoti  1160  1200  1180 NaN
856  Kalyani  06/07/2012    7  Chandermukhi  1360  1400  1380 NaN
857  Kalyani  06/07/2012  NaN         Jyoti  1180  1200  1200 NaN
858  Kalyani  09/07/2012    7  Chandermukhi  1360  1400  1380 NaN
859  Kalyani  09/07/2012  NaN         Jyoti  1160  1200  1180 NaN
860  Kalyani  10/07/2012    7  Chandermukhi  1360  1400  1380 NaN
861  Kalyani  10/07/2012  NaN         Jyoti  1160  1200  1180 NaN
862  Kalyani  11/07/2012    8  Chandermukhi  1360  1400  1380 NaN
863  Kalyani  11/07/2012  NaN         Jyoti  1160  1200  1180 NaN
864  Kalyani  12/07/2012    7  Chandermukhi  1360  1400  1380 NaN
865  Kalyani  12/07/2012  NaN         Jyoti  1160  1200  1180 NaN
866  Kalyani  13/07/2012    7  Chandermukhi  1360  1400  1380 NaN
867  Kalyani  13/07/2012  NaN         Jyoti  1160  1200  1180 NaN
868  Kalyani  16/07/2012    7  Chandermukhi  1360  1400  1380 NaN
869  Kalyani  16/07/2012  NaN         Jyoti  1160  1200  1180 NaN
870  Kalyani  17/07/2012    7  Chandermukhi  1360  1400  1380 NaN
871  Kalyani  17/07/2012  NaN         Jyoti  1160  1200  1180 NaN
872  Kalyani  18/07/2012    7  Chandermukhi  1360  1400  1380 NaN
873  Kalyani  18/07/2012  NaN         Jyoti  1160  1200  1180 NaN
874  Kalyani  19/07/2012    7  Chandermukhi  1360  1400  1380 NaN
875  Kalyani  19/07/2012  NaN         Jyoti  1160  1200  1180 NaN
876  Kalyani  20/07/2012    8  Chandermukhi  1360  1400  1380 NaN
877  Kalyani  20/07/2012  NaN         Jyoti  1160  1200  1180 NaN
878  Kalyani  23/07/2012    5  Chandermukhi  1180  1220  1200 NaN
879  Kalyani  23/07/2012  NaN         Jyoti  1080  1120  1100 NaN
880  Kalyani  24/07/2012    5  Chandermukhi  1180  1220  1200 NaN
881  Kalyani  24/07/2012  NaN         Jyoti  1080  1120  1100 NaN
882  Kalyani  25/07/2012    6  Chandermukhi  1160  1200  1180 NaN
883  Kalyani  25/07/2012  NaN         Jyoti  1060  1100  1080 NaN
884  Kalyani  26/07/2012    5  Chandermukhi  1160  1200  1180 NaN
885  Kalyani  26/07/2012  NaN         Jyoti  1060  1100  1080 NaN
886  Kalyani  27/07/2012    5  Chandermukhi  1180  1220  1200 NaN
887  Kalyani  27/07/2012  NaN         Jyoti  1080  1120  1100 NaN
888  Kalyani  29/07/2012    5  Chandermukhi  1200  1240  1220 NaN
889  Kalyani  29/07/2012  NaN         Jyoti  1100  1140  1120 NaN
890  Kalyani  30/07/2012    5  Chandermukhi  1220  1260  1240 NaN
891  Kalyani  30/07/2012  NaN         Jyoti  1120  1160  1140 NaN
892  Kalyani  31/07/2012  5.5  Chandermukhi  1240  1280  1260 NaN
893  Kalyani  31/07/2012  NaN         Jyoti  1140  1180  1160 NaN
           0           1    2             3     4     5     6   7
821  Kalyani  01/06/2012   12  Chandermukhi  1200  1300  1250 NaN
822  Kalyani  01/06/2012  NaN         Jyoti  1050  1100  1080 NaN
823  Kalyani  02/06/2012    8  Chandermukhi  1200  1300  1250 NaN
824  Kalyani  02/06/2012  NaN         Jyoti  1050  1100  1080 NaN
825  Kalyani  04/06/2012   12  Chandermukhi  1200  1300  1250 NaN
826  Kalyani  04/06/2012  NaN         Jyoti  1050  1100  1080 NaN
827  Kalyani  05/06/2012   10  Chandermukhi  1200  1300  1250 NaN
828  Kalyani  05/06/2012  NaN         Jyoti  1050  1100  1080 NaN
829  Kalyani  06/06/2012   10  Chandermukhi  1200  1300  1250 NaN
830  Kalyani  06/06/2012  NaN         Jyoti  1050  1100  1080 NaN
831  Kalyani  07/06/2012   12  Chandermukhi  1300  1400  1350 NaN
832  Kalyani  07/06/2012  NaN         Jyoti  1100  1140  1120 NaN
833  Kalyani  08/06/2012   10  Chandermukhi  1300  1400  1350 NaN
834  Kalyani  11/06/2012   12  Chandermukhi  1300  1400  1350 NaN
835  Kalyani  11/06/2012  NaN         Jyoti  1100  1140  1120 NaN
836  Kalyani  12/06/2012   10  Chandermukhi  1300  1400  1350 NaN
837  Kalyani  12/06/2012  NaN         Jyoti  1100  1140  1120 NaN
838  Kalyani  13/06/2012   10  Chandermukhi  1300  1400  1350 NaN
839  Kalyani  13/06/2012  NaN         Jyoti  1100  1140  1120 NaN
840  Kalyani  14/06/2012   10  Chandermukhi  1300  1400  1350 NaN
841  Kalyani  14/06/2012  NaN         Jyoti  1100  1140  1120 NaN
842  Kalyani  15/06/2012   10  Chandermukhi  1300  1400  1350 NaN
843  Kalyani  15/06/2012  NaN         Jyoti  1100  1140  1120 NaN
844  Kalyani  16/06/2012   12  Chandermukhi  1300  1400  1350 NaN
845  Kalyani  16/06/2012  NaN         Jyoti  1100  1140  1120 NaN
846  Kalyani  17/06/2012   12  Chandermukhi  1300  1400  1350 NaN
847  Kalyani  17/06/2012  NaN         Jyoti  1100  1160  1140 NaN
848  Kalyani  18/06/2012   10  Chandermukhi  1300  1400  1350 NaN
849  Kalyani  18/06/2012  NaN         Jyoti  1100  1160  1140 NaN
850  Kalyani  19/06/2012   12  Chandermukhi  1300  1400  1350 NaN
851  Kalyani  19/06/2012  NaN         Jyoti  1100  1180  1160 NaN
852  Kalyani  20/06/2012   10  Chandermukhi  1300  1400  1350 NaN
853  Kalyani  20/06/2012  NaN         Jyoti  1140  1180  1160 NaN
854  Kalyani  21/06/2012   12  Chandermukhi  1500  1560  1540 NaN
855  Kalyani  21/06/2012  NaN         Jyoti  1200  1260  1240 NaN
856  Kalyani  22/06/2012   12  Chandermukhi  1400  1500  1450 NaN
857  Kalyani  22/06/2012  NaN         Jyoti  1200  1260  1240 NaN
858  Kalyani  25/06/2012    8  Chandermukhi  1400  1500  1450 NaN
859  Kalyani  25/06/2012  NaN         Jyoti  1200  1300  1250 NaN
860  Kalyani  26/06/2012    8  Chandermukhi  1400  1500  1450 NaN
861  Kalyani  26/06/2012  NaN         Jyoti  1200  1300  1250 NaN
862  Kalyani  27/06/2012    8  Chandermukhi  1440  1480  1460 NaN
863  Kalyani  27/06/2012  NaN         Jyoti  1240  1280  1260 NaN
864  Kalyani  28/06/2012  8.5  Chandermukhi  1440  1480  1460 NaN
865  Kalyani  28/06/2012  NaN         Jyoti  1240  1280  1260 NaN
866  Kalyani  29/06/2012    8         Jyoti  1240  1280  1260 NaN

           0           1    2             3     4     5     6   7
847  Kalyani  01/03/2012    8  Chandermukhi   680   720   700 NaN
848  Kalyani  01/03/2012  NaN         Jyoti   480   520   500 NaN
849  Kalyani  02/03/2012    8  Chandermukhi   680   720   700 NaN
850  Kalyani  02/03/2012  NaN         Jyoti   480   520   500 NaN
851  Kalyani  03/03/2012    6  Chandermukhi   680   720   700 NaN
852  Kalyani  03/03/2012  NaN         Jyoti   480   520   500 NaN
853  Kalyani  04/03/2012    5  Chandermukhi   680   720   700 NaN
854  Kalyani  04/03/2012  NaN         Jyoti   480   520   500 NaN
855  Kalyani  05/03/2012    6  Chandermukhi   680   720   700 NaN
856  Kalyani  05/03/2012  NaN         Jyoti   480   520   500 NaN
857  Kalyani  06/03/2012    6  Chandermukhi   780   820   800 NaN
858  Kalyani  06/03/2012  NaN         Jyoti   660   680   680 NaN
859  Kalyani  07/03/2012    6  Chandermukhi   780   820   800 NaN
860  Kalyani  07/03/2012  NaN         Jyoti   680   700   680 NaN
861  Kalyani  08/03/2012    6  Chandermukhi   780   820   800 NaN
862  Kalyani  08/03/2012  NaN         Jyoti   680   720   700 NaN
863  Kalyani  09/03/2012    6  Chandermukhi   780   820   800 NaN
864  Kalyani  09/03/2012  NaN         Jyoti   680   700   700 NaN
865  Kalyani  10/03/2012    6  Chandermukhi   750   780   750 NaN
866  Kalyani  10/03/2012  NaN         Jyoti   620   650   630 NaN
867  Kalyani  11/03/2012    6  Chandermukhi   700   750   730 NaN
868  Kalyani  11/03/2012  NaN         Jyoti   580   620   600 NaN
869  Kalyani  12/03/2012    8  Chandermukhi   680   720   700 NaN
870  Kalyani  12/03/2012  NaN         Jyoti   580   600   600 NaN
871  Kalyani  13/03/2012    8  Chandermukhi   680   720   700 NaN
872  Kalyani  13/03/2012  NaN         Jyoti   580   600   600 NaN
873  Kalyani  14/03/2012    7  Chandermukhi   680   720   700 NaN
874  Kalyani  14/03/2012  NaN         Jyoti   580   600   600 NaN
875  Kalyani  15/03/2012    8  Chandermukhi   680   720   700 NaN
876  Kalyani  15/03/2012  NaN         Jyoti   580   600   600 NaN
877  Kalyani  16/03/2012    6  Chandermukhi   900   950   930 NaN
878  Kalyani  16/03/2012  NaN         Jyoti   680   700   700 NaN
879  Kalyani  17/03/2012    6  Chandermukhi   900   950   930 NaN
880  Kalyani  17/03/2012  NaN         Jyoti   680   700   700 NaN
881  Kalyani  18/03/2012    6  Chandermukhi   900   950   930 NaN
882  Kalyani  18/03/2012  NaN         Jyoti   680   700   700 NaN
883  Kalyani  19/03/2012    6  Chandermukhi   900   950   930 NaN
884  Kalyani  19/03/2012  NaN         Jyoti   700   730   700 NaN
885  Kalyani  20/03/2012    6  Chandermukhi   900   950   930 NaN
886  Kalyani  20/03/2012  NaN         Jyoti   700   730   700 NaN
887  Kalyani  21/03/2012    8  Chandermukhi   900   950   930 NaN
888  Kalyani  21/03/2012  NaN         Jyoti   700   730   700 NaN
889  Kalyani  22/03/2012    8  Chandermukhi   900   950   930 NaN
890  Kalyani  22/03/2012  NaN         Jyoti   700   730   700 NaN
891  Kalyani  23/03/2012    6  Chandermukhi   900  1000   950 NaN
892  Kalyani  23/03/2012  NaN         Jyoti   750   800   780 NaN
893  Kalyani  24/03/2012  5.5  Chandermukhi   900  1000   950 NaN
894  Kalyani  24/03/2012  NaN         Jyoti   750   800   780 NaN
895  Kalyani  25/03/2012    6  Chandermukhi   900  1000   950 NaN
896  Kalyani  25/03/2012  NaN         Jyoti   800   850   830 NaN
897  Kalyani  26/03/2012    6  Chandermukhi   900  1000   950 NaN
898  Kalyani  26/03/2012  NaN         Jyoti   800   860   840 NaN
899  Kalyani  27/03/2012    6  Chandermukhi   900  1000   950 NaN
900  Kalyani  27/03/2012  NaN         Jyoti   850   900   880 NaN
901  Kalyani  28/03/2012    6  Chandermukhi  1000  1050  1030 NaN
902  Kalyani  28/03/2012  NaN         Jyoti   850   900   880 NaN
903  Kalyani  29/03/2012    6  Chandermukhi  1000  1050  1030 NaN
904  Kalyani  29/03/2012  NaN         Jyoti   850   900   880 NaN
905  Kalyani  31/03/2012    6  Chandermukhi  1130  1180  1150 NaN
906  Kalyani  31/03/2012  NaN         Jyoti  1000  1050  1030 NaN
           0           1    2             3     4     5     6   7
841  Kalyani  01/05/2012   10  Chandermukhi  1200  1240  1220 NaN
842  Kalyani  01/05/2012  NaN         Jyoti  1000  1100  1050 NaN
843  Kalyani  03/05/2012   10  Chandermukhi  1200  1240  1220 NaN
844  Kalyani  03/05/2012  NaN         Jyoti  1000  1100  1050 NaN
845  Kalyani  04/05/2012   10  Chandermukhi  1200  1240  1220 NaN
846  Kalyani  04/05/2012  NaN         Jyoti  1000  1100  1050 NaN
847  Kalyani  05/05/2012   10  Chandermukhi  1200  1240  1220 NaN
848  Kalyani  05/05/2012  NaN         Jyoti  1060  1100  1080 NaN
849  Kalyani  07/05/2012   12  Chandermukhi  1200  1260  1240 NaN
850  Kalyani  07/05/2012  NaN         Jyoti  1080  1120  1100 NaN
851  Kalyani  08/05/2012   10         Jyoti  1080  1120  1100 NaN
852  Kalyani  09/05/2012   12  Chandermukhi  1200  1260  1240 NaN
853  Kalyani  09/05/2012  NaN         Jyoti  1080  1120  1100 NaN
854  Kalyani  10/05/2012   10  Chandermukhi  1200  1260  1240 NaN
855  Kalyani  10/05/2012  NaN         Jyoti  1080  1120  1100 NaN
856  Kalyani  11/05/2012   10  Chandermukhi  1180  1240  1220 NaN
857  Kalyani  11/05/2012  NaN         Jyoti  1060  1100  1080 NaN
858  Kalyani  13/05/2012   12  Chandermukhi  1200  1300  1250 NaN
859  Kalyani  13/05/2012  NaN         Jyoti  1060  1100  1080 NaN
860  Kalyani  15/05/2012   12  Chandermukhi  1200  1300  1250 NaN
861  Kalyani  15/05/2012  NaN         Jyoti  1060  1100  1080 NaN
862  Kalyani  16/05/2012   12  Chandermukhi  1200  1300  1250 NaN
863  Kalyani  16/05/2012  NaN         Jyoti  1060  1100  1080 NaN
864  Kalyani  17/05/2012   12  Chandermukhi  1200  1300  1250 NaN
865  Kalyani  17/05/2012  NaN         Jyoti  1060  1100  1080 NaN
866  Kalyani  18/05/2012   12  Chandermukhi  1200  1300  1250 NaN
867  Kalyani  18/05/2012  NaN         Jyoti  1060  1100  1080 NaN
868  Kalyani  21/05/2012   10  Chandermukhi  1180  1250  1250 NaN
869  Kalyani  21/05/2012  NaN         Jyoti  1050  1100  1080 NaN
870  Kalyani  22/05/2012   12  Chandermukhi  1180  1280  1250 NaN
871  Kalyani  22/05/2012  NaN         Jyoti  1050  1100  1080 NaN
872  Kalyani  23/05/2012   10  Chandermukhi  1180  1280  1250 NaN
873  Kalyani  23/05/2012  NaN         Jyoti  1050  1100  1080 NaN
874  Kalyani  24/05/2012   10  Chandermukhi  1200  1300  1250 NaN
875  Kalyani  24/05/2012  NaN         Jyoti  1050  1100  1080 NaN
876  Kalyani  25/05/2012   10  Chandermukhi  1200  1300  1250 NaN
877  Kalyani  25/05/2012  NaN         Jyoti  1050  1100  1080 NaN
878  Kalyani  28/05/2012   12  Chandermukhi  1200  1300  1250 NaN
879  Kalyani  28/05/2012  NaN         Jyoti  1050  1100  1080 NaN
880  Kalyani  29/05/2012   10  Chandermukhi  1200  1300  1250 NaN
881  Kalyani  29/05/2012  NaN         Jyoti  1050  1100  1080 NaN
882  Kalyani  30/05/2012   15  Chandermukhi  1200  1300  1250 NaN
883  Kalyani  30/05/2012  NaN         Jyoti  1050  1100  1080 NaN
884  Kalyani  31/05/2012   12  Chandermukhi  1200  1300  1250 NaN
885  Kalyani  31/05/2012  NaN         Jyoti  1050  1100  1080 NaN
           0           1    2             3     4     5     6   7
744  Kalyani  01/11/2012    6  Chandermukhi  1360  1440  1400 NaN
745  Kalyani  01/11/2012  NaN         Jyoti  1180  1220  1200 NaN
746  Kalyani  02/11/2012    5  Chandermukhi  1400  1480  1440 NaN
747  Kalyani  02/11/2012  NaN         Jyoti  1180  1220  1200 NaN
748  Kalyani  03/11/2012    6  Chandermukhi  1400  1480  1440 NaN
749  Kalyani  03/11/2012  NaN         Jyoti  1180  1220  1200 NaN
750  Kalyani  04/11/2012    6  Chandermukhi  1400  1480  1440 NaN
751  Kalyani  04/11/2012  NaN         Jyoti  1180  1220  1200 NaN
752  Kalyani  05/11/2012    6  Chandermukhi  1400  1480  1440 NaN
753  Kalyani  05/11/2012  NaN         Jyoti  1180  1220  1200 NaN
754  Kalyani  06/11/2012    5  Chandermukhi  1400  1480  1440 NaN
755  Kalyani  06/11/2012  NaN         Jyoti  1180  1220  1200 NaN
756  Kalyani  07/11/2012    6  Chandermukhi  1400  1480  1440 NaN
757  Kalyani  07/11/2012  NaN         Jyoti  1180  1220  1200 NaN
758  Kalyani  08/11/2012    6  Chandermukhi  1400  1480  1440 NaN
759  Kalyani  08/11/2012  NaN         Jyoti  1180  1220  1200 NaN
760  Kalyani  09/11/2012    6  Chandermukhi  1400  1480  1440 NaN
761  Kalyani  09/11/2012  NaN         Jyoti  1180  1220  1200 NaN
762  Kalyani  10/11/2012    5  Chandermukhi  1400  1480  1440 NaN
763  Kalyani  10/11/2012  NaN         Jyoti  1180  1220  1200 NaN
764  Kalyani  11/11/2012    5  Chandermukhi  1400  1480  1440 NaN
765  Kalyani  11/11/2012  NaN         Jyoti  1180  1220  1200 NaN
766  Kalyani  26/11/2012    5  Chandermukhi  1300  1360  1340 NaN
767  Kalyani  26/11/2012  NaN         Jyoti  1100  1160  1140 NaN
768  Kalyani  27/11/2012    5  Chandermukhi  1300  1360  1340 NaN
769  Kalyani  27/11/2012  NaN         Jyoti  1100  1160  1140 NaN
770  Kalyani  28/11/2012    6  Chandermukhi  1300  1360  1340 NaN
771  Kalyani  28/11/2012  NaN         Jyoti  1100  1160  1140 NaN
772  Kalyani  29/11/2012    5  Chandermukhi  1300  1360  1340 NaN
773  Kalyani  29/11/2012  NaN         Jyoti  1100  1160  1140 NaN
774  Kalyani  30/11/2012    5  Chandermukhi  1300  1360  1340 NaN
775  Kalyani  30/11/2012  NaN         Jyoti  1100  1160  1140 NaN

           0           1    2             3     4     5     6   7
668  Kalyani  01/10/2012    6  Chandermukhi  1360  1400  1380 NaN
669  Kalyani  02/10/2012    6  Chandermukhi  1360  1400  1380 NaN
670  Kalyani  02/10/2012  NaN         Jyoti  1060  1100  1080 NaN
671  Kalyani  03/10/2012  5.5  Chandermukhi  1360  1400  1380 NaN
672  Kalyani  03/10/2012  NaN         Jyoti  1060  1100  1080 NaN
673  Kalyani  04/10/2012    6  Chandermukhi  1360  1400  1380 NaN
674  Kalyani  04/10/2012  NaN         Jyoti  1060  1100  1080 NaN
675  Kalyani  05/10/2012  5.5  Chandermukhi  1360  1400  1380 NaN
676  Kalyani  05/10/2012  NaN         Jyoti  1060  1100  1080 NaN
677  Kalyani  06/10/2012    6  Chandermukhi  1360  1400  1380 NaN
678  Kalyani  06/10/2012  NaN         Jyoti  1060  1100  1080 NaN
679  Kalyani  07/10/2012    6  Chandermukhi  1360  1400  1380 NaN
680  Kalyani  07/10/2012  NaN         Jyoti  1060  1100  1080 NaN
681  Kalyani  08/10/2012  5.5  Chandermukhi  1360  1400  1380 NaN
682  Kalyani  08/10/2012  NaN         Jyoti  1060  1100  1080 NaN
683  Kalyani  09/10/2012    6  Chandermukhi  1360  1400  1380 NaN
684  Kalyani  09/10/2012  NaN         Jyoti  1060  1100  1080 NaN
685  Kalyani  10/10/2012    5  Chandermukhi  1280  1360  1320 NaN
686  Kalyani  10/10/2012  NaN         Jyoti  1060  1100  1080 NaN
687  Kalyani  12/10/2012    5  Chandermukhi  1280  1360  1320 NaN
688  Kalyani  12/10/2012  NaN         Jyoti  1060  1100  1080 NaN
689  Kalyani  13/10/2012    6  Chandermukhi  1280  1360  1320 NaN
690  Kalyani  13/10/2012  NaN         Jyoti  1060  1100  1080 NaN
691  Kalyani  14/10/2012    6  Chandermukhi  1280  1360  1320 NaN
692  Kalyani  14/10/2012  NaN         Jyoti  1060  1100  1080 NaN
693  Kalyani  15/10/2012    6  Chandermukhi  1360  1400  1380 NaN
694  Kalyani  15/10/2012  NaN         Jyoti  1060  1100  1080 NaN
695  Kalyani  16/10/2012    5  Chandermukhi  1280  1360  1320 NaN
696  Kalyani  16/10/2012  NaN         Jyoti  1080  1100  1080 NaN
697  Kalyani  17/10/2012    6  Chandermukhi  1280  1360  1320 NaN
698  Kalyani  17/10/2012  NaN         Jyoti  1060  1100  1080 NaN
699  Kalyani  18/10/2012    6  Chandermukhi  1360  1440  1400 NaN
700  Kalyani  18/10/2012  NaN         Jyoti  1160  1200  1180 NaN
701  Kalyani  20/10/2012    5  Chandermukhi  1360  1440  1400 NaN
702  Kalyani  20/10/2012  NaN         Jyoti  1160  1200  1180 NaN
703  Kalyani  21/10/2012    5  Chandermukhi  1360  1440  1400 NaN
704  Kalyani  21/10/2012  NaN         Jyoti  1160  1200  1180 NaN
705  Kalyani  22/10/2012    5  Chandermukhi  1360  1440  1400 NaN
706  Kalyani  22/10/2012  NaN         Jyoti  1160  1200  1180 NaN
707  Kalyani  23/10/2012    6  Chandermukhi  1360  1440  1400 NaN
708  Kalyani  23/10/2012  NaN         Jyoti  1160  1200  1180 NaN
709  Kalyani  24/10/2012    6  Chandermukhi  1360  1440  1400 NaN
710  Kalyani  24/10/2012  NaN         Jyoti  1160  1200  1180 NaN
711  Kalyani  25/10/2012    5  Chandermukhi  1360  1440  1400 NaN
712  Kalyani  25/10/2012  NaN         Jyoti  1160  1200  1180 NaN
713  Kalyani  26/10/2012    5  Chandermukhi  1360  1440  1400 NaN
714  Kalyani  26/10/2012  NaN         Jyoti  1160  1200  1180 NaN
715  Kalyani  27/10/2012    5  Chandermukhi  1360  1440  1400 NaN
716  Kalyani  27/10/2012  NaN         Jyoti  1180  1220  1200 NaN
717  Kalyani  28/10/2012    5  Chandermukhi  1360  1440  1400 NaN
718  Kalyani  28/10/2012  NaN         Jyoti  1180  1220  1200 NaN
719  Kalyani  29/10/2012    6  Chandermukhi  1360  1440  1400 NaN
720  Kalyani  29/10/2012  NaN         Jyoti  1180  1220  1200 NaN
721  Kalyani  30/10/2012    5  Chandermukhi  1360  1440  1400 NaN
722  Kalyani  30/10/2012  NaN         Jyoti  1180  1220  1200 NaN
723  Kalyani  31/10/2012    5  Chandermukhi  1360  1440  1400 NaN
724  Kalyani  31/10/2012  NaN         Jyoti  1180  1220  1200 NaN
           0           1    2             3     4     5     6   7
794  Kalyani  01/09/2012  5.5  Chandermukhi  1130  1160  1150 NaN
795  Kalyani  01/09/2012  NaN         Jyoti  1030  1060  1050 NaN
796  Kalyani  03/09/2012    6  Chandermukhi  1130  1160  1150 NaN
797  Kalyani  03/09/2012  NaN         Jyoti  1030  1060  1050 NaN
798  Kalyani  04/09/2012    5  Chandermukhi  1400  1440  1420 NaN
799  Kalyani  04/09/2012  NaN         Jyoti  1100  1140  1120 NaN
800  Kalyani  05/09/2012    5  Chandermukhi  1400  1440  1420 NaN
801  Kalyani  05/09/2012  NaN         Jyoti  1100  1140  1120 NaN
802  Kalyani  06/09/2012    5  Chandermukhi  1400  1440  1420 NaN
803  Kalyani  06/09/2012  NaN         Jyoti  1100  1140  1120 NaN
804  Kalyani  07/09/2012    5  Chandermukhi  1400  1450  1430 NaN
805  Kalyani  07/09/2012  NaN         Jyoti  1100  1150  1130 NaN
806  Kalyani  08/09/2012  5.5  Chandermukhi  1400  1450  1430 NaN
807  Kalyani  08/09/2012  NaN         Jyoti  1100  1150  1130 NaN
808  Kalyani  09/09/2012  5.5  Chandermukhi  1400  1440  1420 NaN
809  Kalyani  09/09/2012  NaN         Jyoti  1060  1100  1080 NaN
810  Kalyani  10/09/2012  5.5  Chandermukhi  1400  1440  1420 NaN
811  Kalyani  10/09/2012  NaN         Jyoti  1060  1100  1080 NaN
812  Kalyani  11/09/2012    5  Chandermukhi  1400  1440  1420 NaN
813  Kalyani  11/09/2012  NaN         Jyoti  1060  1100  1080 NaN
814  Kalyani  12/09/2012    5  Chandermukhi  1400  1440  1420 NaN
815  Kalyani  12/09/2012  NaN         Jyoti  1060  1100  1080 NaN
816  Kalyani  13/09/2012    5  Chandermukhi  1400  1440  1420 NaN
817  Kalyani  13/09/2012  NaN         Jyoti  1060  1100  1080 NaN
818  Kalyani  14/09/2012    6  Chandermukhi  1400  1550  1430 NaN
819  Kalyani  14/09/2012  NaN         Jyoti  1060  1100  1080 NaN
820  Kalyani  15/09/2012    5  Chandermukhi  1400  1450  1430 NaN
821  Kalyani  15/09/2012  NaN         Jyoti  1060  1100  1080 NaN
822  Kalyani  16/09/2012    5  Chandermukhi  1400  1450  1430 NaN
823  Kalyani  16/09/2012  NaN         Jyoti  1060  1100  1080 NaN
824  Kalyani  17/09/2012    5  Chandermukhi  1400  1450  1430 NaN
825  Kalyani  17/09/2012  NaN         Jyoti  1060  1100  1080 NaN
826  Kalyani  18/09/2012    5  Chandermukhi  1400  1450  1430 NaN
827  Kalyani  18/09/2012  NaN         Jyoti  1060  1100  1080 NaN
828  Kalyani  19/09/2012    5  Chandermukhi  1400  1450  1430 NaN
829  Kalyani  19/09/2012  NaN         Jyoti  1060  1100  1080 NaN
830  Kalyani  23/09/2012    5  Chandermukhi  1360  1420  1380 NaN
831  Kalyani  23/09/2012  NaN         Jyoti  1120  1160  1140 NaN
832  Kalyani  24/09/2012    5  Chandermukhi  1400  1500  1450 NaN
833  Kalyani  24/09/2012  NaN         Jyoti  1160  1200  1180 NaN
834  Kalyani  25/09/2012    5  Chandermukhi  1400  1500  1450 NaN
835  Kalyani  25/09/2012  NaN         Jyoti  1160  1200  1180 NaN
836  Kalyani  26/09/2012  5.5  Chandermukhi  1400  1450  1430 NaN
837  Kalyani  26/09/2012  NaN         Jyoti  1100  1150  1130 NaN
838  Kalyani  27/09/2012  5.5  Chandermukhi  1400  1450  1430 NaN
839  Kalyani  27/09/2012  NaN         Jyoti  1100  1150  1130 NaN
840  Kalyani  28/09/2012    5  Chandermukhi  1400  1450  1430 NaN
841  Kalyani  28/09/2012  NaN         Jyoti  1100  1150  1130 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2      3    4    5    6   7
815  Kalyani  01/01/2013  5.5  Jyoti  800  880  830 NaN
816  Kalyani  02/01/2013    6  Jyoti  800  870  830 NaN
817  Kalyani  04/01/2013    6  Jyoti  780  860  830 NaN
818  Kalyani  05/01/2013    6  Jyoti  750  820  800 NaN
819  Kalyani  07/01/2013    6  Jyoti  720  760  740 NaN
820  Kalyani  08/01/2013    5  Jyoti  700  770  740 NaN
821  Kalyani  09/01/2013    5  Jyoti  700  770  750 NaN
822  Kalyani  10/01/2013    5  Jyoti  700  770  740 NaN
823  Kalyani  11/01/2013    5          NR   NR   NR NaN
824  Kalyani  12/01/2013    4  Jyoti  700  770  750 NaN
825  Kalyani  13/01/2013  5.5  Jyoti  720  800  750 NaN
826  Kalyani  14/01/2013    6  Jyoti  700  800  750 NaN
827  Kalyani  15/01/2013  5.5  Jyoti  680  720  700 NaN
828  Kalyani  16/01/2013    6  Jyoti  680  720  700 NaN
829  Kalyani  17/01/2013    6  Jyoti  680  720  700 NaN

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1     2      3     4     5     6   7
824  Kalyani  01/04/2014   1.8  Jyoti  1000  1100  1050 NaN
825  Kalyani  02/04/2014   1.8  Jyoti   950  1050  1000 NaN
826  Kalyani  03/04/2014  1.85  Jyoti   900  1100  1000 NaN
827  Kalyani  04/04/2014  1.75  Jyoti   950  1150  1050 NaN
828  Kalyani  05/04/2014   1.7  Jyoti  1000  1200  1100 NaN
829  Kalyani  07/04/2014  1.65  Jyoti  1000  1200  1100 NaN
830  Kalyani  08/04/2014   1.6  Jyoti  1100  1200  1150 NaN
831  Kalyani  09/04/2014  1.55  Jyoti  1100  1200  1150 NaN
832  Kalyani  10/04/2014   1.5  Jyoti  1200  1300  1250 NaN
833  Kalyani  11/04/2014   1.4  Jyoti  1200  1300  1250 NaN
834  Kalyani  12/04/2014   1.4  Jyoti  1200  1300  1250 NaN
835  Kalyani  14/04/2014  1.45  Jyoti  1200  1300  1250 NaN
836  Kalyani  15/04/2014  1.45  Jyoti  1200  1300  1250 NaN
837  Kalyani  16/04/2014   1.4  Jyoti  1200  1300  1250 NaN
838  Kalyani  17/04/2014  1.35  Jyoti  1200  1300  1250 NaN
839  Kalyani  18/04/2014   1.3  Jyoti  1200  1400  1300 NaN
840  Kalyani  19/04/2014  1.25  Jyoti  1250  1400  1350 NaN
841  Kalyani  21/04/2014   1.2  Jyoti  1200  1450  1350 NaN
842  Kalyani  22/04/2014   1.1  Jyoti  1250  1450  1350 NaN
843  Kalyani  23/04/2014  1.15  Jyoti  1250  1400  1350 NaN
844  Kalyani  24/04/2014   1.1  Jyoti  1300  1400  1350 NaN
845  Kalyani  25/04/2014  1.05  Jyoti  1300  1400  1350 NaN
846  Kalyani  26/04/2014   1.5  Jyoti  1300  1400  1350 NaN
847  Kalyani  28/04/2014   1.5  Jyoti  1300  1400  1350 NaN
848  Kalyani  29/04/2014   1.4  Jyoti  1300  1400  1350 NaN
849  Kalyani  30/04/2014   1.5  Jyoti  1300  1400  1350 NaN
           0           1    2      3     4     5     6   7
744  Kalyani  01/08/2014  1.6  Jyoti  1500  1600  1550 NaN
745  Kalyani  02/08/2014  1.5  Jyoti  1600  1700  1650 NaN
746  Kalyani  04/08/2014  1.5  Jyoti  1600  1700  1650 NaN
747  Kalyani  05/08/2014  1.5  Jyoti  1650  1750  1700 NaN
748  Kalyani  06/08/2014  1.6  Jyoti  1700  1800  1750 NaN
749  Kalyani  07/08/2014  1.5  Jyoti  1700  1800  1750 NaN
750  Kalyani  08/08/2014  1.6  Jyoti  1650  1750  1700 NaN
751  Kalyani  09/08/2014  1.5  Jyoti  1700  1800  1750 NaN
752  Kalyani  11/08/2014  1.6  Jyoti  1700  1800  1750 NaN
753  Kalyani  12/08/2014  1.5  Jyoti  1700  1800  1750 NaN
754  Kalyani  13/08/2014  1.5  Jyoti  1700  1800  1750 NaN
755  Kalyani  14/08/2014  1.5  Jyoti  1700  1800  1750 NaN
756  Kalyani  16/08/2014  1.6  Jyoti  1800  1900  1850 NaN
757  Kalyani  18/08/2014  1.5  Jyoti  1800  1900  1850 NaN
758  Kalyani  19/08/2014  1.6  Jyoti  1800  1900  1850 NaN
759  Kalyani  20/08/2014  1.5  Jyoti  1800  1900  1850 NaN
760  Kalyani  21/08/2014  1.5  Jyoti  1750  1850  1800 NaN
761  Kalyani  22/08/2014  1.5  Jyoti  1750  1850  1800 NaN
762  Kalyani  23/08/2014  1.5  Jyoti  1750  1850  1800 NaN
763  Kalyani  25/08/2014  1.5  Jyoti  1700  1800  1750 NaN
764  Kalyani  26/08/2014  1.5  Jyoti  1700  1800  1750 NaN
765  Kalyani  27/08/2014  1.5  Jyoti  1700  1800  1750 NaN
766  Kalyani  28/08/2014  1.5  Jyoti  1700  1800  1750 NaN
767  Kalyani  29/08/2014  1.5  Jyoti  1700  1800  1750 NaN
768  Kalyani  30/08/2014  1.5  Jyoti  1700  1800  1750 NaN
           0           1     2      3     4     5     6   7
886  Kalyani  01/12/2014   1.3  Jyoti  1800  2000  1900 NaN
887  Kalyani  02/12/2014   1.2  Jyoti  1800  2000  1900 NaN
888  Kalyani  03/12/2014  1.15  Jyoti  1800  2000  1900 NaN
889  Kalyani  04/12/2014   1.1  Jyoti  1800  1900  1850 NaN
890  Kalyani  05/12/2014  1.15  Jyoti  1800  1900  1850 NaN
891  Kalyani  06/12/2014   1.2  Jyoti  1800  1900  1850 NaN
892  Kalyani  08/12/2014  1.25  Jyoti  1750  1850  1800 NaN
893  Kalyani  09/12/2014   1.3  Jyoti  1750  1850  1800 NaN
894  Kalyani  10/12/2014  1.25  Jyoti  1750  1850  1800 NaN
895  Kalyani  11/12/2014   1.2  Jyoti  1750  1850  1800 NaN
896  Kalyani  12/12/2014  1.15  Jyoti  1700  1800  1750 NaN
897  Kalyani  13/12/2014   1.2  Jyoti  1700  1800  1750 NaN
898  Kalyani  15/12/2014  1.25  Jyoti  1600  1700  1650 NaN
899  Kalyani  16/12/2014   1.2  Jyoti  1600  1700  1650 NaN
900  Kalyani  17/12/2014  1.25  Jyoti  1600  1700  1650 NaN
901  Kalyani  18/12/2014   1.2  Jyoti  1600  1700  1650 NaN
902  Kalyani  19/12/2014  1.25  Jyoti  1600  1700  1650 NaN
903  Kalyani  20/12/2014   1.2  Jyoti  1600  1700  1650 NaN
904  Kalyani  22/12/2014  1.25  Jyoti  1400  1600  1500 NaN
905  Kalyani  23/12/2014   1.2  Jyoti  1400  1600  1500 NaN
906  Kalyani  24/12/2014  1.25  Jyoti  1400  1600  1500 NaN
907  Kalyani  25/12/2014   1.2  Jyoti  1400  1600  1500 NaN
908  Kalyani  26/12/2014  1.25  Jyoti  1400  1600  1500 NaN
909  Kalyani  27/12/2014   1.2  Jyoti  1300  1500  1400 NaN
910  Kalyani  29/12/2014   1.5  Jyoti   950  1050  1000 NaN
911  Kalyani  30/12/2014  1.55  Jyoti   900  1000   950 NaN
912  Kalyani  31/12/2014   1.6  Jyoti   900  1000   950 NaN
           0           1    2      3    4    5    6   7
732  Kalyani  17/02/2014  0.8  Jyoti  680  700  690 NaN
733  Kalyani  18/02/2014  0.8  Jyoti  700  720  710 NaN
734  Kalyani  19/02/2014  0.9  Jyoti  700  800  750 NaN
735  Kalyani  20/02/2014  0.9  Jyoti  700  800  750 NaN
736  Kalyani  21/02/2014  0.9  Jyoti  700  800  750 NaN
737  Kalyani  22/02/2014    1  Jyoti  700  740  725 NaN
738  Kalyani  24/02/2014    1  Jyoti  700  730  720 NaN
739  Kalyani  25/02/2014    5  Jyoti  700  720  710 NaN
740  Kalyani  26/02/2014    6  Jyoti  680  700  690 NaN
741  Kalyani  27/02/2014    6  Jyoti  700  720  710 NaN
742  Kalyani  28/02/2014  5.5  Jyoti  680  700  690 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1     2      3     4     5     6   7
806  Kalyani  01/07/2014   1.6  Jyoti  1450  1550  1500 NaN
807  Kalyani  02/07/2014   1.6  Jyoti  1450  1550  1500 NaN
808  Kalyani  03/07/2014   1.5  Jyoti  1450  1550  1500 NaN
809  Kalyani  04/07/2014   1.6  Jyoti  1450  1550  1500 NaN
810  Kalyani  05/07/2014   1.6  Jyoti  1500  1600  1550 NaN
811  Kalyani  07/07/2014  1.55  Jyoti  1500  1600  1550 NaN
812  Kalyani  08/07/2014   1.5  Jyoti  1500  1600  1550 NaN
813  Kalyani  09/07/2014   1.6  Jyoti  1500  1600  1550 NaN
814  Kalyani  10/07/2014   1.6  Jyoti  1450  1550  1500 NaN
815  Kalyani  11/07/2014  1.55  Jyoti  1450  1550  1500 NaN
816  Kalyani  12/07/2014   1.6  Jyoti  1450  1550  1500 NaN
817  Kalyani  14/07/2014  1.55  Jyoti  1450  1550  1500 NaN
818  Kalyani  15/07/2014   1.6  Jyoti  1450  1550  1500 NaN
819  Kalyani  16/07/2014  1.55  Jyoti  1450  1550  1500 NaN
820  Kalyani  17/07/2014   1.6  Jyoti  1450  1550  1500 NaN
821  Kalyani  18/07/2014  1.55  Jyoti  1450  1550  1500 NaN
822  Kalyani  19/07/2014   1.5  Jyoti  1500  1600  1550 NaN
823  Kalyani  20/07/2014  1.55  Jyoti  1500  1600  1550 NaN
824  Kalyani  21/07/2014  1.55  Jyoti  1500  1600  1550 NaN
825  Kalyani  22/07/2014   1.6  Jyoti  1500  1600  1550 NaN
826  Kalyani  23/07/2014   1.6  Jyoti  1450  1550  1500 NaN
827  Kalyani  24/07/2014   1.5  Jyoti  1500  1600  1550 NaN
828  Kalyani  25/07/2014   1.6  Jyoti  1500  1600  1550 NaN
829  Kalyani  26/07/2014   1.5  Jyoti  1500  1600  1550 NaN
830  Kalyani  28/07/2014  1.55  Jyoti  1500  1600  1550 NaN
831  Kalyani  30/07/2014   1.5  Jyoti  1500  1600  1550 NaN
832  Kalyani  31/07/2014   1.6  Jyoti  1500  1600  1550 NaN
           0           1     2      3     4     5     6   7
716  Kalyani  02/06/2014  1.55  Jyoti  1400  1500  1450 NaN
717  Kalyani  03/06/2014   1.5  Jyoti  1400  1500  1450 NaN
718  Kalyani  04/06/2014  1.55  Jyoti  1400  1500  1450 NaN
719  Kalyani  05/06/2014   1.5  Jyoti  1400  1500  1450 NaN
720  Kalyani  06/06/2014   1.5  Jyoti  1400  1500  1450 NaN
721  Kalyani  07/06/2014  1.55  Jyoti  1400  1500  1450 NaN
722  Kalyani  09/06/2014   1.5  Jyoti  1400  1500  1450 NaN
723  Kalyani  10/06/2014  1.55  Jyoti  1400  1500  1450 NaN
724  Kalyani  11/06/2014   1.5  Jyoti  1400  1500  1450 NaN
725  Kalyani  12/06/2014  1.55  Jyoti  1400  1500  1450 NaN
726  Kalyani  13/06/2014   1.5  Jyoti  1400  1500  1450 NaN
727  Kalyani  14/06/2014  1.55  Jyoti  1450  1550  1500 NaN
728  Kalyani  16/06/2014   1.6  Jyoti  1450  1550  1500 NaN
729  Kalyani  17/06/2014   1.5  Jyoti  1450  1550  1500 NaN
730  Kalyani  18/06/2014  1.55  Jyoti  1450  1550  1500 NaN
731  Kalyani  19/06/2014   1.5  Jyoti  1450  1550  1500 NaN
732  Kalyani  20/06/2014   1.5  Jyoti  1450  1550  1500 NaN
733  Kalyani  21/06/2014  1.55  Jyoti  1450  1550  1500 NaN
734  Kalyani  23/06/2014   1.6  Jyoti  1450  1550  1500 NaN
735  Kalyani  24/06/2014   1.5  Jyoti  1450  1550  1500 NaN
736  Kalyani  25/06/2014   1.4  Jyoti  1450  1550  1500 NaN
737  Kalyani  26/06/2014   1.3  Jyoti  1500  1600  1550 NaN
738  Kalyani  27/06/2014   1.4  Jyoti  1500  1600  1550 NaN
739  Kalyani  28/06/2014  1.45  Jyoti  1450  1550  1500 NaN
740  Kalyani  30/06/2014   1.5  Jyoti  1450  1550  1500 NaN

           0           1     2      3     4     5     6   7
921  Kalyani  01/03/2014   5.3  Jyoti   670   700   680 NaN
922  Kalyani  03/03/2014   5.5  Jyoti   660   700   680 NaN
923  Kalyani  04/03/2014   5.3  Jyoti   680   720   690 NaN
924  Kalyani  05/03/2014   5.2  Jyoti   690   720   700 NaN
925  Kalyani  06/03/2014     5  Jyoti   800   840   830 NaN
926  Kalyani  07/03/2014   5.1  Jyoti   800   850   830 NaN
927  Kalyani  08/03/2014   4.9  Jyoti   850   900   860 NaN
928  Kalyani  10/03/2014   4.8  Jyoti   860   910   870 NaN
929  Kalyani  11/03/2014   4.6  Jyoti   870   920   880 NaN
930  Kalyani  12/03/2014   4.5  Jyoti   880   930   890 NaN
931  Kalyani  13/03/2014   4.6  Jyoti   880   950   900 NaN
932  Kalyani  14/03/2014   4.7  Jyoti   900  1000   950 NaN
933  Kalyani  15/03/2014   4.5  Jyoti   900  1000   950 NaN
934  Kalyani  17/03/2014  4.55  Jyoti   950  1050  1000 NaN
935  Kalyani  18/03/2014   4.6  Jyoti   950  1050  1000 NaN
936  Kalyani  19/03/2014  4.65  Jyoti  1000  1100  1050 NaN
937  Kalyani  20/03/2014   4.7  Jyoti  1000  1100  1050 NaN
938  Kalyani  21/03/2014   1.9  Jyoti  1000  1100  1050 NaN
939  Kalyani  22/03/2014  1.85  Jyoti  1000  1100  1050 NaN
940  Kalyani  24/03/2014   1.8  Jyoti  1050  1150  1100 NaN
941  Kalyani  25/03/2014   1.7  Jyoti  1050  1150  1100 NaN
942  Kalyani  26/03/2014   1.8  Jyoti  1000  1100  1050 NaN
943  Kalyani  27/03/2014  1.85  Jyoti  1000  1100  1050 NaN
944  Kalyani  28/03/2014   1.8  Jyoti  1000  1100  1050 NaN
945  Kalyani  29/03/2014  1.75  Jyoti  1000  1100  1050 NaN
946  Kalyani  31/03/2014   1.7  Jyoti  1050  1150  1100 NaN
           0           1     2      3     4     5     6   7
851  Kalyani  01/05/2014   1.4  Jyoti  1300  1400  1350 NaN
852  Kalyani  02/05/2014  1.45  Jyoti  1300  1400  1350 NaN
853  Kalyani  03/05/2014   1.3  Jyoti  1350  1450  1400 NaN
854  Kalyani  05/05/2014  1.35  Jyoti  1350  1450  1400 NaN
855  Kalyani  06/05/2014  1.25  Jyoti  1400  1500  1450 NaN
856  Kalyani  07/05/2014   1.2  Jyoti  1400  1500  1450 NaN
857  Kalyani  08/05/2014   1.2  Jyoti  1400  1500  1450 NaN
858  Kalyani  09/05/2014  1.15  Jyoti  1400  1500  1450 NaN
859  Kalyani  10/05/2014   1.2  Jyoti  1350  1450  1400 NaN
860  Kalyani  13/05/2014   1.2  Jyoti  1400  1500  1450 NaN
861  Kalyani  14/05/2014  1.15  Jyoti  1400  1500  1450 NaN
862  Kalyani  15/05/2014  1.15  Jyoti  1400  1500  1450 NaN
863  Kalyani  16/05/2014   1.2  Jyoti  1400  1500  1450 NaN
864  Kalyani  17/05/2014  1.15  Jyoti  1400  1500  1450 NaN
865  Kalyani  19/05/2014   1.2  Jyoti  1400  1500  1450 NaN
866  Kalyani  20/05/2014  1.25  Jyoti  1400  1500  1450 NaN
867  Kalyani  21/05/2014   1.3  Jyoti  1400  1500  1450 NaN
868  Kalyani  22/05/2014  1.35  Jyoti  1400  1500  1450 NaN
869  Kalyani  23/05/2014   1.4  Jyoti  1400  1500  1450 NaN
870  Kalyani  24/05/2014   1.4  Jyoti  1400  1500  1450 NaN
871  Kalyani  26/05/2014  1.45  Jyoti  1400  1500  1450 NaN
872  Kalyani  27/05/2014   1.5  Jyoti  1400  1500  1450 NaN
873  Kalyani  28/05/2014  1.45  Jyoti  1400  1500  1450 NaN
874  Kalyani  29/05/2014   1.5  Jyoti  1400  1500  1450 NaN
875  Kalyani  30/05/2014   1.5  Jyoti  1400  1500  1450 NaN
876  Kalyani  31/05/2014  1.55  Jyoti  1400  1500  1450 NaN
           0           1     2      3     4     5     6   7
792  Kalyani  01/11/2014   1.5  Jyoti  1750  1850  1800 NaN
793  Kalyani  03/11/2014   1.5  Jyoti  1750  1850  1800 NaN
794  Kalyani  04/11/2014   1.5  Jyoti  1750  1850  1800 NaN
795  Kalyani  05/11/2014  1.45  Jyoti  1800  1900  1850 NaN
796  Kalyani  06/11/2014   1.5  Jyoti  1800  1900  1850 NaN
797  Kalyani  07/11/2014  1.45  Jyoti  1800  1900  1850 NaN
798  Kalyani  08/11/2014   1.5  Jyoti  1800  1900  1850 NaN
799  Kalyani  10/11/2014  1.45  Jyoti  1800  1900  1850 NaN
800  Kalyani  11/11/2014   1.5           NR    NR    NR NaN
801  Kalyani  12/11/2014   1.5  Jyoti  1800  1900  1850 NaN
802  Kalyani  13/11/2014   1.5  Jyoti  1800  1900  1850 NaN
803  Kalyani  14/11/2014   1.5  Jyoti  1800  1900  1850 NaN
804  Kalyani  15/11/2014  1.55  Jyoti  1800  1900  1850 NaN
805  Kalyani  17/11/2014   1.5  Jyoti  1800  1900  1850 NaN
806  Kalyani  18/11/2014   1.5  Jyoti  1800  1900  1850 NaN
807  Kalyani  19/11/2014  1.45  Jyoti  1900  2000  1950 NaN
808  Kalyani  20/11/2014   1.5  Jyoti  1900  2000  1950 NaN
809  Kalyani  21/11/2014   1.5  Jyoti  1900  2100  2000 NaN
810  Kalyani  22/11/2014   1.5  Jyoti  1900  2100  2000 NaN
811  Kalyani  24/11/2014   1.5  Jyoti  1900  2100  2000 NaN
812  Kalyani  25/11/2014  1.45  Jyoti  1900  2100  2000 NaN
813  Kalyani  26/11/2014   1.5  Jyoti  1900  2100  2000 NaN
814  Kalyani  27/11/2014  1.45  Jyoti  1900  2100  2000 NaN
815  Kalyani  28/11/2014   1.4  Jyoti  1900  2100  2000 NaN
816  Kalyani  29/11/2014  1.35  Jyoti  1900  2100  2000 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1     2      3     4     5     6   7
566  Kalyani  01/09/2014  1.45  Jyoti  1700  1800  1750 NaN
567  Kalyani  02/09/2014   1.5  Jyoti  1700  1800  1750 NaN
568  Kalyani  03/09/2014   1.4  Jyoti  1700  1800  1750 NaN
569  Kalyani  04/09/2014   1.5  Jyoti  1700  1800  1750 NaN
570  Kalyani  05/09/2014   1.5  Jyoti  1700  1800  1750 NaN
571  Kalyani  06/09/2014   1.4  Jyoti  1700  1800  1750 NaN
572  Kalyani  08/09/2014   1.5  Jyoti  1700  1800  1750 NaN
573  Kalyani  09/09/2014   1.4  Jyoti  1750  1850  1800 NaN
574  Kalyani  10/09/2014  1.45  Jyoti  1750  1850  1800 NaN
575  Kalyani  11/09/2014   1.4  Jyoti  1800  1900  1850 NaN
576  Kalyani  12/09/2014   1.4  Jyoti  1900  2000  1950 NaN
577  Kalyani  13/09/2014  1.45  Jyoti  1850  1950  1900 NaN
578  Kalyani  15/09/2014   1.5  Jyoti  1800  1900  1850 NaN
579  Kalyani  16/09/2014   1.5  Jyoti  1800  1900  1850 NaN
580  Kalyani  17/09/2014   1.5  Jyoti  1800  1900  1850 NaN
581  Kalyani  18/09/2014   1.5  Jyoti  1750  1850  1800 NaN
582  Kalyani  19/09/2014   1.5  Jyoti  1700  1800  1750 NaN
583  Kalyani  20/09/2014   1.5  Jyoti  1700  1800  1750 NaN
584  Kalyani  22/09/2014  1.45  Jyoti  1700  1800  1750 NaN
585  Kalyani  24/09/2014   1.5  Jyoti  1700  1800  1750 NaN
586  Kalyani  25/09/2014  1.45  Jyoti  1700  1800  1750 NaN
587  Kalyani  26/09/2014   1.5  Jyoti  1700  1800  1750 NaN
588  Kalyani  27/09/2014   1.4  Jyoti  1700  1800  1750 NaN
589  Kalyani  29/09/2014   1.5  Jyoti  1700  1800  1750 NaN
           0           1     2      3    4    5    6   7
885  Kalyani  01/04/2015   9.5  Jyoti  500  600  550 NaN
886  Kalyani  02/04/2015  9.45  Jyoti  500  600  550 NaN
887  Kalyani  03/04/2015   9.5  Jyoti  500  600  550 NaN
888  Kalyani  04/04/2015   9.4  Jyoti  500  600  550 NaN
889  Kalyani  06/04/2015   9.2  Jyoti  550  650  600 NaN
890  Kalyani  07/04/2015   9.3  Jyoti  550  650  600 NaN
891  Kalyani  08/04/2015   9.2  Jyoti  550  650  600 NaN
892  Kalyani  09/04/2015   9.5  Jyoti  550  650  600 NaN
893  Kalyani  10/04/2015    10  Jyoti  500  600  550 NaN
894  Kalyani  11/04/2015  10.2  Jyoti  500  600  550 NaN
895  Kalyani  13/04/2015  10.5  Jyoti  500  600  550 NaN
896  Kalyani  14/04/2015    11  Jyoti  500  600  550 NaN
897  Kalyani  15/04/2015  10.5  Jyoti  500  600  550 NaN
898  Kalyani  16/04/2015    11  Jyoti  500  600  550 NaN
899  Kalyani  17/04/2015  11.2  Jyoti  500  600  550 NaN
900  Kalyani  18/04/2015  11.5  Jyoti  500  600  550 NaN
901  Kalyani  20/04/2015    11  Jyoti  500  600  550 NaN
902  Kalyani  21/04/2015  10.5  Jyoti  500  600  550 NaN
903  Kalyani  22/04/2015    10  Jyoti  500  600  550 NaN
904  Kalyani  23/04/2015   9.5  Jyoti  500  600  550 NaN
905  Kalyani  24/04/2015   9.2  Jyoti  500  600  550 NaN
906  Kalyani  25/04/2015     9  Jyoti  500  600  550 NaN
907  Kalyani  27/04/2015   9.5          NR   NR   NR NaN
908  Kalyani  28/04/2015     9          NR   NR   NR NaN
909  Kalyani  29/04/2015   8.7  Jyoti  510  610  560 NaN
910  Kalyani  30/04/2015   8.5  Jyoti  540  600  580 NaN
            0           1    2      3    4    5    6   7
1005  Kalyani  03/08/2015    6  Jyoti  750  850  800 NaN
1006  Kalyani  04/08/2015  5.5  Jyoti  750  850  800 NaN
1007  Kalyani  05/08/2015  5.3  Jyoti  750  850  800 NaN
1008  Kalyani  06/08/2015    5  Jyoti  750  850  800 NaN
1009  Kalyani  07/08/2015  5.2  Jyoti  750  850  800 NaN
1010  Kalyani  08/08/2015  5.3  Jyoti  700  800  750 NaN
1011  Kalyani  10/08/2015  5.5  Jyoti  700  800  750 NaN
1012  Kalyani  11/08/2015    6  Jyoti  650  700  680 NaN
1013  Kalyani  12/08/2015  6.2  Jyoti  650  700  680 NaN
1014  Kalyani  13/08/2015  6.3  Jyoti  650  700  680 NaN
1015  Kalyani  14/08/2015  6.5  Jyoti  650  700  670 NaN
1016  Kalyani  17/08/2015  6.3  Jyoti  650  700  680 NaN
1017  Kalyani  18/08/2015    6  Jyoti  650  700  680 NaN
1018  Kalyani  19/08/2015  6.2          NR   NR   NR NaN
1019  Kalyani  20/08/2015  6.5          NR   NR   NR NaN
1020  Kalyani  21/08/2015  6.8  Jyoti  650  700  690 NaN
1021  Kalyani  24/08/2015    7  Jyoti  600  690  650 NaN
1022  Kalyani  25/08/2015  7.2  Jyoti  600  690  650 NaN
1023  Kalyani  31/08/2015  7.3  Jyoti  600  680  650 NaN

           0           1    2      3    4    5    6   7
984  Kalyani  01/12/2015  6.5  Jyoti  800  900  850 NaN
985  Kalyani  02/12/2015  6.7  Jyoti  800  900  850 NaN
986  Kalyani  03/12/2015  6.8  Jyoti  800  900  830 NaN
987  Kalyani  07/12/2015  6.5  Jyoti  800  900  850 NaN
988  Kalyani  08/12/2015  6.9  Jyoti  800  900  850 NaN
989  Kalyani  09/12/2015    7  Jyoti  800  900  850 NaN
990  Kalyani  10/12/2015  7.5  Jyoti  750  800  780 NaN
991  Kalyani  11/12/2015  7.6  Jyoti  750  800  780 NaN
992  Kalyani  14/12/2015  7.8  Jyoti  750  800  770 NaN
993  Kalyani  15/12/2015  7.9  Jyoti  750  800  760 NaN
994  Kalyani  16/12/2015  7.5  Jyoti  750  850  800 NaN
995  Kalyani  17/12/2015  7.3  Jyoti  750  850  800 NaN
996  Kalyani  28/12/2015    6  Jyoti  780  850  800 NaN
997  Kalyani  29/12/2015  5.7  Jyoti  780  850  800 NaN
998  Kalyani  31/12/2015  5.3  Jyoti  800  850  830 NaN
           0           1      2      3    4    5    6   7
911  Kalyani  02/02/2015   10.5  Jyoti  500  650  600 NaN
912  Kalyani  03/02/2015  10.55  Jyoti  500  650  600 NaN
913  Kalyani  04/02/2015   10.7  Jyoti  500  650  600 NaN
914  Kalyani  05/02/2015  10.75  Jyoti  500  650  600 NaN
915  Kalyani  06/02/2015   10.8  Jyoti  500  650  600 NaN
916  Kalyani  07/02/2015   10.9  Jyoti  500  650  600 NaN
917  Kalyani  09/02/2015   10.8  Jyoti  550  700  650 NaN
918  Kalyani  10/02/2015   10.5  Jyoti  550  700  650 NaN
919  Kalyani  11/02/2015     10  Jyoti  550  700  650 NaN
920  Kalyani  12/02/2015     10  Jyoti  550  650  600 NaN
921  Kalyani  13/02/2015    9.5  Jyoti  550  650  600 NaN
922  Kalyani  14/02/2015      9  Jyoti  550  650  600 NaN
923  Kalyani  16/02/2015    8.5  Jyoti  550  650  600 NaN
924  Kalyani  17/02/2015    8.3  Jyoti  550  650  600 NaN
925  Kalyani  18/02/2015    8.2  Jyoti  550  650  600 NaN
926  Kalyani  19/02/2015      8  Jyoti  550  650  600 NaN
927  Kalyani  20/02/2015    7.9  Jyoti  550  650  600 NaN
928  Kalyani  21/02/2015   7.85  Jyoti  550  650  600 NaN
929  Kalyani  23/02/2015    7.9  Jyoti  500  600  550 NaN
930  Kalyani  24/02/2015    7.8  Jyoti  500  600  550 NaN
931  Kalyani  25/02/2015    7.7  Jyoti  500  600  550 NaN
932  Kalyani  26/02/2015    7.5  Jyoti  550  650  600 NaN
933  Kalyani  27/02/2015   7.45          NR   NR   NR NaN
934  Kalyani  28/02/2015    7.4          NR   NR   NR NaN
           0           1     2      3    4     5     6   7
958  Kalyani  01/01/2015  1.65  Jyoti  900  1000   950 NaN
959  Kalyani  02/01/2015   1.7  Jyoti  950  1050  1000 NaN
960  Kalyani  03/01/2015   1.8  Jyoti  900  1050  1000 NaN
961  Kalyani  05/01/2015  1.85  Jyoti  900  1050  1000 NaN
962  Kalyani  06/01/2015   1.9  Jyoti  950  1100  1050 NaN
963  Kalyani  07/01/2015     2  Jyoti  900  1050  1000 NaN
964  Kalyani  08/01/2015   2.5  Jyoti  950  1050  1000 NaN
965  Kalyani  09/01/2015     3  Jyoti  850  1000   950 NaN
966  Kalyani  10/01/2015   3.5  Jyoti  850  1000   950 NaN
967  Kalyani  12/01/2015     4  Jyoti  850  1000   950 NaN
968  Kalyani  13/01/2015   4.5  Jyoti  800  1000   900 NaN
969  Kalyani  14/01/2015     5  Jyoti  700   900   850 NaN
970  Kalyani  15/01/2015   5.5  Jyoti  700   800   750 NaN
971  Kalyani  16/01/2015     6  Jyoti  650   800   700 NaN
972  Kalyani  17/01/2015   6.5  Jyoti  650   800   700 NaN
973  Kalyani  19/01/2015     7  Jyoti  650   800   700 NaN
974  Kalyani  20/01/2015   7.5  Jyoti  600   750   650 NaN
975  Kalyani  21/01/2015     8  Jyoti  600   700   650 NaN
976  Kalyani  22/01/2015   7.5  Jyoti  600   750   675 NaN
977  Kalyani  23/01/2015     7  Jyoti  600   750   675 NaN
978  Kalyani  24/01/2015   7.5  Jyoti  600   750   650 NaN
979  Kalyani  26/01/2015  7.55  Jyoti  600   700   650 NaN
980  Kalyani  27/01/2015     8  Jyoti  600   700   650 NaN
981  Kalyani  28/01/2015   8.5  Jyoti  600   750   700 NaN
982  Kalyani  29/01/2015     9  Jyoti  600   700   650 NaN
983  Kalyani  30/01/2015   9.5  Jyoti  600   700   675 NaN
984  Kalyani  31/01/2015    10  Jyoti  600   700   650 NaN
            0           1    2      3    4    5    6   7
977   Kalyani  02/07/2015  3.7  Jyoti  680  750  700 NaN
978   Kalyani  03/07/2015  3.5  Jyoti  690  750  700 NaN
979   Kalyani  04/07/2015  3.5  Jyoti  680  750  700 NaN
980   Kalyani  06/07/2015    4  Jyoti  650  750  700 NaN
981   Kalyani  07/07/2015  4.2  Jyoti  650  720  700 NaN
982   Kalyani  08/07/2015    4  Jyoti  670  750  700 NaN
983   Kalyani  09/07/2015  3.6  Jyoti  670  750  700 NaN
984   Kalyani  10/07/2015  3.8  Jyoti  680  750  700 NaN
985   Kalyani  13/07/2015  3.5  Jyoti  690  750  700 NaN
986   Kalyani  14/07/2015  3.3  Jyoti  680  750  700 NaN
987   Kalyani  15/07/2015  3.5  Jyoti  650  750  700 NaN
988   Kalyani  16/07/2015    4  Jyoti  650  750  700 NaN
989   Kalyani  17/07/2015  4.5  Jyoti  650  750  700 NaN
990   Kalyani  18/07/2015    5  Jyoti  650  750  700 NaN
991   Kalyani  20/07/2015  4.5  Jyoti  650  750  700 NaN
992   Kalyani  21/07/2015    5  Jyoti  650  750  700 NaN
993   Kalyani  22/07/2015  5.2  Jyoti  650  750  700 NaN
994   Kalyani  23/07/2015  5.5  Jyoti  650  750  700 NaN
995   Kalyani  24/07/2015  5.7  Jyoti  650  750  700 NaN
996   Kalyani  27/07/2015    6  Jyoti  600  700  650 NaN
997   Kalyani  28/07/2015  6.5  Jyoti  600  700  650 NaN
998   Kalyani  29/07/2015    6          NR   NR   NR NaN
999   Kalyani  30/07/2015  6.3  Jyoti  650  750  700 NaN
1000  Kalyani  31/07/2015  6.2  Jyoti  650  750  700 NaN
            0           1    2      3    4    5    6   7
1021  Kalyani  01/06/2015    3  Jyoti  650  700  680 NaN
1022  Kalyani  02/06/2015    3  Jyoti  650  700  680 NaN
1023  Kalyani  03/06/2015  3.5  Jyoti  650  700  680 NaN
1024  Kalyani  04/06/2015  3.2  Jyoti  650  700  690 NaN
1025  Kalyani  05/06/2015    3  Jyoti  650  700  690 NaN
1026  Kalyani  06/06/2015    3  Jyoti  650  700  690 NaN
1027  Kalyani  08/06/2015    3  Jyoti  650  700  690 NaN
1028  Kalyani  09/06/2015  3.2  Jyoti  650  700  680 NaN
1029  Kalyani  10/06/2015    3  Jyoti  650  700  690 NaN
1030  Kalyani  11/06/2015    3  Jyoti  680  700  690 NaN
1031  Kalyani  12/06/2015    3  Jyoti  680  750  700 NaN
1032  Kalyani  13/06/2015    3  Jyoti  680  750  700 NaN
1033  Kalyani  15/06/2015  3.2  Jyoti  680  750  700 NaN
1034  Kalyani  16/06/2015  3.5  Jyoti  690  750  700 NaN
1035  Kalyani  17/06/2015    3  Jyoti  680  740  700 NaN
1036  Kalyani  18/06/2015  3.2  Jyoti  690  750  700 NaN
1037  Kalyani  19/06/2015    3  Jyoti  690  750  700 NaN
1038  Kalyani  20/06/2015  3.3  Jyoti  690  750  700 NaN
1039  Kalyani  22/06/2015  3.5  Jyoti  690  750  700 NaN
1040  Kalyani  23/06/2015  3.5  Jyoti  660  720  700 NaN
1041  Kalyani  24/06/2015  3.6  Jyoti  680  750  700 NaN
1042  Kalyani  25/06/2015  3.5  Jyoti  680  750  700 NaN
1043  Kalyani  26/06/2015  3.2  Jyoti  700  750  725 NaN
1044  Kalyani  27/06/2015    3  Jyoti  700  750  725 NaN
1045  Kalyani  29/06/2015    3  Jyoti  700  750  730 NaN
           0           1     2      3    4    5    6   7
936  Kalyani  02/03/2015  7.35          NR   NR   NR NaN
937  Kalyani  06/03/2015     8  Jyoti  500  600  550 NaN
938  Kalyani  07/03/2015     8  Jyoti  500  600  550 NaN
939  Kalyani  09/03/2015   8.5  Jyoti  450  550  500 NaN
940  Kalyani  10/03/2015  8.55  Jyoti  450  550  500 NaN
941  Kalyani  11/03/2015   8.5  Jyoti  450  550  500 NaN
942  Kalyani  12/03/2015     9  Jyoti  400  500  450 NaN
943  Kalyani  16/03/2015   9.5  Jyoti  400  500  450 NaN
944  Kalyani  17/03/2015   9.6  Jyoti  400  500  450 NaN
945  Kalyani  18/03/2015   9.7  Jyoti  400  500  450 NaN
946  Kalyani  19/03/2015  9.65  Jyoti  400  500  450 NaN
947  Kalyani  20/03/2015   9.7  Jyoti  400  500  450 NaN
948  Kalyani  21/03/2015  9.72  Jyoti  400  500  450 NaN
949  Kalyani  23/03/2015  9.75  Jyoti  400  500  450 NaN
950  Kalyani  24/03/2015   9.7  Jyoti  450  550  500 NaN
951  Kalyani  25/03/2015  9.65  Jyoti  500  600  550 NaN
952  Kalyani  26/03/2015  9.62  Jyoti  500  600  550 NaN
953  Kalyani  27/03/2015   9.6  Jyoti  500  600  550 NaN
954  Kalyani  28/03/2015   9.5  Jyoti  550  650  600 NaN
955  Kalyani  30/03/2015   9.3  Jyoti  550  650  600 NaN
956  Kalyani  31/03/2015   9.2  Jyoti  550  650  600 NaN
           0           1    2      3    4    5    6   7
933  Kalyani  01/05/2015    8  Jyoti  540  600  580 NaN
934  Kalyani  02/05/2015  7.6  Jyoti  550  650  600 NaN
935  Kalyani  04/05/2015  7.5  Jyoti  550  650  600 NaN
936  Kalyani  05/05/2015    7  Jyoti  550  650  600 NaN
937  Kalyani  06/05/2015  6.9  Jyoti  550  650  600 NaN
938  Kalyani  07/05/2015  6.5  Jyoti  550  650  600 NaN
939  Kalyani  08/05/2015    6  Jyoti  550  650  600 NaN
940  Kalyani  09/05/2015  5.6  Jyoti  550  650  600 NaN
941  Kalyani  11/05/2015    5  Jyoti  560  680  650 NaN
942  Kalyani  12/05/2015    5  Jyoti  600  680  650 NaN
943  Kalyani  13/05/2015  4.5  Jyoti  600  680  650 NaN
944  Kalyani  14/05/2015  4.2  Jyoti  600  680  650 NaN
945  Kalyani  15/05/2015    4  Jyoti  600  680  650 NaN
946  Kalyani  16/05/2015    4  Jyoti  600  680  650 NaN
947  Kalyani  18/05/2015  3.5  Jyoti  650  700  660 NaN
948  Kalyani  19/05/2015  3.2  Jyoti  650  700  680 NaN
949  Kalyani  20/05/2015    3  Jyoti  650  700  680 NaN
950  Kalyani  21/05/2015  3.5  Jyoti  650  700  680 NaN
951  Kalyani  25/05/2015    3  Jyoti  650  700  690 NaN
952  Kalyani  26/05/2015    3  Jyoti  650  700  690 NaN
953  Kalyani  27/05/2015    3  Jyoti  650  700  690 NaN
954  Kalyani  28/05/2015  3.5  Jyoti  650  700  680 NaN
955  Kalyani  29/05/2015  3.2  Jyoti  650  700  680 NaN
956  Kalyani  30/05/2015    3  Jyoti  650  700  690 NaN

           0           1    2      3    4     5    6   7
877  Kalyani  02/11/2015  6.2  Jyoti  750   850  800 NaN
878  Kalyani  03/11/2015    6  Jyoti  800   900  850 NaN
879  Kalyani  04/11/2015  5.9  Jyoti  800   900  850 NaN
880  Kalyani  05/11/2015    6  Jyoti  750   850  800 NaN
881  Kalyani  06/11/2015    6  Jyoti  750   850  800 NaN
882  Kalyani  09/11/2015    6  Jyoti  800   900  850 NaN
883  Kalyani  16/11/2015    6  Jyoti  880   930  900 NaN
884  Kalyani  17/11/2015  6.2  Jyoti  880   930  900 NaN
885  Kalyani  18/11/2015    6  Jyoti  860   910  900 NaN
886  Kalyani  19/11/2015    6  Jyoti  880   950  920 NaN
887  Kalyani  20/11/2015   10  Jyoti  900  1000  950 NaN
888  Kalyani  23/11/2015    6  Jyoti  900   960  950 NaN
889  Kalyani  24/11/2015    6  Jyoti  900   960  950 NaN
890  Kalyani  25/11/2015    6  Jyoti  900   970  950 NaN
891  Kalyani  26/11/2015  5.8  Jyoti  900   970  950 NaN
892  Kalyani  27/11/2015    6  Jyoti  900   950  930 NaN
893  Kalyani  30/11/2015  6.3  Jyoti  850   900  880 NaN
           0           1    2      3    4    5    6   7
868  Kalyani  01/10/2015  7.6  Jyoti  630  710  700 NaN
869  Kalyani  02/10/2015  7.6  Jyoti  610  680  670 NaN
870  Kalyani  03/10/2015  7.5  Jyoti  610  680  670 NaN
871  Kalyani  05/10/2015  7.6  Jyoti  620  690  680 NaN
872  Kalyani  06/10/2015  7.5  Jyoti  620  690  680 NaN
873  Kalyani  07/10/2015  7.3  Jyoti  620  690  670 NaN
874  Kalyani  08/10/2015  7.5  Jyoti  610  680  650 NaN
875  Kalyani  09/10/2015  7.6  Jyoti  610  680  650 NaN
876  Kalyani  12/10/2015  7.7  Jyoti  610  690  655 NaN
877  Kalyani  13/10/2015  7.5  Jyoti  600  690  660 NaN
878  Kalyani  14/10/2015  7.6  Jyoti  600  690  660 NaN
879  Kalyani  15/10/2015  7.5  Jyoti  600  690  660 NaN
880  Kalyani  16/10/2015  7.6  Jyoti  600  690  650 NaN
881  Kalyani  27/10/2015  7.2  Jyoti  680  750  700 NaN
882  Kalyani  28/10/2015    7  Jyoti  680  750  700 NaN
883  Kalyani  29/10/2015  6.9  Jyoti  680  760  720 NaN
884  Kalyani  30/10/2015  6.8  Jyoti  680  760  720 NaN
           0           1    2      3    4    5    6   7
971  Kalyani  01/09/2015  6.8  Jyoti  650  720  680 NaN
972  Kalyani  03/09/2015    7  Jyoti  650  750  700 NaN
973  Kalyani  04/09/2015  7.3  Jyoti  650  750  700 NaN
974  Kalyani  05/09/2015  7.5  Jyoti  650  750  700 NaN
975  Kalyani  07/09/2015    8  Jyoti  650  700  680 NaN
976  Kalyani  08/09/2015  8.3  Jyoti  650  700  680 NaN
977  Kalyani  09/09/2015  8.5  Jyoti  650  700  680 NaN
978  Kalyani  10/09/2015  8.8  Jyoti  620  700  680 NaN
979  Kalyani  11/09/2015    9  Jyoti  620  700  680 NaN
980  Kalyani  12/09/2015  9.3  Jyoti  630  700  680 NaN
981  Kalyani  14/09/2015  9.5  Jyoti  620  700  670 NaN
982  Kalyani  17/09/2015    8  Jyoti  650  750  700 NaN
983  Kalyani  18/09/2015  7.6  Jyoti  650  750  700 NaN
984  Kalyani  21/09/2015  7.8  Jyoti  650  750  700 NaN
985  Kalyani  22/09/2015    8  Jyoti  640  730  690 NaN
986  Kalyani  23/09/2015  8.3  Jyoti  630  710  690 NaN
987  Kalyani  24/09/2015  8.5  Jyoti  630  700  680 NaN
988  Kalyani  28/09/2015  8.2  Jyoti  650  720  700 NaN
989  Kalyani  29/09/2015    8  Jyoti  650  730  700 NaN
           0           1     2      3     4     5     6   7
894  Kalyani  03/04/2016   4.1  Jyoti  1250  1500  1400 NaN
895  Kalyani  04/04/2016     4  Jyoti  1250  1500  1400 NaN
896  Kalyani  05/04/2016     4  Jyoti  1250  1500  1400 NaN
897  Kalyani  06/04/2016   4.1  Jyoti  1250  1500  1400 NaN
898  Kalyani  07/04/2016     4  Jyoti  1250  1500  1400 NaN
899  Kalyani  08/04/2016     4           NR    NR    NR NaN
900  Kalyani  09/04/2016   3.9  Jyoti  1250  1500  1400 NaN
901  Kalyani  10/04/2016   3.8  Jyoti  1250  1500  1400 NaN
902  Kalyani  11/04/2016  3.85  Jyoti  1250  1500  1400 NaN
903  Kalyani  12/04/2016   3.8           NR    NR    NR NaN
904  Kalyani  13/04/2016   3.8  Jyoti  1250  1500  1400 NaN
905  Kalyani  14/04/2016   3.9  Jyoti  1250  1500  1400 NaN
906  Kalyani  15/04/2016     4  Jyoti  1250  1450  1350 NaN
907  Kalyani  17/04/2016   3.9  Jyoti  1300  1400  1350 NaN
908  Kalyani  18/04/2016   3.7  Jyoti  1400  1500  1450 NaN
909  Kalyani  19/04/2016   3.6  Jyoti  1400  1500  1450 NaN
910  Kalyani  24/04/2016   3.8  Jyoti  1400  1600  1500 NaN
911  Kalyani  25/04/2016   3.9  Jyoti  1400  1600  1500 NaN
912  Kalyani  26/04/2016     4  Jyoti  1400  1600  1500 NaN
913  Kalyani  27/04/2016   4.2  Jyoti  1450  1650  1550 NaN
914  Kalyani  28/04/2016   3.5  Jyoti  1600  1700  1650 NaN
915  Kalyani  29/04/2016   3.5  Jyoti  1600  1700  1650 NaN
           0           1    2      3     4     5     6   7
965  Kalyani  01/08/2016  2.2  Jyoti  1700  1800  1760 NaN
966  Kalyani  02/08/2016  2.3  Jyoti  1720  1820  1780 NaN
967  Kalyani  03/08/2016  2.3  Jyoti  1720  1820  1780 NaN
968  Kalyani  04/08/2016  2.4  Jyoti  1720  1800  1780 NaN
969  Kalyani  05/08/2016  2.5  Jyoti  1720  1800  1780 NaN
970  Kalyani  08/08/2016  2.5  Jyoti  1700  1800  1720 NaN
971  Kalyani  09/08/2016  2.6  Jyoti  1700  1800  1730 NaN
972  Kalyani  10/08/2016  2.5  Jyoti  1700  1800  1750 NaN
973  Kalyani  11/08/2016  2.7  Jyoti  1700  1800  1750 NaN
974  Kalyani  12/08/2016  2.6  Jyoti  1700  1800  1750 NaN
975  Kalyani  15/08/2016  2.8  Jyoti  1700  1800  1750 NaN
976  Kalyani  16/08/2016    3  Jyoti  1650  1750  1700 NaN
977  Kalyani  17/08/2016  3.1  Jyoti  1650  1750  1700 NaN
978  Kalyani  22/08/2016    3  Jyoti  1650  1750  1700 NaN
979  Kalyani  23/08/2016  3.1  Jyoti  1660  1760  1710 NaN
980  Kalyani  24/08/2016    3  Jyoti  1660  1760  1700 NaN
981  Kalyani  25/08/2016  3.1  Jyoti  1650  1750  1700 NaN
982  Kalyani  26/08/2016    3  Jyoti  1650  1750  1700 NaN
983  Kalyani  29/08/2016  3.1  Jyoti  1650  1750  1700 NaN
984  Kalyani  30/08/2016    3  Jyoti  1660  1760  1700 NaN
            0           1    2      3     4     5     6   7
991   Kalyani  01/12/2016  3.5  Jyoti  1000  1300  1200 NaN
992   Kalyani  02/12/2016  3.6  Jyoti  1000  1300  1200 NaN
993   Kalyani  05/12/2016  3.7  Jyoti   700   900   800 NaN
994   Kalyani  06/12/2016  3.8  Jyoti   700   900   800 NaN
995   Kalyani  07/12/2016    4  Jyoti   700   900   800 NaN
996   Kalyani  08/12/2016  4.2  Jyoti   700   900   800 NaN
997   Kalyani  09/12/2016  4.5  Jyoti   650   850   750 NaN
998   Kalyani  12/12/2016  4.5  Jyoti   650   850   750 NaN
999   Kalyani  13/12/2016  4.6  Jyoti   600   800   700 NaN
1000  Kalyani  14/12/2016  4.3  Jyoti   600   800   700 NaN
1001  Kalyani  15/12/2016  4.2  Jyoti   600   800   700 NaN
1002  Kalyani  16/12/2016  4.1  Jyoti   600   800   700 NaN
1003  Kalyani  19/12/2016  3.9  Jyoti   550   750   650 NaN
1004  Kalyani  20/12/2016  3.7  Jyoti   550   750   650 NaN
1005  Kalyani  21/12/2016  3.5  Jyoti   550   750   650 NaN
1006  Kalyani  22/12/2016  3.4  Jyoti   550   800   650 NaN
1007  Kalyani  23/12/2016  3.5  Jyoti   560   800   650 NaN
1008  Kalyani  26/12/2016  3.4  Jyoti   560   800   650 NaN
1009  Kalyani  27/12/2016  3.5  Jyoti   560   750   650 NaN
1010  Kalyani  28/12/2016  3.5  Jyoti   500   700   600 NaN
           0           1    2      3    4    5    6   7
881  Kalyani  01/02/2016    7  Jyoti  620  700  680 NaN
882  Kalyani  02/02/2016  7.2  Jyoti  650  750  700 NaN
883  Kalyani  03/02/2016  7.3  Jyoti  650  750  700 NaN
884  Kalyani  04/02/2016  7.5  Jyoti  650  750  700 NaN
885  Kalyani  08/02/2016  7.8  Jyoti  650  750  700 NaN
886  Kalyani  09/02/2016  7.6  Jyoti  660  760  710 NaN
887  Kalyani  10/02/2016  7.5  Jyoti  660  760  715 NaN
888  Kalyani  11/02/2016  7.3  Jyoti  670  780  720 NaN
889  Kalyani  12/02/2016  7.5  Jyoti  650  750  700 NaN
890  Kalyani  15/02/2016  7.6  Jyoti  650  750  700 NaN
891  Kalyani  16/02/2016  7.5  Jyoti  660  750  700 NaN
892  Kalyani  17/02/2016  7.4  Jyoti  660  750  700 NaN
893  Kalyani  18/02/2016  7.2  Jyoti  690  780  720 NaN
894  Kalyani  19/02/2016    7          NR   NR   NR NaN
895  Kalyani  22/02/2016  6.5  Jyoti  800  900  850 NaN
896  Kalyani  23/02/2016  6.2  Jyoti  820  950  900 NaN
897  Kalyani  24/02/2016  6.1  Jyoti  820  950  900 NaN
898  Kalyani  25/02/2016    6  Jyoti  830  960  910 NaN
            0           1    2      3    4    5    6   7
989   Kalyani  04/01/2016    5  Jyoti  850  950  900 NaN
990   Kalyani  05/01/2016  5.1  Jyoti  850  950  900 NaN
991   Kalyani  06/01/2016    5  Jyoti  870  950  900 NaN
992   Kalyani  07/01/2016  5.2  Jyoti  800  900  870 NaN
993   Kalyani  08/01/2016    5  Jyoti  850  950  900 NaN
994   Kalyani  19/01/2016  5.3  Jyoti  800  900  850 NaN
995   Kalyani  20/01/2016  5.5  Jyoti  800  900  850 NaN
996   Kalyani  21/01/2016  5.6  Jyoti  800  900  850 NaN
997   Kalyani  22/01/2016    6  Jyoti  760  850  800 NaN
998   Kalyani  25/01/2016  6.2          NR   NR   NR NaN
999   Kalyani  27/01/2016  6.5          NR   NR   NR NaN
1000  Kalyani  28/01/2016  6.5  Jyoti  650  750  700 NaN
1001  Kalyani  29/01/2016  6.6  Jyoti  650  750  700 NaN

           0           1    2      3     4     5     6   7
974  Kalyani  01/07/2016  3.5  Jyoti  1560  1680  1640 NaN
975  Kalyani  07/07/2016  3.2  Jyoti  1650  1760  1740 NaN
976  Kalyani  08/07/2016    3  Jyoti  1680  1780  1750 NaN
977  Kalyani  09/07/2016    3  Jyoti  1660  1760  1740 NaN
978  Kalyani  11/07/2016    3  Jyoti  1680  1780  1750 NaN
979  Kalyani  13/07/2016  3.1  Jyoti  1660  1780  1740 NaN
980  Kalyani  14/07/2016    3  Jyoti  1660  1780  1740 NaN
981  Kalyani  15/07/2016  3.2  Jyoti  1680  1780  1750 NaN
982  Kalyani  18/07/2016    3  Jyoti  1670  1780  1750 NaN
983  Kalyani  19/07/2016  3.1  Jyoti  1660  1780  1740 NaN
984  Kalyani  20/07/2016    3  Jyoti  1660  1780  1740 NaN
985  Kalyani  21/07/2016    3  Jyoti  1680  1800  1760 NaN
986  Kalyani  22/07/2016  2.8  Jyoti  1680  1800  1760 NaN
987  Kalyani  25/07/2016  2.7  Jyoti  1680  1800  1760 NaN
988  Kalyani  26/07/2016  2.6  Jyoti  1680  1800  1760 NaN
989  Kalyani  27/07/2016  2.5  Jyoti  1680  1800  1760 NaN
990  Kalyani  28/07/2016  2.4  Jyoti  1700  1820  1780 NaN
            0           1    2      3     4     5     6   7
987   Kalyani  01/06/2016  2.6  Jyoti  1580  1700  1650 NaN
988   Kalyani  02/06/2016  2.5  Jyoti  1580  1700  1650 NaN
989   Kalyani  03/06/2016  2.6  Jyoti  1560  1680  1620 NaN
990   Kalyani  06/06/2016  2.7  Jyoti  1550  1650  1600 NaN
991   Kalyani  09/06/2016  2.8  Jyoti  1550  1650  1600 NaN
992   Kalyani  10/06/2016    3  Jyoti  1560  1660  1620 NaN
993   Kalyani  13/06/2016    3  Jyoti  1550  1650  1620 NaN
994   Kalyani  14/06/2016  3.2  Jyoti  1550  1650  1620 NaN
995   Kalyani  15/06/2016    3  Jyoti  1560  1660  1630 NaN
996   Kalyani  16/06/2016    3  Jyoti  1560  1670  1630 NaN
997   Kalyani  20/06/2016  3.1  Jyoti  1570  1680  1630 NaN
998   Kalyani  21/06/2016    3  Jyoti  1570  1680  1630 NaN
999   Kalyani  22/06/2016    3  Jyoti  1570  1680  1630 NaN
1000  Kalyani  23/06/2016  3.2  Jyoti  1580  1680  1640 NaN
1001  Kalyani  24/06/2016    3  Jyoti  1570  1680  1630 NaN
1002  Kalyani  27/06/2016  3.3  Jyoti  1580  1680  1640 NaN
1003  Kalyani  28/06/2016  3.5  Jyoti  1580  1680  1640 NaN
1004  Kalyani  29/06/2016  3.6  Jyoti  1560  1660  1620 NaN
           0           1    2      3     4     5     6   7
957  Kalyani  01/03/2016  5.5  Jyoti   870   980   950 NaN
958  Kalyani  02/03/2016  5.4  Jyoti   880   990   960 NaN
959  Kalyani  03/03/2016  5.3  Jyoti   900  1000   970 NaN
960  Kalyani  04/03/2016  5.2  Jyoti   900  1050  1000 NaN
961  Kalyani  10/03/2016  5.5  Jyoti  1040  1240  1140 NaN
962  Kalyani  11/03/2016  5.4  Jyoti  1050  1250  1150 NaN
963  Kalyani  14/03/2016  5.1  Jyoti  1050  1250  1150 NaN
964  Kalyani  15/03/2016    5  Jyoti  1100  1300  1200 NaN
965  Kalyani  16/03/2016  5.1  Jyoti  1100  1300  1200 NaN
966  Kalyani  17/03/2016    5  Jyoti  1100  1350  1250 NaN
967  Kalyani  18/03/2016    5  Jyoti  1150  1400  1300 NaN
968  Kalyani  21/03/2016  4.9  Jyoti  1150  1420  1320 NaN
969  Kalyani  22/03/2016    5  Jyoti  1150  1400  1250 NaN
           0           1    2      3     4     5     6   7
910  Kalyani  02/05/2016  3.2  Jyoti  1650  1800  1700 NaN
911  Kalyani  03/05/2016  3.1  Jyoti  1675  1850  1750 NaN
912  Kalyani  04/05/2016  3.3  Jyoti  1600  1800  1700 NaN
913  Kalyani  05/05/2016    3  Jyoti  1600  1800  1700 NaN
914  Kalyani  06/05/2016    3  Jyoti  1600  1800  1700 NaN
915  Kalyani  09/05/2016  2.8  Jyoti  1650  1850  1750 NaN
916  Kalyani  10/05/2016    3  Jyoti  1600  1700  1650 NaN
917  Kalyani  11/05/2016    3  Jyoti  1600  1700  1650 NaN
918  Kalyani  12/05/2016  2.8  Jyoti  1620  1750  1700 NaN
919  Kalyani  13/05/2016    3  Jyoti  1600  1730  1680 NaN
920  Kalyani  16/05/2016  2.8  Jyoti  1650  1750  1700 NaN
921  Kalyani  17/05/2016  2.7  Jyoti  1650  1750  1700 NaN
922  Kalyani  18/05/2016  2.6  Jyoti  1650  1750  1700 NaN
923  Kalyani  19/05/2016  2.5  Jyoti  1650  1750  1700 NaN
924  Kalyani  20/05/2016  2.6  Jyoti  1650  1750  1700 NaN
925  Kalyani  23/05/2016  2.6  Jyoti  1650  1750  1700 NaN
926  Kalyani  24/05/2016  2.5  Jyoti  1600  1700  1650 NaN
927  Kalyani  25/05/2016  2.4  Jyoti  1600  1700  1650 NaN
928  Kalyani  26/05/2016  2.5  Jyoti  1630  1720  1680 NaN
929  Kalyani  27/05/2016  2.4  Jyoti  1650  1750  1700 NaN
930  Kalyani  30/05/2016  2.6  Jyoti  1620  1710  1660 NaN
931  Kalyani  31/05/2016  2.5  Jyoti  1620  1710  1660 NaN
           0           1    2      3     4     5     6   7
963  Kalyani  01/11/2016  3.5  Jyoti  1480  1600  1550 NaN
964  Kalyani  02/11/2016  3.6  Jyoti  1480  1600  1550 NaN
965  Kalyani  03/11/2016  3.7  Jyoti  1500  1600  1550 NaN
966  Kalyani  04/11/2016  3.8  Jyoti  1500  1600  1550 NaN
967  Kalyani  05/11/2016  3.7  Jyoti  1500  1600  1550 NaN
968  Kalyani  07/11/2016  3.8  Jyoti  1500  1600  1550 NaN
969  Kalyani  08/11/2016  3.9  Jyoti  1500  1600  1550 NaN
970  Kalyani  09/11/2016  3.8  Jyoti  1500  1600  1550 NaN
971  Kalyani  10/11/2016  3.7  Jyoti  1500  1600  1550 NaN
972  Kalyani  11/11/2016  3.6  Jyoti  1500  1600  1550 NaN
973  Kalyani  12/11/2016  3.7  Jyoti  1500  1600  1550 NaN
974  Kalyani  14/11/2016  3.6  Jyoti  1500  1600  1550 NaN
975  Kalyani  15/11/2016  3.5  Jyoti  1400  1500  1450 NaN
976  Kalyani  16/11/2016  3.4  Jyoti  1350  1450  1400 NaN
977  Kalyani  17/11/2016  3.3  Jyoti  1350  1450  1400 NaN
978  Kalyani  18/11/2016  3.2  Jyoti  1350  1450  1400 NaN
979  Kalyani  21/11/2016  3.1  Jyoti  1400  1500  1450 NaN
980  Kalyani  22/11/2016  3.2  Jyoti  1400  1500  1450 NaN
981  Kalyani  23/11/2016  3.1           NR    NR    NR NaN
982  Kalyani  24/11/2016    3           NR    NR    NR NaN
983  Kalyani  25/11/2016  2.9           NR    NR    NR NaN
984  Kalyani  28/11/2016  2.7  Jyoti  1300  1400  1350 NaN
985  Kalyani  29/11/2016  2.8  Jyoti  1300  1400  1350 NaN
           0           1    2      3     4     5     6   7
968  Kalyani  03/10/2016    3  Jyoti  1550  1650  1600 NaN
969  Kalyani  17/10/2016    3  Jyoti  1600  1700  1650 NaN
970  Kalyani  18/10/2016  3.1  Jyoti  1600  1700  1650 NaN
971  Kalyani  19/10/2016  3.2  Jyoti  1610  1720  1680 NaN
972  Kalyani  20/10/2016  3.4  Jyoti  1620  1730  1690 NaN
973  Kalyani  21/10/2016  3.5  Jyoti  1610  1700  1660 NaN
974  Kalyani  24/10/2016  3.4  Jyoti  1600  1700  1650 NaN
975  Kalyani  25/10/2016  3.5  Jyoti  1600  1700  1650 NaN
976  Kalyani  26/10/2016  3.6  Jyoti  1600  1700  1650 NaN
           0           1    2      3     4     5     6   7
978  Kalyani  01/09/2016  3.1  Jyoti  1660  1760  1700 NaN
979  Kalyani  02/09/2016    3  Jyoti  1660  1760  1700 NaN
980  Kalyani  05/09/2016  3.2  Jyoti  1650  1750  1700 NaN
981  Kalyani  06/09/2016    3  Jyoti  1650  1750  1700 NaN
982  Kalyani  07/09/2016  3.2  Jyoti  1650  1750  1700 NaN
983  Kalyani  09/09/2016  3.3  Jyoti  1660  1760  1700 NaN
984  Kalyani  12/09/2016  3.3  Jyoti  1660  1760  1700 NaN
985  Kalyani  14/09/2016  3.2  Jyoti  1650  1750  1700 NaN
986  Kalyani  15/09/2016  3.1  Jyoti  1660  1760  1700 NaN
987  Kalyani  16/09/2016  3.2  Jyoti  1660  1760  1700 NaN
988  Kalyani  21/09/2016  3.1  Jyoti  1630  1730  1680 NaN
989  Kalyani  22/09/2016  3.1  Jyoti  1620  1720  1680 NaN
990  Kalyani  23/09/2016  3.1  Jyoti  1620  1720  1680 NaN
991  Kalyani  27/09/2016  3.1  Jyoti  1600  1700  1660 NaN
992  Kalyani  28/09/2016  3.2  Jyoti  1600  1700  1650 NaN
993  Kalyani  29/09/2016  3.1  Jyoti  1600  1700  1650 NaN
            0           1     2      3    4    5    6   7
1006  Kalyani  03/04/2017   5.9  Jyoti  480  530  500 NaN
1007  Kalyani  04/04/2017   5.6  Jyoti  490  550  520 NaN
1008  Kalyani  10/04/2017  5.65  Jyoti  500  600  550 NaN
1009  Kalyani  11/04/2017   5.5  Jyoti  510  600  560 NaN
1010  Kalyani  12/04/2017   5.4  Jyoti  510  610  560 NaN
1011  Kalyani  13/04/2017  5.45  Jyoti  510  610  560 NaN
1012  Kalyani  14/04/2017   5.3  Jyoti  520  620  570 NaN
1013  Kalyani  17/04/2017   5.4  Jyoti  550  700  650 NaN
1014  Kalyani  18/04/2017  5.45  Jyoti  550  710  650 NaN
1015  Kalyani  19/04/2017   5.5  Jyoti  550  700  650 NaN
1016  Kalyani  20/04/2017   5.4  Jyoti  560  760  660 NaN
1017  Kalyani  21/04/2017  5.45  Jyoti  570  770  670 NaN
1018  Kalyani  24/04/2017   5.5  Jyoti  570  770  670 NaN
1019  Kalyani  25/04/2017  5.55  Jyoti  560  760  660 NaN
1020  Kalyani  26/04/2017   5.6  Jyoti  560  760  660 NaN
1021  Kalyani  27/04/2017   5.5  Jyoti  560  760  660 NaN
1022  Kalyani  28/04/2017   5.3  Jyoti  550  750  650 NaN
1023  Kalyani  29/04/2017   5.2  Jyoti  560  750  660 NaN

            0           1    2      3    4    5    6   7
1056  Kalyani  01/08/2017    5  Jyoti  680  750  720 NaN
1057  Kalyani  02/08/2017  5.2  Jyoti  700  780  740 NaN
1058  Kalyani  03/08/2017  5.3  Jyoti  700  780  740 NaN
1059  Kalyani  04/08/2017  5.2  Jyoti  700  780  740 NaN
1060  Kalyani  07/08/2017    5  Jyoti  700  780  740 NaN
1061  Kalyani  08/08/2017  5.1  Jyoti  700  780  740 NaN
1062  Kalyani  09/08/2017  5.5  Jyoti  650  750  700 NaN
1063  Kalyani  10/08/2017  5.6  Jyoti  650  740  700 NaN
1064  Kalyani  11/08/2017  5.5  Jyoti  650  740  700 NaN
1065  Kalyani  14/08/2017  5.4  Jyoti  650  710  690 NaN
1066  Kalyani  15/08/2017  5.4  Jyoti  650  710  690 NaN
1067  Kalyani  16/08/2017  5.6  Jyoti  630  700  680 NaN
1068  Kalyani  17/08/2017  5.5  Jyoti  630  700  690 NaN
1069  Kalyani  18/08/2017  5.4  Jyoti  630  700  690 NaN
1070  Kalyani  21/08/2017  5.5  Jyoti  630  700  690 NaN
1071  Kalyani  22/08/2017  5.6  Jyoti  630  700  680 NaN
1072  Kalyani  23/08/2017  5.5  Jyoti  650  710  690 NaN
1073  Kalyani  24/08/2017  5.6  Jyoti  650  710  690 NaN
1074  Kalyani  25/08/2017  5.5  Jyoti  640  700  680 NaN
1075  Kalyani  28/08/2017  5.3  Jyoti  660  710  700 NaN
1076  Kalyani  29/08/2017  5.2  Jyoti  660  720  700 NaN
            0           1    2      3    4    5    6   7
1144  Kalyani  04/12/2017  3.5  Jyoti  680  750  700 NaN
1145  Kalyani  05/12/2017  3.6  Jyoti  680  750  700 NaN
1146  Kalyani  07/12/2017  3.5  Jyoti  680  750  700 NaN
1147  Kalyani  08/12/2017  3.6  Jyoti  680  750  700 NaN
1148  Kalyani  13/12/2017  3.6  Jyoti  680  750  700 NaN
1149  Kalyani  14/12/2017  3.6  Jyoti  680  750  700 NaN
1150  Kalyani  15/12/2017  3.6  Jyoti  680  750  700 NaN
1151  Kalyani  18/12/2017  3.7  Jyoti  680  750  700 NaN
1152  Kalyani  19/12/2017  3.6  Jyoti  680  750  700 NaN
1153  Kalyani  20/12/2017  3.7  Jyoti  680  750  700 NaN
1154  Kalyani  21/12/2017  3.6  Jyoti  650  750  700 NaN
1155  Kalyani  22/12/2017  3.5  Jyoti  650  750  700 NaN
1156  Kalyani  27/12/2017  3.5  Jyoti  650  750  700 NaN
            0           1     2      3    4    5    6   7
984   Kalyani  01/02/2017   5.1  Jyoti  450  550  500 NaN
985   Kalyani  02/02/2017   5.2  Jyoti  450  550  500 NaN
986   Kalyani  03/02/2017  5.25  Jyoti  450  550  500 NaN
987   Kalyani  06/02/2017   5.3  Jyoti  450  550  500 NaN
988   Kalyani  07/02/2017   5.4  Jyoti  400  500  450 NaN
989   Kalyani  08/02/2017   5.5  Jyoti  400  500  450 NaN
990   Kalyani  09/02/2017   5.6  Jyoti  380  460  420 NaN
991   Kalyani  10/02/2017  5.65  Jyoti  350  450  400 NaN
992   Kalyani  15/02/2017   5.8  Jyoti  300  400  350 NaN
993   Kalyani  16/02/2017     6  Jyoti  300  400  350 NaN
994   Kalyani  17/02/2017   6.1  Jyoti  300  400  350 NaN
995   Kalyani  20/02/2017   6.2  Jyoti  300  400  350 NaN
996   Kalyani  21/02/2017   6.5  Jyoti  250  350  300 NaN
997   Kalyani  22/02/2017   6.7  Jyoti  250  350  300 NaN
998   Kalyani  23/02/2017   6.8  Jyoti  250  350  300 NaN
999   Kalyani  27/02/2017   6.5  Jyoti  380  450  400 NaN
1000  Kalyani  28/02/2017   6.4  Jyoti  300  400  350 NaN
            0           1    2      3    4    5    6   7
1082  Kalyani  02/01/2017  3.5  Jyoti  550  650  600 NaN
1083  Kalyani  03/01/2017  3.5  Jyoti  550  650  600 NaN
1084  Kalyani  04/01/2017  3.6  Jyoti  500  600  550 NaN
1085  Kalyani  05/01/2017  3.7  Jyoti  500  600  550 NaN
1086  Kalyani  06/01/2017  3.8  Jyoti  500  600  550 NaN
1087  Kalyani  09/01/2017  3.9  Jyoti  500  600  550 NaN
1088  Kalyani  10/01/2017  3.8  Jyoti  500  600  550 NaN
1089  Kalyani  11/01/2017  3.7  Jyoti  500  600  550 NaN
1090  Kalyani  12/01/2017  3.8  Jyoti  500  600  550 NaN
1091  Kalyani  13/01/2017  3.9  Jyoti  500  600  550 NaN
1092  Kalyani  16/01/2017    4  Jyoti  450  550  500 NaN
1093  Kalyani  17/01/2017  4.1  Jyoti  450  540  500 NaN
1094  Kalyani  18/01/2017  4.2  Jyoti  450  550  500 NaN
1095  Kalyani  19/01/2017  4.3  Jyoti  400  500  450 NaN
1096  Kalyani  20/01/2017  4.4  Jyoti  400  500  450 NaN
1097  Kalyani  23/01/2017  4.5  Jyoti  400  500  450 NaN
1098  Kalyani  24/01/2017  4.6  Jyoti  400  500  450 NaN
1099  Kalyani  25/01/2017  4.7  Jyoti  400  500  450 NaN
1100  Kalyani  27/01/2017  4.8  Jyoti  450  550  500 NaN
1101  Kalyani  30/01/2017  4.9  Jyoti  450  550  500 NaN
1102  Kalyani  31/01/2017    5  Jyoti  400  500  450 NaN
            0           1    2      3    4    5    6   7
1023  Kalyani  03/07/2017  4.3  Jyoti  630  750  720 NaN
1024  Kalyani  04/07/2017  4.2  Jyoti  630  750  720 NaN
1025  Kalyani  05/07/2017  4.1  Jyoti  630  750  730 NaN
1026  Kalyani  06/07/2017    4  Jyoti  640  760  740 NaN
1027  Kalyani  07/07/2017    4  Jyoti  640  760  740 NaN
1028  Kalyani  11/07/2017  4.2  Jyoti  630  750  730 NaN
1029  Kalyani  12/07/2017  4.3  Jyoti  630  750  730 NaN
1030  Kalyani  13/07/2017  4.5  Jyoti  630  750  720 NaN
1031  Kalyani  17/07/2017  4.8  Jyoti  600  720  690 NaN
1032  Kalyani  18/07/2017    5  Jyoti  600  710  680 NaN
1033  Kalyani  19/07/2017  5.1  Jyoti  600  710  680 NaN
1034  Kalyani  20/07/2017    5  Jyoti  600  700  680 NaN
1035  Kalyani  21/07/2017  5.2  Jyoti  600  700  680 NaN
1036  Kalyani  24/07/2017  5.5  Jyoti  580  680  660 NaN
1037  Kalyani  25/07/2017    5  Jyoti  660  720  700 NaN
1038  Kalyani  26/07/2017  4.9  Jyoti  660  720  700 NaN
1039  Kalyani  27/07/2017  4.7  Jyoti  680  750  720 NaN
1040  Kalyani  28/07/2017  4.9  Jyoti  680  750  720 NaN
            0           1    2      3    4    5    6   7
1014  Kalyani  01/06/2017  4.2  Jyoti  680  780  760 NaN
1015  Kalyani  02/06/2017    4  Jyoti  660  770  750 NaN
1016  Kalyani  05/06/2017    4  Jyoti  700  790  760 NaN
1017  Kalyani  06/06/2017  4.1  Jyoti  700  790  760 NaN
1018  Kalyani  07/06/2017  4.3  Jyoti  690  760  740 NaN
1019  Kalyani  08/06/2017  4.4  Jyoti  680  750  730 NaN
1020  Kalyani  09/06/2017  4.5  Jyoti  680  760  730 NaN
1021  Kalyani  12/06/2017  4.3  Jyoti  680  760  730 NaN
1022  Kalyani  13/06/2017  4.1  Jyoti  670  750  720 NaN
1023  Kalyani  14/06/2017    4  Jyoti  670  790  750 NaN
1024  Kalyani  15/06/2017  4.2  Jyoti  660  780  750 NaN
1025  Kalyani  16/06/2017    4  Jyoti  660  780  750 NaN
1026  Kalyani  19/06/2017    4  Jyoti  660  780  750 NaN
1027  Kalyani  20/06/2017  4.1  Jyoti  660  770  740 NaN
1028  Kalyani  21/06/2017    4  Jyoti  660  760  740 NaN
1029  Kalyani  22/06/2017  4.5  Jyoti  630  750  720 NaN
1030  Kalyani  23/06/2017    4  Jyoti  660  760  740 NaN
1031  Kalyani  27/06/2017  3.8  Jyoti  670  780  750 NaN
1032  Kalyani  28/06/2017  3.7  Jyoti  670  780  750 NaN
1033  Kalyani  29/06/2017    4  Jyoti  660  760  730 NaN
            0           1    2      3    4    5    6   7
1096  Kalyani  01/03/2017  6.2  Jyoti  380  450  400 NaN
1097  Kalyani  02/03/2017  5.5  Jyoti  450  500  480 NaN
1098  Kalyani  03/03/2017  5.6  Jyoti  400  480  450 NaN
1099  Kalyani  06/03/2017  5.5  Jyoti  420  480  460 NaN
1100  Kalyani  07/03/2017  5.4  Jyoti  420  480  460 NaN
1101  Kalyani  08/03/2017  5.6  Jyoti  430  480  470 NaN
1102  Kalyani  09/03/2017  5.5  Jyoti  430  480  470 NaN
1103  Kalyani  10/03/2017  5.4  Jyoti  430  480  470 NaN
1104  Kalyani  14/03/2017  5.6  Jyoti  410  470  450 NaN
1105  Kalyani  15/03/2017  5.7  Jyoti  380  420  400 NaN
1106  Kalyani  16/03/2017    6  Jyoti  420  460  440 NaN
1107  Kalyani  17/03/2017  6.3  Jyoti  420  480  450 NaN
1108  Kalyani  20/03/2017  6.5  Jyoti  420  480  450 NaN
1109  Kalyani  21/03/2017  6.7  Jyoti  420  470  450 NaN
1110  Kalyani  22/03/2017  6.8  Jyoti  410  470  450 NaN
1111  Kalyani  23/03/2017    7  Jyoti  400  450  430 NaN
1112  Kalyani  24/03/2017    7  Jyoti  400  450  430 NaN
1113  Kalyani  27/03/2017  6.8  Jyoti  420  460  440 NaN
1114  Kalyani  28/03/2017  6.2  Jyoti  440  500  480 NaN
1115  Kalyani  29/03/2017  6.1  Jyoti  440  500  480 NaN
1116  Kalyani  30/03/2017    6  Jyoti  450  500  490 NaN
            0           1     2      3    4    5    6   7
1019  Kalyani  01/05/2017     5  Jyoti  580  800  680 NaN
1020  Kalyani  02/05/2017     5  Jyoti  580  800  680 NaN
1021  Kalyani  03/05/2017   4.9  Jyoti  580  780  680 NaN
1022  Kalyani  04/05/2017   4.8  Jyoti  590  800  690 NaN
1023  Kalyani  05/05/2017   4.7  Jyoti  590  800  690 NaN
1024  Kalyani  08/05/2017   4.6  Jyoti  590  805  690 NaN
1025  Kalyani  09/05/2017  4.65  Jyoti  590  790  690 NaN
1026  Kalyani  10/05/2017   4.5  Jyoti  590  800  690 NaN
1027  Kalyani  15/05/2017   4.3  Jyoti  580  800  680 NaN
1028  Kalyani  16/05/2017  4.35  Jyoti  580  800  680 NaN
1029  Kalyani  17/05/2017   4.3  Jyoti  580  800  680 NaN
1030  Kalyani  18/05/2017     4  Jyoti  700  810  780 NaN
1031  Kalyani  19/05/2017   4.1  Jyoti  700  810  780 NaN
1032  Kalyani  22/05/2017     4  Jyoti  700  820  790 NaN
1033  Kalyani  23/05/2017   3.9  Jyoti  700  800  780 NaN
1034  Kalyani  24/05/2017     4  Jyoti  700  800  780 NaN
1035  Kalyani  25/05/2017   3.7  Jyoti  690  800  780 NaN
1036  Kalyani  26/05/2017   3.6  Jyoti  690  800  780 NaN
1037  Kalyani  29/05/2017     4  Jyoti  680  780  760 NaN
1038  Kalyani  30/05/2017   4.3  Jyoti  680  780  760 NaN

            0           1    2      3    4    5    6   7
1089  Kalyani  01/11/2017    3  Jyoti  720  800  750 NaN
1090  Kalyani  02/11/2017  3.2  Jyoti  720  800  750 NaN
1091  Kalyani  03/11/2017  3.3  Jyoti  720  800  750 NaN
1092  Kalyani  06/11/2017  3.4  Jyoti  720  800  750 NaN
1093  Kalyani  07/11/2017  3.3  Jyoti  730  810  760 NaN
1094  Kalyani  08/11/2017  3.2  Jyoti  720  800  750 NaN
1095  Kalyani  09/11/2017    3  Jyoti  720  800  750 NaN
1096  Kalyani  10/11/2017  2.8  Jyoti  750  850  800 NaN
1097  Kalyani  11/11/2017  2.7  Jyoti  750  850  800 NaN
1098  Kalyani  13/11/2017  2.7  Jyoti  750  850  800 NaN
1099  Kalyani  14/11/2017  2.6  Jyoti  750  850  800 NaN
1100  Kalyani  15/11/2017  2.5  Jyoti  750  850  800 NaN
1101  Kalyani  16/11/2017  2.5  Jyoti  750  850  800 NaN
1102  Kalyani  20/11/2017  2.6  Jyoti  750  850  800 NaN
1103  Kalyani  21/11/2017  2.7  Jyoti  740  830  790 NaN
1104  Kalyani  22/11/2017    3  Jyoti  700  800  750 NaN
1105  Kalyani  23/11/2017  3.2  Jyoti  700  800  750 NaN
1106  Kalyani  27/11/2017  3.4  Jyoti  700  800  750 NaN
1107  Kalyani  28/11/2017  3.5  Jyoti  680  750  700 NaN
1108  Kalyani  29/11/2017  3.6  Jyoti  680  750  700 NaN
Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7]
Index: []
           0           1    2      3    4    5    6   7
967  Kalyani  01/09/2017  5.4  Jyoti  650  700  680 NaN
968  Kalyani  04/09/2017  5.5  Jyoti  650  700  680 NaN
969  Kalyani  05/09/2017  5.6  Jyoti  650  700  680 NaN
970  Kalyani  06/09/2017  5.5  Jyoti  650  700  680 NaN
971  Kalyani  07/09/2017  5.6  Jyoti  650  700  680 NaN
972  Kalyani  08/09/2017  5.7  Jyoti  640  695  670 NaN
973  Kalyani  11/09/2017  5.6  Jyoti  640  695  670 NaN
974  Kalyani  12/09/2017  5.8  Jyoti  610  680  650 NaN
975  Kalyani  13/09/2017    6  Jyoti  600  660  630 NaN
976  Kalyani  14/09/2017  6.2  Jyoti  580  650  620 NaN
977  Kalyani  15/09/2017  6.4  Jyoti  560  620  600 NaN
978  Kalyani  16/09/2017  6.5  Jyoti  560  620  600 NaN
979  Kalyani  18/09/2017  6.6  Jyoti  550  600  580 NaN
980  Kalyani  19/09/2017  6.7  Jyoti  520  580  560 NaN
981  Kalyani  20/09/2017  6.8  Jyoti  520  580  550 NaN
982  Kalyani  21/09/2017  6.7  Jyoti  520  580  550 NaN
983  Kalyani  22/09/2017  6.8  Jyoti  520  580  550 NaN
            0           1    2      3     4     5     6   7
1036  Kalyani  02/04/2018    6  Jyoti   900  1100  1000 NaN
1037  Kalyani  03/04/2018  6.2  Jyoti   900  1100  1000 NaN
1038  Kalyani  04/04/2018  6.5  Jyoti   940  1060  1020 NaN
1039  Kalyani  05/04/2018  6.4  Jyoti   940  1060  1020 NaN
1040  Kalyani  06/04/2018  6.5  Jyoti   950  1060  1020 NaN
1041  Kalyani  09/04/2018  6.7  Jyoti   950  1060  1020 NaN
1042  Kalyani  10/04/2018  6.8  Jyoti   960  1060  1020 NaN
1043  Kalyani  11/04/2018  6.6  Jyoti   970  1070  1030 NaN
1044  Kalyani  12/04/2018  6.7  Jyoti   970  1070  1030 NaN
1045  Kalyani  13/04/2018  6.8  Jyoti   960  1050  1020 NaN
1046  Kalyani  16/04/2018  6.9  Jyoti   960  1060  1030 NaN
1047  Kalyani  17/04/2018  6.8  Jyoti   950  1050  1020 NaN
1048  Kalyani  18/04/2018    7  Jyoti   940  1020   980 NaN
1049  Kalyani  19/04/2018  7.1  Jyoti   950  1050   980 NaN
1050  Kalyani  20/04/2018    6  Jyoti  1100  1200  1150 NaN
1051  Kalyani  23/04/2018  6.1           NR    NR    NR NaN
1052  Kalyani  24/04/2018  6.2  Jyoti  1100  1250  1150 NaN
1053  Kalyani  25/04/2018    6  Jyoti  1120  1250  1160 NaN
1054  Kalyani  26/04/2018  5.9  Jyoti  1120  1250  1160 NaN
1055  Kalyani  27/04/2018  5.8  Jyoti  1130  1260  1180 NaN
            0           1    2      3     4     5     6   7
1189  Kalyani  01/08/2018    5  Jyoti  1450  1490  1470 NaN
1190  Kalyani  02/08/2018  5.1  Jyoti  1450  1490  1470 NaN
1191  Kalyani  03/08/2018    5  Jyoti  1450  1490  1470 NaN
1192  Kalyani  04/08/2018  5.1  Jyoti  1450  1490  1470 NaN
1193  Kalyani  06/08/2018  5.2  Jyoti  1420  1450  1440 NaN
1194  Kalyani  07/08/2018  5.1  Jyoti  1420  1450  1440 NaN
1195  Kalyani  08/08/2018  5.2  Jyoti  1420  1450  1440 NaN
1196  Kalyani  09/08/2018  5.5  Jyoti  1350  1370  1360 NaN
1197  Kalyani  10/08/2018  5.6  Jyoti  1340  1360  1350 NaN
1198  Kalyani  13/08/2018  5.7  Jyoti  1340  1360  1350 NaN
1199  Kalyani  14/08/2018  5.6  Jyoti  1350  1370  1360 NaN
1200  Kalyani  15/08/2018  5.7  Jyoti  1350  1370  1360 NaN
1201  Kalyani  16/08/2018  5.8  Jyoti  1350  1370  1360 NaN
1202  Kalyani  17/08/2018  5.6  Jyoti  1350  1370  1360 NaN
1203  Kalyani  18/08/2018  5.5  Jyoti  1340  1360  1350 NaN
1204  Kalyani  20/08/2018  5.3  Jyoti  1360  1380  1370 NaN
1205  Kalyani  21/08/2018  5.4  Jyoti  1360  1380  1370 NaN
1206  Kalyani  22/08/2018  5.3  Jyoti  1360  1380  1370 NaN
1207  Kalyani  23/08/2018  5.4  Jyoti  1370  1390  1380 NaN
1208  Kalyani  24/08/2018  5.2  Jyoti  1370  1390  1380 NaN
1209  Kalyani  27/08/2018  5.4  Jyoti  1370  1390  1380 NaN
1210  Kalyani  28/08/2018  5.3  Jyoti  1370  1390  1380 NaN
1211  Kalyani  29/08/2018  5.5  Jyoti  1360  1380  1370 NaN
            0           1    2      3     4     5     6   7
1131  Kalyani  01/12/2018  4.1  Jyoti  1010  1050  1020 NaN
1132  Kalyani  03/12/2018  4.2  Jyoti  1000  1040  1010 NaN
1133  Kalyani  04/12/2018  4.1  Jyoti   900  1000   950 NaN
1134  Kalyani  05/12/2018    4  Jyoti   890   980   940 NaN
1135  Kalyani  06/12/2018  3.9  Jyoti   900   950   930 NaN
1136  Kalyani  07/12/2018  3.8  Jyoti   920   960   940 NaN
1137  Kalyani  08/12/2018  3.9  Jyoti   930   970   950 NaN
1138  Kalyani  10/12/2018    4  Jyoti   900   960   940 NaN
1139  Kalyani  11/12/2018  3.9  Jyoti   700   800   750 NaN
1140  Kalyani  12/12/2018    4  Jyoti   720   800   760 NaN
1141  Kalyani  13/12/2018  3.5  Jyoti   700   780   720 NaN
1142  Kalyani  14/12/2018  3.2  Jyoti   650   700   680 NaN
1143  Kalyani  15/12/2018  3.2  Jyoti   660   700   680 NaN
1144  Kalyani  17/12/2018    3  Jyoti   670   700   690 NaN
1145  Kalyani  18/12/2018  3.1  Jyoti   660   700   680 NaN
1146  Kalyani  19/12/2018    3  Jyoti   670   710   690 NaN
1147  Kalyani  20/12/2018  3.1  Jyoti   680   720   700 NaN
1148  Kalyani  21/12/2018    3  Jyoti   660   700   680 NaN
1149  Kalyani  22/12/2018  2.9  Jyoti   670   710   690 NaN
1150  Kalyani  24/12/2018  2.8  Jyoti   670   710   690 NaN
1151  Kalyani  25/12/2018  2.9  Jyoti   680   720   700 NaN
1152  Kalyani  26/12/2018  2.8  Jyoti   680   720   700 NaN
1153  Kalyani  27/12/2018  2.6  Jyoti   680   720   700 NaN
1154  Kalyani  28/12/2018  2.5  Jyoti   660   700   680 NaN
1155  Kalyani  31/12/2018  2.4  Jyoti   650   680   660 NaN
            0           1    2      3    4    5    6   7
1050  Kalyani  01/02/2018  4.5  Jyoti  480  580  520 NaN
1051  Kalyani  02/02/2018  4.7  Jyoti  450  550  500 NaN
1052  Kalyani  05/02/2018    4  Jyoti  460  550  520 NaN
1053  Kalyani  06/02/2018    4  Jyoti  460  550  520 NaN
1054  Kalyani  07/02/2018  3.8  Jyoti  480  600  550 NaN
1055  Kalyani  08/02/2018  3.6  Jyoti  480  600  550 NaN
1056  Kalyani  09/02/2018  3.2  Jyoti  450  550  500 NaN
1057  Kalyani  12/02/2018    3  Jyoti  480  540  520 NaN
1058  Kalyani  13/02/2018  3.5  Jyoti  480  560  530 NaN
1059  Kalyani  14/02/2018    4  Jyoti  500  600  550 NaN
1060  Kalyani  15/02/2018  4.5  Jyoti  500  600  550 NaN
1061  Kalyani  16/02/2018  4.6  Jyoti  500  600  550 NaN
1062  Kalyani  19/02/2018    5  Jyoti  500  600  550 NaN
1063  Kalyani  20/02/2018  5.3  Jyoti  500  600  550 NaN
1064  Kalyani  21/02/2018  5.4  Jyoti  550  650  600 NaN
1065  Kalyani  22/02/2018  5.5  Jyoti  550  650  600 NaN
1066  Kalyani  23/02/2018  5.4  Jyoti  550  650  600 NaN
1067  Kalyani  26/02/2018    5  Jyoti  550  650  600 NaN
1068  Kalyani  27/02/2018  5.1  Jyoti  560  660  610 NaN
1069  Kalyani  28/02/2018  5.2  Jyoti  550  650  600 NaN
            0           1    2      3    4    5    6   7
1136  Kalyani  01/01/2018    5  Jyoti  350  480  420 NaN
1137  Kalyani  02/01/2018  5.5  Jyoti  350  480  400 NaN
1138  Kalyani  03/01/2018  5.6  Jyoti  350  470  400 NaN
1139  Kalyani  04/01/2018  5.6  Jyoti  350  470  400 NaN
1140  Kalyani  05/01/2018    6  Jyoti  340  420  380 NaN
1141  Kalyani  08/01/2018  6.2  Jyoti  320  400  360 NaN
1142  Kalyani  09/01/2018  6.3  Jyoti  320  400  360 NaN
1143  Kalyani  10/01/2018  6.5  Jyoti  320  400  360 NaN
1144  Kalyani  11/01/2018  6.7  Jyoti  320  400  360 NaN
1145  Kalyani  15/01/2018    7  Jyoti  320  400  360 NaN
1146  Kalyani  16/01/2018    7  Jyoti  320  400  360 NaN
1147  Kalyani  17/01/2018  6.8  Jyoti  350  420  380 NaN
1148  Kalyani  18/01/2018  6.8  Jyoti  350  420  380 NaN
1149  Kalyani  19/01/2018  6.6  Jyoti  350  420  380 NaN
1150  Kalyani  22/01/2018  6.7  Jyoti  350  410  380 NaN
1151  Kalyani  23/01/2018  6.7  Jyoti  350  410  380 NaN
1152  Kalyani  24/01/2018  6.8  Jyoti  340  400  360 NaN
1153  Kalyani  25/01/2018    5  Jyoti  400  500  450 NaN
1154  Kalyani  29/01/2018  4.9  Jyoti  450  550  500 NaN
1155  Kalyani  30/01/2018  4.7  Jyoti  450  550  500 NaN
1156  Kalyani  31/01/2018  4.3  Jyoti  460  560  510 NaN

            0           1    2      3     4     5     6   7
1231  Kalyani  02/07/2018    5  Jyoti  1480  1550  1510 NaN
1232  Kalyani  03/07/2018  4.8  Jyoti  1500  1580  1520 NaN
1233  Kalyani  04/07/2018  4.7  Jyoti  1510  1590  1530 NaN
1234  Kalyani  05/07/2018  4.5  Jyoti  1520  1600  1550 NaN
1235  Kalyani  06/07/2018    5  Jyoti  1480  1520  1500 NaN
1236  Kalyani  07/07/2018  4.9           NR    NR    NR NaN
1237  Kalyani  09/07/2018    5  Jyoti  1480  1520  1500 NaN
1238  Kalyani  10/07/2018  5.1  Jyoti  1490  1530  1510 NaN
1239  Kalyani  11/07/2018  5.2  Jyoti  1480  1510  1500 NaN
1240  Kalyani  12/07/2018  5.3  Jyoti  1480  1510  1500 NaN
1241  Kalyani  13/07/2018  5.2  Jyoti  1480  1510  1500 NaN
1242  Kalyani  14/07/2018  5.1  Jyoti  1480  1510  1500 NaN
1243  Kalyani  16/07/2018  5.2  Jyoti  1480  1510  1500 NaN
1244  Kalyani  17/07/2018  5.3  Jyoti  1490  1520  1510 NaN
1245  Kalyani  18/07/2018    5  Jyoti  1480  1510  1500 NaN
1246  Kalyani  19/07/2018  5.2  Jyoti  1480  1510  1500 NaN
1247  Kalyani  20/07/2018  5.3  Jyoti  1450  1500  1480 NaN
1248  Kalyani  21/07/2018  5.2  Jyoti  1450  1500  1480 NaN
1249  Kalyani  23/07/2018  5.3  Jyoti  1430  1480  1450 NaN
1250  Kalyani  24/07/2018  5.2  Jyoti  1430  1480  1450 NaN
1251  Kalyani  25/07/2018  5.3  Jyoti  1430  1480  1450 NaN
1252  Kalyani  26/07/2018  5.2  Jyoti  1430  1480  1450 NaN
1253  Kalyani  27/07/2018  5.3  Jyoti  1430  1480  1450 NaN
1254  Kalyani  30/07/2018  5.3  Jyoti  1430  1480  1450 NaN
1255  Kalyani  31/07/2018  5.2  Jyoti  1440  1480  1450 NaN
            0           1    2      3     4     5     6   7
1086  Kalyani  01/06/2018  4.8  Jyoti  1500  1600  1550 NaN
1087  Kalyani  04/06/2018  4.5  Jyoti  1550  1650  1600 NaN
1088  Kalyani  05/06/2018  4.4  Jyoti  1550  1650  1600 NaN
1089  Kalyani  06/06/2018    5  Jyoti  1450  1500  1480 NaN
1090  Kalyani  07/06/2018  5.1  Jyoti  1450  1500  1480 NaN
1091  Kalyani  08/06/2018    5  Jyoti  1450  1500  1480 NaN
1092  Kalyani  11/06/2018    5  Jyoti  1450  1510  1480 NaN
1093  Kalyani  12/06/2018  5.1  Jyoti  1450  1500  1480 NaN
1094  Kalyani  13/06/2018    5  Jyoti  1460  1510  1490 NaN
1095  Kalyani  14/06/2018  5.1  Jyoti  1450  1500  1480 NaN
1096  Kalyani  15/06/2018    5  Jyoti  1450  1500  1480 NaN
1097  Kalyani  20/06/2018    5  Jyoti  1450  1500  1480 NaN
1098  Kalyani  21/06/2018    5  Jyoti  1460  1510  1490 NaN
1099  Kalyani  25/06/2018  4.9  Jyoti  1470  1520  1500 NaN
1100  Kalyani  26/06/2018    5  Jyoti  1460  1510  1500 NaN
1101  Kalyani  27/06/2018  5.1  Jyoti  1450  1500  1480 NaN
1102  Kalyani  28/06/2018    5  Jyoti  1450  1500  1480 NaN
1103  Kalyani  29/06/2018  5.1  Jyoti  1450  1500  1480 NaN
1104  Kalyani  30/06/2018    5  Jyoti  1450  1500  1480 NaN
            0           1    2      3    4     5    6   7
1091  Kalyani  05/03/2018  5.5  Jyoti  500   600  550 NaN
1092  Kalyani  06/03/2018  5.6  Jyoti  500   600  550 NaN
1093  Kalyani  07/03/2018  5.5  Jyoti  650   750  700 NaN
1094  Kalyani  08/03/2018  5.4  Jyoti  700   900  800 NaN
1095  Kalyani  09/03/2018  5.2  Jyoti  750   950  800 NaN
1096  Kalyani  12/03/2018  5.1  Jyoti  760   960  810 NaN
1097  Kalyani  13/03/2018  5.3  Jyoti  750   950  800 NaN
1098  Kalyani  14/03/2018  5.2  Jyoti  800  1000  900 NaN
1099  Kalyani  15/03/2018  5.4  Jyoti  800  1000  900 NaN
1100  Kalyani  16/03/2018  5.5  Jyoti  800  1000  900 NaN
1101  Kalyani  19/03/2018  5.6  Jyoti  850  1050  950 NaN
1102  Kalyani  20/03/2018  5.5  Jyoti  850  1050  950 NaN
1103  Kalyani  21/03/2018  5.4  Jyoti  900  1050  950 NaN
1104  Kalyani  22/03/2018  5.5  Jyoti  900  1050  950 NaN
1105  Kalyani  23/03/2018  5.6  Jyoti  900  1050  950 NaN
1106  Kalyani  26/03/2018  5.7  Jyoti  900  1050  950 NaN
1107  Kalyani  27/03/2018  5.6  Jyoti  900  1050  950 NaN
1108  Kalyani  28/03/2018  5.8  Jyoti  940  1050  980 NaN
1109  Kalyani  29/03/2018  5.9  Jyoti  950  1050  980 NaN
            0           1    2      3     4     5     6   7
1119  Kalyani  02/05/2018  5.9  Jyoti  1200  1400  1300 NaN
1120  Kalyani  03/05/2018    6  Jyoti  1200  1400  1300 NaN
1121  Kalyani  04/05/2018  6.2  Jyoti  1200  1400  1300 NaN
1122  Kalyani  07/05/2018  6.3  Jyoti  1200  1300  1250 NaN
1123  Kalyani  08/05/2018  6.2  Jyoti  1200  1300  1250 NaN
1124  Kalyani  09/05/2018    6  Jyoti  1350  1450  1400 NaN
1125  Kalyani  10/05/2018  5.9  Jyoti  1350  1450  1400 NaN
1126  Kalyani  11/05/2018  5.8  Jyoti  1350  1450  1400 NaN
1127  Kalyani  14/05/2018  5.9  Jyoti  1350  1450  1400 NaN
1128  Kalyani  15/05/2018  5.8  Jyoti  1350  1450  1400 NaN
1129  Kalyani  16/05/2018  5.6  Jyoti  1400  1500  1450 NaN
1130  Kalyani  17/05/2018  5.7  Jyoti  1400  1500  1450 NaN
1131  Kalyani  18/05/2018  5.5  Jyoti  1400  1500  1450 NaN
1132  Kalyani  21/05/2018  5.6  Jyoti  1400  1500  1450 NaN
1133  Kalyani  22/05/2018  5.7  Jyoti  1400  1500  1450 NaN
1134  Kalyani  23/05/2018  5.6  Jyoti  1450  1550  1500 NaN
1135  Kalyani  24/05/2018  5.2  Jyoti  1460  1560  1510 NaN
1136  Kalyani  25/05/2018    5  Jyoti  1460  1560  1510 NaN
1137  Kalyani  28/05/2018  5.1  Jyoti  1460  1560  1510 NaN
1138  Kalyani  29/05/2018    5  Jyoti  1460  1560  1510 NaN
1139  Kalyani  30/05/2018    5  Jyoti  1500  1600  1550 NaN
1140  Kalyani  31/05/2018  4.9  Jyoti  1500  1600  1550 NaN
            0           1    2      3     4     5     6   7
1176  Kalyani  01/11/2018  5.1  Jyoti  1420  1450  1440 NaN
1177  Kalyani  02/11/2018  5.2  Jyoti  1410  1450  1430 NaN
1178  Kalyani  05/11/2018    5  Jyoti  1410  1440  1420 NaN
1179  Kalyani  06/11/2018  5.1  Jyoti  1400  1430  1420 NaN
1180  Kalyani  07/11/2018    5  Jyoti  1410  1440  1420 NaN
1181  Kalyani  08/11/2018    5  Jyoti  1410  1440  1420 NaN
1182  Kalyani  09/11/2018  5.1  Jyoti  1400  1430  1420 NaN
1183  Kalyani  10/11/2018    5  Jyoti  1410  1440  1420 NaN
1184  Kalyani  12/11/2018  5.2  Jyoti  1360  1400  1380 NaN
1185  Kalyani  13/11/2018  5.1  Jyoti  1360  1400  1380 NaN
1186  Kalyani  14/11/2018  5.3  Jyoti  1370  1410  1390 NaN
1187  Kalyani  15/11/2018  5.2  Jyoti  1380  1420  1400 NaN
1188  Kalyani  16/11/2018  5.1  Jyoti  1390  1410  1400 NaN
1189  Kalyani  17/11/2018  5.3  Jyoti  1400  1420  1410 NaN
1190  Kalyani  19/11/2018  5.2  Jyoti  1410  1430  1420 NaN
1191  Kalyani  20/11/2018  5.1  Jyoti  1400  1420  1410 NaN
1192  Kalyani  21/11/2018  5.2  Jyoti  1410  1430  1420 NaN
1193  Kalyani  22/11/2018  5.1  Jyoti  1360  1400  1380 NaN
1194  Kalyani  23/11/2018    5  Jyoti  1370  1410  1390 NaN
1195  Kalyani  24/11/2018  5.1  Jyoti  1380  1400  1390 NaN
1196  Kalyani  26/11/2018  5.2  Jyoti  1390  1410  1400 NaN
1197  Kalyani  27/11/2018  4.9  Jyoti  1100  1200  1150 NaN
1198  Kalyani  28/11/2018  4.3  Jyoti  1100  1250  1200 NaN
1199  Kalyani  29/11/2018  4.1  Jyoti  1150  1240  1190 NaN
1200  Kalyani  30/11/2018    4  Jyoti  1000  1050  1020 NaN
            0           1    2      3     4     5     6   7
1132  Kalyani  01/10/2018  5.3  Jyoti  1360  1380  1370 NaN
1133  Kalyani  02/10/2018  5.2  Jyoti  1370  1400  1380 NaN
1134  Kalyani  03/10/2018  5.3  Jyoti  1360  1380  1370 NaN
1135  Kalyani  04/10/2018  5.1  Jyoti  1380  1400  1390 NaN
1136  Kalyani  05/10/2018    5  Jyoti  1360  1400  1380 NaN
1137  Kalyani  06/10/2018  5.1  Jyoti  1380  1400  1390 NaN
1138  Kalyani  08/10/2018    5  Jyoti  1380  1400  1390 NaN
1139  Kalyani  09/10/2018  5.2  Jyoti  1390  1410  1400 NaN
1140  Kalyani  10/10/2018  5.1  Jyoti  1390  1410  1400 NaN
1141  Kalyani  11/10/2018  5.1  Jyoti  1390  1410  1400 NaN
1142  Kalyani  12/10/2018    5  Jyoti  1400  1430  1410 NaN
1143  Kalyani  13/10/2018  5.1  Jyoti  1400  1420  1410 NaN
1144  Kalyani  15/10/2018    5  Jyoti  1400  1430  1410 NaN
1145  Kalyani  16/10/2018  5.1  Jyoti  1400  1420  1410 NaN
1146  Kalyani  17/10/2018  5.2  Jyoti  1400  1420  1410 NaN
1147  Kalyani  18/10/2018  5.1  Jyoti  1400  1430  1410 NaN
1148  Kalyani  19/10/2018    5  Jyoti  1400  1420  1410 NaN
1149  Kalyani  20/10/2018  5.1  Jyoti  1390  1410  1400 NaN
1150  Kalyani  22/10/2018    5  Jyoti  1380  1400  1390 NaN
1151  Kalyani  23/10/2018  5.1  Jyoti  1380  1400  1390 NaN
1152  Kalyani  24/10/2018    5  Jyoti  1380  1400  1390 NaN
1153  Kalyani  25/10/2018  5.1  Jyoti  1390  1410  1400 NaN
1154  Kalyani  26/10/2018    5  Jyoti  1390  1410  1400 NaN
1155  Kalyani  29/10/2018  5.1  Jyoti  1390  1410  1400 NaN
1156  Kalyani  30/10/2018    5  Jyoti  1420  1450  1440 NaN
1157  Kalyani  31/10/2018    5  Jyoti  1420  1450  1440 NaN

            0           1    2      3     4     5     6   7
1175  Kalyani  01/09/2018  5.4  Jyoti  1370  1390  1380 NaN
1176  Kalyani  03/09/2018  5.3  Jyoti  1360  1380  1370 NaN
1177  Kalyani  04/09/2018  5.4  Jyoti  1370  1390  1380 NaN
1178  Kalyani  05/09/2018  5.3  Jyoti  1370  1390  1380 NaN
1179  Kalyani  06/09/2018  5.2  Jyoti  1380  1400  1390 NaN
1180  Kalyani  07/09/2018  5.3  Jyoti  1380  1400  1390 NaN
1181  Kalyani  10/09/2018  5.2  Jyoti  1380  1400  1390 NaN
1182  Kalyani  11/09/2018  5.3  Jyoti  1380  1400  1390 NaN
1183  Kalyani  12/09/2018  5.2  Jyoti  1370  1390  1380 NaN
1184  Kalyani  13/09/2018  5.3  Jyoti  1380  1400  1390 NaN
1185  Kalyani  14/09/2018  5.4  Jyoti  1370  1390  1380 NaN
1186  Kalyani  15/09/2018  5.3  Jyoti  1370  1390  1380 NaN
1187  Kalyani  17/09/2018  5.4  Jyoti  1370  1390  1380 NaN
1188  Kalyani  18/09/2018  5.2  Jyoti  1380  1400  1390 NaN
1189  Kalyani  19/09/2018  5.1  Jyoti  1380  1400  1390 NaN
1190  Kalyani  20/09/2018  5.3  Jyoti  1350  1380  1360 NaN
1191  Kalyani  21/09/2018  5.4  Jyoti  1350  1380  1360 NaN
1192  Kalyani  24/09/2018  5.5  Jyoti  1350  1380  1360 NaN
1193  Kalyani  25/09/2018  5.3  Jyoti  1360  1390  1370 NaN
1194  Kalyani  26/09/2018  5.2  Jyoti  1370  1400  1380 NaN
1195  Kalyani  27/09/2018  5.1  Jyoti  1370  1400  1380 NaN
1196  Kalyani  28/09/2018    5  Jyoti  1370  1400  1380 NaN
1197  Kalyani  29/09/2018  5.2  Jyoti  1370  1400  1380 NaN
            0           1    2      3     4     5     6
1112  Kalyani  01/04/2019    3  Jyoti   550   570   560
1113  Kalyani  02/04/2019    5  Jyoti   860   900   880
1114  Kalyani  03/04/2019    6  Jyoti   860   900   890
1115  Kalyani  04/04/2019  6.5    NaN    NR    NR    NR
1116  Kalyani  05/04/2019    6  Jyoti   860   900   890
1117  Kalyani  06/04/2019  6.1  Jyoti   870   900   890
1118  Kalyani  08/04/2019    6  Jyoti   860   900   890
1119  Kalyani  09/04/2019  6.1  Jyoti   950   980   960
1120  Kalyani  10/04/2019    6  Jyoti   960  1000   980
1121  Kalyani  11/04/2019  6.3  Jyoti   950   990   980
1122  Kalyani  12/04/2019  6.4  Jyoti   980  1010  1000
1123  Kalyani  13/04/2019  6.5  Jyoti   990  1020  1010
1124  Kalyani  15/04/2019  6.5  Jyoti   980  1010  1000
1125  Kalyani  16/04/2019  6.6  Jyoti   990  1020  1010
1126  Kalyani  17/04/2019  6.4  Jyoti  1020  1050  1040
1127  Kalyani  18/04/2019  6.3  Jyoti  1020  1050  1040
1128  Kalyani  19/04/2019  6.2  Jyoti  1030  1070  1050
1129  Kalyani  20/04/2019  6.3  Jyoti  1020  1060  1040
1130  Kalyani  22/04/2019  6.4  Jyoti   980  1020  1000
1131  Kalyani  23/04/2019  6.5  Jyoti   980  1020  1000
1132  Kalyani  24/04/2019  6.3  Jyoti  1010  1050  1030
1133  Kalyani  25/04/2019  6.1  Jyoti  1030  1070  1050
1134  Kalyani  26/04/2019  6.3  Jyoti  1010  1050  1030
1135  Kalyani  27/04/2019  6.2  Jyoti  1010  1050  1030
1136  Kalyani  29/04/2019  6.2  Jyoti  1010  1050  1030
1137  Kalyani  30/04/2019  6.1  Jyoti  1020  1060  1040
            0           1    2      3     4     5     6
1100  Kalyani  01/08/2019  5.7  Jyoti   980  1000   990
1101  Kalyani  02/08/2019  5.8  Jyoti   990  1010  1000
1102  Kalyani  03/08/2019    6  Jyoti   970   990   980
1103  Kalyani  05/08/2019  6.1  Jyoti   970   990   980
1104  Kalyani  06/08/2019  6.2  Jyoti   970   990   980
1105  Kalyani  07/08/2019  6.3  Jyoti   960   980   970
1106  Kalyani  08/08/2019  6.2  Jyoti   960   980   970
1107  Kalyani  09/08/2019  6.3  Jyoti   950   970   960
1108  Kalyani  10/08/2019  6.2  Jyoti   950   970   960
1109  Kalyani  12/08/2019  6.1  Jyoti   960   980   970
1110  Kalyani  13/08/2019    6  Jyoti   990  1010  1000
1111  Kalyani  14/08/2019  6.1  Jyoti   990  1010  1000
1112  Kalyani  15/08/2019    6  Jyoti   990  1010  1000
1113  Kalyani  16/08/2019  6.2  Jyoti   980  1000   990
1114  Kalyani  17/08/2019  6.1  Jyoti   990  1010  1000
1115  Kalyani  19/08/2019    6  Jyoti  1000  1020  1010
1116  Kalyani  20/08/2019  6.2  Jyoti   980  1000   990
1117  Kalyani  21/08/2019    6  Jyoti  1020  1040  1030
1118  Kalyani  22/08/2019  6.2  Jyoti  1010  1030  1020
1119  Kalyani  23/08/2019  6.2  Jyoti  1010  1030  1020
1120  Kalyani  24/08/2019  6.3  Jyoti  1010  1030  1020
1121  Kalyani  26/08/2019  6.4  Jyoti  1000  1020  1010
1122  Kalyani  27/08/2019  6.2  Jyoti  1010  1030  1020
1123  Kalyani  28/08/2019  6.1  Jyoti  1010  1030  1020
1124  Kalyani  29/08/2019  6.3  Jyoti  1000  1020  1010
1125  Kalyani  30/08/2019    6  Jyoti  1020  1040  1030
            0           1    2      3     4     5     6
1100  Kalyani  02/12/2019  3.5  Jyoti  1550  1600  1580
1101  Kalyani  03/12/2019    3  Jyoti  1620  1670  1650
1102  Kalyani  04/12/2019  3.2  Jyoti  1650  1680  1670
1103  Kalyani  05/12/2019    3  Jyoti  1670  1690  1680
1104  Kalyani  06/12/2019  2.8  Jyoti  1740  1760  1750
1105  Kalyani  09/12/2019  2.6  Jyoti  1750  1780  1770
1106  Kalyani  10/12/2019  2.4  Jyoti  1780  1800  1790
1107  Kalyani  11/12/2019  2.5  Jyoti  1740  1760  1750
1108  Kalyani  12/12/2019  2.3  Jyoti  1760  1780  1770
1109  Kalyani  13/12/2019  2.4  Jyoti  1750  1770  1760
1110  Kalyani  14/12/2019  2.5  Jyoti  1770  1790  1780
1111  Kalyani  16/12/2019  2.5  Jyoti  1820  1840  1830
1112  Kalyani  17/12/2019  2.4  Jyoti  1870  1900  1880
1113  Kalyani  18/12/2019  2.3  Jyoti  1970  2000  1980
1114  Kalyani  19/12/2019    2  Jyoti  2030  2050  2040
1115  Kalyani  20/12/2019  1.8  Jyoti  2050  2070  2060
1116  Kalyani  21/12/2019  1.7  Jyoti  2060  2080  2070
1117  Kalyani  23/12/2019  1.6  Jyoti  2250  2270  2260
1118  Kalyani  24/12/2019  1.5  Jyoti  2270  2290  2280
1119  Kalyani  25/12/2019  1.4  Jyoti  2280  2300  2290
1120  Kalyani  26/12/2019  1.6  Jyoti  2190  2210  2200
1121  Kalyani  27/12/2019  1.8  Jyoti  2130  2150  2140
1122  Kalyani  28/12/2019  1.7  Jyoti  2130  2150  2140
1123  Kalyani  30/12/2019  1.8  Jyoti  2110  2130  2120
1124  Kalyani  31/12/2019  1.6  Jyoti  2160  2180  2170
            0           1    2      3    4    5    6
1011  Kalyani  01/02/2019  1.5  Jyoti  610  630  620
1012  Kalyani  02/02/2019  1.4  Jyoti  600  620  610
1013  Kalyani  04/02/2019  1.7  Jyoti  600  620  610
1014  Kalyani  05/02/2019  1.8  Jyoti  600  620  610
1015  Kalyani  06/02/2019  1.7  Jyoti  610  630  620
1016  Kalyani  07/02/2019  1.8  Jyoti  600  620  610
1017  Kalyani  08/02/2019  1.7  Jyoti  610  630  620
1018  Kalyani  09/02/2019  1.6  Jyoti  620  640  630
1019  Kalyani  11/02/2019  1.7  Jyoti  620  640  630
1020  Kalyani  12/02/2019  1.8  Jyoti  610  630  620
1021  Kalyani  13/02/2019  1.6  Jyoti  600  620  610
1022  Kalyani  14/02/2019  1.7  Jyoti  600  620  610
1023  Kalyani  15/02/2019  1.6  Jyoti  610  630  620
1024  Kalyani  16/02/2019  1.5  Jyoti  600  620  610
1025  Kalyani  18/02/2019  1.7  Jyoti  600  620  610
1026  Kalyani  19/02/2019  1.8  Jyoti  600  620  610
1027  Kalyani  20/02/2019  1.7  Jyoti  610  630  620
1028  Kalyani  21/02/2019  1.8  Jyoti  610  630  620
1029  Kalyani  22/02/2019  1.7  Jyoti  600  620  610
1030  Kalyani  23/02/2019  1.6  Jyoti  610  630  620
1031  Kalyani  25/02/2019  1.7  Jyoti  600  620  610
1032  Kalyani  26/02/2019  1.6  Jyoti  610  630  620
1033  Kalyani  27/02/2019  1.7  Jyoti  600  620  610
1034  Kalyani  28/02/2019  1.8  Jyoti  600  620  610
            0           1    2      3    4    5    6
1163  Kalyani  01/01/2019  2.5  Jyoti  650  680  660
1164  Kalyani  02/01/2019  2.3  Jyoti  640  660  650
1165  Kalyani  03/01/2019  2.2  Jyoti  650  680  660
1166  Kalyani  04/01/2019  2.1  Jyoti  640  660  650
1167  Kalyani  05/01/2019    2  Jyoti  650  670  660
1168  Kalyani  07/01/2019    2  Jyoti  620  650  630
1169  Kalyani  08/01/2019  1.9  Jyoti  620  650  630
1170  Kalyani  09/01/2019  1.8  Jyoti  620  650  630
1171  Kalyani  10/01/2019  1.7  Jyoti  620  650  630
1172  Kalyani  11/01/2019  1.6  Jyoti  630  650  640
1173  Kalyani  12/01/2019  1.5  Jyoti  640  660  650
1174  Kalyani  14/01/2019  1.4  Jyoti  640  660  650
1175  Kalyani  15/01/2019  1.2  Jyoti  600  640  620
1176  Kalyani  16/01/2019    1  Jyoti  610  640  620
1177  Kalyani  17/01/2019    1  Jyoti  620  660  640
1178  Kalyani  18/01/2019    1  Jyoti  600  640  620
1179  Kalyani  19/01/2019    1  Jyoti  610  650  630
1180  Kalyani  21/01/2019    1  Jyoti  600  640  620
1181  Kalyani  22/01/2019  1.2  Jyoti  620  660  640
1182  Kalyani  23/01/2019  1.3  Jyoti  600  640  620
1183  Kalyani  24/01/2019  1.2  Jyoti  600  640  620
1184  Kalyani  25/01/2019    1  Jyoti  610  640  620
1185  Kalyani  28/01/2019  1.5  Jyoti  600  620  610
1186  Kalyani  29/01/2019  1.4  Jyoti  610  630  620
1187  Kalyani  30/01/2019  1.3  Jyoti  620  640  630
1188  Kalyani  31/01/2019  1.4  Jyoti  610  630  620

            0           1    2      3     4     5     6
1140  Kalyani  01/07/2019  5.2  Jyoti  1030  1050  1040
1141  Kalyani  02/07/2019  5.1  Jyoti  1030  1050  1040
1142  Kalyani  03/07/2019    5  Jyoti  1050  1070  1060
1143  Kalyani  04/07/2019  5.1  Jyoti  1050  1070  1060
1144  Kalyani  05/07/2019  5.2  Jyoti  1030  1050  1040
1145  Kalyani  08/07/2019  5.3  Jyoti  1020  1040  1030
1146  Kalyani  09/07/2019  5.5  Jyoti  1010  1030  1020
1147  Kalyani  10/07/2019  5.4  Jyoti  1040  1060  1050
1148  Kalyani  11/07/2019  5.3  Jyoti  1050  1070  1060
1149  Kalyani  12/07/2019  5.2  Jyoti  1050  1070  1060
1150  Kalyani  13/07/2019  5.1  Jyoti  1050  1070  1060
1151  Kalyani  15/07/2019  5.3  Jyoti  1030  1050  1040
1152  Kalyani  16/07/2019  5.4  Jyoti  1030  1050  1040
1153  Kalyani  17/07/2019    5  Jyoti  1050  1070  1060
1154  Kalyani  18/07/2019  5.1  Jyoti  1040  1060  1050
1155  Kalyani  19/07/2019  5.2  Jyoti  1040  1060  1050
1156  Kalyani  20/07/2019  5.3  Jyoti  1030  1050  1040
1157  Kalyani  22/07/2019  5.4  Jyoti  1020  1040  1030
1158  Kalyani  23/07/2019  5.6  Jyoti  1000  1020  1010
1159  Kalyani  24/07/2019  5.5  Jyoti  1020  1040  1030
1160  Kalyani  25/07/2019  5.6  Jyoti  1020  1040  1030
1161  Kalyani  26/07/2019  5.5  Jyoti  1010  1030  1020
1162  Kalyani  27/07/2019  5.6  Jyoti  1000  1020  1010
1163  Kalyani  29/07/2019  5.4  Jyoti  1010  1030  1020
1164  Kalyani  30/07/2019  5.5  Jyoti  1000  1020  1010
1165  Kalyani  31/07/2019  5.6  Jyoti   990  1010  1000
            0           1    2      3     4     5     6
1117  Kalyani  03/06/2019  5.5  Jyoti  1080  1130  1100
1118  Kalyani  04/06/2019  5.4  Jyoti  1060  1100  1080
1119  Kalyani  05/06/2019  5.2  Jyoti  1060  1090  1080
1120  Kalyani  06/06/2019  5.3  Jyoti  1060  1080  1070
1121  Kalyani  07/06/2019  5.1  Jyoti  1070  1090  1080
1122  Kalyani  10/06/2019  5.2  Jyoti  1060  1080  1070
1123  Kalyani  11/06/2019    5  Jyoti  1070  1090  1080
1124  Kalyani  12/06/2019  5.1  Jyoti  1070  1090  1080
1125  Kalyani  13/06/2019    5  Jyoti  1070  1090  1080
1126  Kalyani  14/06/2019  5.1  Jyoti  1080  1100  1090
1127  Kalyani  19/06/2019  5.3  Jyoti  1070  1090  1080
1128  Kalyani  20/06/2019  5.2  Jyoti  1070  1090  1080
1129  Kalyani  21/06/2019  5.5  Jyoti  1050  1070  1060
1130  Kalyani  22/06/2019  5.3  Jyoti  1060  1080  1070
1131  Kalyani  24/06/2019  5.5  Jyoti  1050  1070  1060
1132  Kalyani  25/06/2019  5.6  Jyoti  1040  1060  1050
1133  Kalyani  26/06/2019  5.5  Jyoti  1040  1060  1050
1134  Kalyani  27/06/2019  5.6  Jyoti  1050  1070  1060
1135  Kalyani  28/06/2019  5.5  Jyoti  1040  1060  1050
1136  Kalyani  29/06/2019  5.4  Jyoti  1050  1070  1060
            0           1    2      3    4    5    6
1184  Kalyani  01/03/2019  1.7  Jyoti  600  620  610
1185  Kalyani  02/03/2019  1.6  Jyoti  610  630  620
1186  Kalyani  04/03/2019  1.7  Jyoti  610  630  620
1187  Kalyani  05/03/2019  1.8  Jyoti  600  620  610
1188  Kalyani  06/03/2019  1.9  Jyoti  610  630  620
1189  Kalyani  07/03/2019  1.8  Jyoti  620  640  630
1190  Kalyani  08/03/2019  1.9  Jyoti  600  620  610
1191  Kalyani  09/03/2019  1.8  Jyoti  610  630  620
1192  Kalyani  11/03/2019    2  Jyoti  600  620  610
1193  Kalyani  12/03/2019  2.3  Jyoti  580  610  600
1194  Kalyani  13/03/2019  2.2  Jyoti  590  610  600
1195  Kalyani  14/03/2019  2.3  Jyoti  580  600  590
1196  Kalyani  15/03/2019  2.4  Jyoti  550  570  560
1197  Kalyani  16/03/2019  2.3    NaN   NR   NR   NR
1198  Kalyani  18/03/2019  2.4  Jyoti  550  570  560
1199  Kalyani  19/03/2019  2.6  Jyoti  520  550  530
1200  Kalyani  20/03/2019  2.7  Jyoti  520  550  530
1201  Kalyani  21/03/2019  2.6  Jyoti  530  550  540
1202  Kalyani  22/03/2019  2.5  Jyoti  520  550  530
1203  Kalyani  23/03/2019  2.4  Jyoti  530  550  540
1204  Kalyani  25/03/2019  2.6  Jyoti  520  540  530
1205  Kalyani  26/03/2019  2.8  Jyoti  530  580  550
1206  Kalyani  27/03/2019  2.9  Jyoti  530  580  550
1207  Kalyani  28/03/2019  2.8  Jyoti  540  580  550
1208  Kalyani  29/03/2019  2.9  Jyoti  580  600  590
            0           1    2      3     4     5     6
1129  Kalyani  01/05/2019  6.2  Jyoti  1100  1130  1110
1130  Kalyani  02/05/2019  6.3  Jyoti  1100  1140  1120
1131  Kalyani  03/05/2019  6.2  Jyoti  1120  1150  1140
1132  Kalyani  04/05/2019  6.1  Jyoti  1120  1160  1140
1133  Kalyani  06/05/2019  6.1  Jyoti  1130  1160  1140
1134  Kalyani  07/05/2019  6.2  Jyoti  1130  1170  1150
1135  Kalyani  08/05/2019  6.1  Jyoti  1090  1130  1110
1136  Kalyani  09/05/2019  6.2  Jyoti  1100  1140  1120
1137  Kalyani  10/05/2019  6.3  Jyoti  1120  1160  1140
1138  Kalyani  11/05/2019  6.2  Jyoti  1100  1130  1120
1139  Kalyani  13/05/2019  6.1  Jyoti  1100  1130  1120
1140  Kalyani  14/05/2019    6  Jyoti  1130  1160  1150
1141  Kalyani  15/05/2019  5.9  Jyoti  1130  1160  1150
1142  Kalyani  16/05/2019  5.5  Jyoti  1140  1170  1160
1143  Kalyani  17/05/2019  5.7  Jyoti  1130  1160  1150
1144  Kalyani  18/05/2019  5.6  Jyoti  1130  1160  1150
1145  Kalyani  20/05/2019  5.5  Jyoti  1130  1160  1150
1146  Kalyani  21/05/2019  5.6  Jyoti  1120  1160  1140
1147  Kalyani  22/05/2019  5.5    NaN    NR    NR    NR
1148  Kalyani  23/05/2019  5.6  Jyoti  1120  1160  1140
1149  Kalyani  24/05/2019  5.7  Jyoti  1110  1140  1130
1150  Kalyani  25/05/2019  5.6  Jyoti  1110  1140  1130
1151  Kalyani  27/05/2019  5.8  Jyoti  1090  1120  1110
1152  Kalyani  28/05/2019  5.9  Jyoti  1080  1110  1100
1153  Kalyani  29/05/2019  5.8  Jyoti  1080  1120  1100
            0           1    2      3     4     5     6
1101  Kalyani  01/11/2019  3.1  Jyoti  1510  1530  1520
1102  Kalyani  02/11/2019    3  Jyoti  1510  1530  1520
1103  Kalyani  04/11/2019  2.9  Jyoti  1670  1690  1680
1104  Kalyani  05/11/2019  2.8  Jyoti  1660  1700  1680
1105  Kalyani  06/11/2019    3  Jyoti  1680  1700  1690
1106  Kalyani  07/11/2019  2.8  Jyoti  1700  1720  1710
1107  Kalyani  08/11/2019  2.7  Jyoti  1730  1750  1740
1108  Kalyani  09/11/2019  2.2  Jyoti  1750  1770  1760
1109  Kalyani  11/11/2019  2.5  Jyoti  1720  1740  1730
1110  Kalyani  12/11/2019  2.6  Jyoti  1720  1740  1730
1111  Kalyani  13/11/2019  2.5  Jyoti  1730  1750  1740
1112  Kalyani  14/11/2019  2.6  Jyoti  1730  1750  1740
1113  Kalyani  15/11/2019    3  Jyoti  1700  1720  1710
1114  Kalyani  16/11/2019  3.5  Jyoti  1650  1710  1680
1115  Kalyani  18/11/2019  3.6  Jyoti  1610  1650  1630
1116  Kalyani  19/11/2019  3.5  Jyoti  1610  1630  1620
1117  Kalyani  20/11/2019  3.7  Jyoti  1590  1610  1600
1118  Kalyani  21/11/2019  3.8  Jyoti  1580  1600  1590
1119  Kalyani  22/11/2019  3.9  Jyoti  1540  1560  1550
1120  Kalyani  23/11/2019  3.8  Jyoti  1550  1570  1560
1121  Kalyani  25/11/2019  3.9  Jyoti  1490  1510  1500
1122  Kalyani  26/11/2019  3.7  Jyoti  1510  1530  1520
1123  Kalyani  27/11/2019  3.6  Jyoti  1510  1530  1520
1124  Kalyani  28/11/2019  3.5  Jyoti  1520  1540  1530
1125  Kalyani  29/11/2019  3.8  Jyoti  1500  1520  1510
            0           1    2      3     4     5     6
994   Kalyani  01/10/2019    5  Jyoti  1050  1070  1060
995   Kalyani  14/10/2019  4.5  Jyoti  1280  1320  1300
996   Kalyani  15/10/2019  4.3  Jyoti  1300  1340  1320
997   Kalyani  16/10/2019    4  Jyoti  1350  1390  1370
998   Kalyani  17/10/2019  4.2  Jyoti  1350  1390  1370
999   Kalyani  18/10/2019    4  Jyoti  1390  1410  1400
1000  Kalyani  19/10/2019  3.9  Jyoti  1380  1410  1400
1001  Kalyani  21/10/2019  3.7  Jyoti  1400  1420  1410
1002  Kalyani  22/10/2019  3.6  Jyoti  1400  1420  1410
1003  Kalyani  23/10/2019  3.5  Jyoti  1410  1430  1420
1004  Kalyani  24/10/2019  3.8  Jyoti  1380  1400  1390
1005  Kalyani  28/10/2019  3.5  Jyoti  1460  1500  1480
1006  Kalyani  29/10/2019  3.2  Jyoti  1500  1520  1510
1007  Kalyani  30/10/2019  3.1  Jyoti  1510  1530  1520
1008  Kalyani  31/10/2019    3  Jyoti  1530  1550  1540
            0           1    2      3     4     5     6
1142  Kalyani  02/09/2019    6  Jyoti  1020  1040  1030
1143  Kalyani  03/09/2019  5.8  Jyoti  1030  1050  1040
1144  Kalyani  04/09/2019    6  Jyoti  1010  1030  1020
1145  Kalyani  05/09/2019  6.1  Jyoti  1010  1030  1020
1146  Kalyani  06/09/2019    6  Jyoti  1000  1020  1010
1147  Kalyani  07/09/2019  6.1  Jyoti  1010  1030  1020
1148  Kalyani  09/09/2019    6  Jyoti  1010  1030  1020
1149  Kalyani  10/09/2019  6.3  Jyoti  1000  1020  1010
1150  Kalyani  11/09/2019  6.5  Jyoti   990  1010  1000
1151  Kalyani  12/09/2019  6.2  Jyoti  1000  1020  1010
1152  Kalyani  13/09/2019  6.3  Jyoti  1000  1020  1010
1153  Kalyani  14/09/2019  6.2  Jyoti  1000  1020  1010
1154  Kalyani  16/09/2019  6.1  Jyoti  1020  1040  1030
1155  Kalyani  17/09/2019    6  Jyoti  1020  1040  1030
1156  Kalyani  18/09/2019  5.9  Jyoti   990  1010  1000
1157  Kalyani  19/09/2019  5.5  Jyoti  1040  1060  1050
1158  Kalyani  20/09/2019  5.6  Jyoti  1020  1040  1030
1159  Kalyani  21/09/2019  5.5  Jyoti  1020  1040  1030
1160  Kalyani  23/09/2019  5.7  Jyoti  1000  1020  1010
1161  Kalyani  24/09/2019  5.8  Jyoti  1000  1020  1010
1162  Kalyani  25/09/2019  5.5  Jyoti  1020  1040  1030
1163  Kalyani  26/09/2019  5.4  Jyoti  1020  1040  1030
1164  Kalyani  27/09/2019  5.2  Jyoti  1030  1050  1040
1165  Kalyani  28/09/2019  5.1  Jyoti  1030  1050  1040
1166  Kalyani  30/09/2019    5  Jyoti  1050  1070  1060

In [617]:
dk[dk[1]=='12/03/2019']

            0           1    2      3    4    5    6   7
1193  Kalyani  12/03/2019  2.3  Jyoti  580  610  600 NaN

In [618]:
dk[[1]]=dk[[1]].fillna(method='ffill')

In [619]:
# dk=dk[dk[3]=='Other']

In [620]:
dk[dk[1]=='12/03/2019']

            0           1    2      3    4    5    6   7
1193  Kalyani  12/03/2019  2.3  Jyoti  580  610  600 NaN

In [621]:
dk=dk.drop_duplicates(subset=1,keep='first')

In [622]:
dk[dk[1]=='12/03/2019']

            0           1    2      3    4    5    6   7
1193  Kalyani  12/03/2019  2.3  Jyoti  580  610  600 NaN

In [623]:
dk[1]=dk[1].astype(str)

In [624]:
from datetime import datetime

In [625]:
df=dk

In [626]:
# df=dk[dk[3]=='Other']

In [627]:
df[df[1]=='12/03/2019']

            0           1    2      3    4    5    6   7
1193  Kalyani  12/03/2019  2.3  Jyoti  580  610  600 NaN

In [628]:
df[1] = df[1].str.split("/")

In [629]:
df.head(2)

           0               1   2             3    4    5    6   7
316  Kalyani  [08, 04, 2008]  30  Chandermukhi  580  600  580 NaN
318  Kalyani  [09, 04, 2008]  30  Chandermukhi  580  600  580 NaN

In [630]:
df.iloc[0][1]

['08', '04', '2008']

In [631]:
l=[]
for i in range(len(df)):
    date = df.iloc[i][1]
#     date=str(date)
    print(date)
    day = date[0]
    month = date[1]
    year = date[2]
    if(len(year)==2):
        year = '20' + year
#         df.iloc[i][1] = day + "/" + month + "/" + year
        l.append(day + "/" + month + "/" + year)
    else:
        l.append(day + "/" + month + "/" + year)

['08', '04', '2008']
['09', '04', '2008']
['10', '04', '2008']
['11', '04', '2008']
['12', '04', '2008']
['13', '04', '2008']
['14', '04', '2008']
['15', '04', '2008']
['16', '04', '2008']
['17', '04', '2008']
['18', '04', '2008']
['19', '04', '2008']
['20', '04', '2008']
['21', '04', '2008']
['22', '04', '2008']
['23', '04', '2008']
['24', '04', '2008']
['25', '04', '2008']
['26', '04', '2008']
['27', '04', '2008']
['28', '04', '2008']
['29', '04', '2008']
['30', '04', '2008']
['01', '08', '2008']
['02', '08', '2008']
['03', '08', '2008']
['04', '08', '2008']
['05', '08', '2008']
['06', '08', '2008']
['07', '08', '2008']
['08', '08', '2008']
['09', '08', '2008']
['10', '08', '2008']
['11', '08', '2008']
['12', '08', '2008']
['13', '08', '2008']
['14', '08', '2008']
['15', '08', '2008']
['16', '08', '2008']
['17', '08', '2008']
['18', '08', '2008']
['19', '08', '2008']
['21', '08', '2008']
['22', '08', '2008']
['23', '08', '2008']
['24', '08', '2008']
['25', '08', '2008']
['26', '08', '2008']
['27', '08', '2008']
['28', '08', '2008']
['29', '08', '2008']
['30', '08', '2008']
['31', '08', '2008']
['01', '12', '2008']
['02', '12', '2008']
['03', '12', '2008']
['04', '12', '2008']
['05', '12', '2008']
['06', '12', '2008']
['07', '12', '2008']
['08', '12', '2008']
['09', '12', '2008']
['10', '12', '2008']
['11', '12', '2008']
['12', '12', '2008']
['13', '12', '2008']
['14', '12', '2008']
['15', '12', '2008']
['16', '12', '2008']
['17', '12', '2008']
['18', '12', '2008']
['19', '12', '2008']
['20', '12', '2008']
['21', '12', '2008']
['22', '12', '2008']
['23', '12', '2008']
['24', '12', '2008']
['25', '12', '2008']
['26', '12', '2008']
['27', '12', '2008']
['28', '12', '2008']
['29', '12', '2008']
['30', '12', '2008']
['31', '12', '2008']
['05', '02', '2008']
['07', '02', '2008']
['08', '02', '2008']
['09', '02', '2008']
['10', '02', '2008']
['11', '02', '2008']
['12', '02', '2008']
['13', '02', '2008']
['14', '02', '2008']
['15', '02', '2008']
['16', '02', '2008']
['17', '02', '2008']
['18', '02', '2008']
['19', '02', '2008']
['20', '02', '2008']
['21', '02', '2008']
['22', '02', '2008']
['01', '07', '2008']
['02', '07', '2008']
['03', '07', '2008']
['04', '07', '2008']
['06', '07', '2008']
['07', '07', '2008']
['08', '07', '2008']
['09', '07', '2008']
['10', '07', '2008']
['11', '07', '2008']
['12', '07', '2008']
['13', '07', '2008']
['14', '07', '2008']
['15', '07', '2008']
['16', '07', '2008']
['17', '07', '2008']
['18', '07', '2008']
['19', '07', '2008']
['20', '07', '2008']
['21', '07', '2008']
['22', '07', '2008']
['23', '07', '2008']
['24', '07', '2008']
['25', '07', '2008']
['26', '07', '2008']
['27', '07', '2008']
['28', '07', '2008']
['29', '07', '2008']
['30', '07', '2008']
['31', '07', '2008']
['16', '06', '2008']
['17', '06', '2008']
['18', '06', '2008']
['19', '06', '2008']
['20', '06', '2008']
['21', '06', '2008']
['22', '06', '2008']
['23', '06', '2008']
['24', '06', '2008']
['25', '06', '2008']
['26', '06', '2008']
['27', '06', '2008']
['28', '06', '2008']
['29', '06', '2008']
['30', '06', '2008']
['01', '03', '2008']
['02', '03', '2008']
['03', '03', '2008']
['04', '03', '2008']
['05', '03', '2008']
['06', '03', '2008']
['07', '03', '2008']
['08', '03', '2008']
['09', '03', '2008']
['10', '03', '2008']
['11', '03', '2008']
['12', '03', '2008']
['13', '03', '2008']
['14', '03', '2008']
['15', '03', '2008']
['16', '03', '2008']
['17', '03', '2008']
['18', '03', '2008']
['19', '03', '2008']
['20', '03', '2008']
['21', '03', '2008']
['22', '03', '2008']
['23', '03', '2008']
['24', '03', '2008']
['25', '03', '2008']
['26', '03', '2008']
['27', '03', '2008']
['28', '03', '2008']
['01', '11', '2008']
['02', '11', '2008']
['03', '11', '2008']
['04', '11', '2008']
['05', '11', '2008']
['06', '11', '2008']
['07', '11', '2008']
['09', '11', '2008']
['01', '10', '2008']
['02', '10', '2008']
['03', '10', '2008']
['01', '09', '2008']
['02', '09', '2008']
['03', '09', '2008']
['04', '09', '2008']
['05', '09', '2008']
['06', '09', '2008']
['07', '09', '2008']
['08', '09', '2008']
['09', '09', '2008']
['10', '09', '2008']
['11', '09', '2008']
['12', '09', '2008']
['13', '09', '2008']
['14', '09', '2008']
['15', '09', '2008']
['16', '09', '2008']
['17', '09', '2008']
['18', '09', '2008']
['19', '09', '2008']
['20', '09', '2008']
['21', '09', '2008']
['22', '09', '2008']
['23', '09', '2008']
['24', '09', '2008']
['25', '09', '2008']
['26', '09', '2008']
['27', '09', '2008']
['28', '09', '2008']
['29', '09', '2008']
['30', '09', '2008']
['01', '01', '2009']
['02', '01', '2009']
['03', '01', '2009']
['04', '01', '2009']
['05', '01', '2009']
['06', '01', '2009']
['01', '08', '2010']
['02', '08', '2010']
['03', '08', '2010']
['04', '08', '2010']
['05', '08', '2010']
['06', '08', '2010']
['07', '08', '2010']
['08', '08', '2010']
['09', '08', '2010']
['10', '08', '2010']
['11', '08', '2010']
['12', '08', '2010']
['13', '08', '2010']
['14', '08', '2010']
['15', '08', '2010']
['16', '08', '2010']
['17', '08', '2010']
['18', '08', '2010']
['19', '08', '2010']
['20', '08', '2010']
['21', '08', '2010']
['22', '08', '2010']
['23', '08', '2010']
['24', '08', '2010']
['25', '08', '2010']
['26', '08', '2010']
['27', '08', '2010']
['28', '08', '2010']
['29', '08', '2010']
['30', '08', '2010']
['31', '08', '2010']
['01', '12', '2010']
['02', '12', '2010']
['03', '12', '2010']
['04', '12', '2010']
['05', '12', '2010']
['06', '12', '2010']
['07', '12', '2010']
['08', '12', '2010']
['09', '12', '2010']
['10', '12', '2010']
['11', '12', '2010']
['12', '12', '2010']
['13', '12', '2010']
['14', '12', '2010']
['15', '12', '2010']
['16', '12', '2010']
['17', '12', '2010']
['18', '12', '2010']
['19', '12', '2010']
['20', '12', '2010']
['21', '12', '2010']
['22', '12', '2010']
['23', '12', '2010']
['24', '12', '2010']
['25', '12', '2010']
['26', '12', '2010']
['27', '12', '2010']
['28', '12', '2010']
['29', '12', '2010']
['30', '12', '2010']
['31', '12', '2010']
['01', '11', '2010']
['02', '11', '2010']
['03', '11', '2010']
['04', '11', '2010']
['05', '11', '2010']
['06', '11', '2010']
['07', '11', '2010']
['08', '11', '2010']
['09', '11', '2010']
['10', '11', '2010']
['11', '11', '2010']
['12', '11', '2010']
['13', '11', '2010']
['14', '11', '2010']
['15', '11', '2010']
['16', '11', '2010']
['17', '11', '2010']
['18', '11', '2010']
['19', '11', '2010']
['20', '11', '2010']
['21', '11', '2010']
['22', '11', '2010']
['23', '11', '2010']
['24', '11', '2010']
['26', '11', '2010']
['27', '11', '2010']
['28', '11', '2010']
['29', '11', '2010']
['30', '11', '2010']
['01', '10', '2010']
['02', '10', '2010']
['03', '10', '2010']
['04', '10', '2010']
['05', '10', '2010']
['06', '10', '2010']
['07', '10', '2010']
['08', '10', '2010']
['09', '10', '2010']
['10', '10', '2010']
['11', '10', '2010']
['12', '10', '2010']
['13', '10', '2010']
['14', '10', '2010']
['15', '10', '2010']
['16', '10', '2010']
['17', '10', '2010']
['18', '10', '2010']
['19', '10', '2010']
['20', '10', '2010']
['21', '10', '2010']
['22', '10', '2010']
['23', '10', '2010']
['24', '10', '2010']
['25', '10', '2010']
['26', '10', '2010']
['27', '10', '2010']
['28', '10', '2010']
['29', '10', '2010']
['30', '10', '2010']
['31', '10', '2010']
['01', '09', '2010']
['02', '09', '2010']
['03', '09', '2010']
['04', '09', '2010']
['05', '09', '2010']
['06', '09', '2010']
['07', '09', '2010']
['08', '09', '2010']
['09', '09', '2010']
['10', '09', '2010']
['11', '09', '2010']
['12', '09', '2010']
['13', '09', '2010']
['14', '09', '2010']
['15', '09', '2010']
['16', '09', '2010']
['17', '09', '2010']
['18', '09', '2010']
['19', '09', '2010']
['20', '09', '2010']
['21', '09', '2010']
['22', '09', '2010']
['23', '09', '2010']
['24', '09', '2010']
['25', '09', '2010']
['26', '09', '2010']
['27', '09', '2010']
['28', '09', '2010']
['29', '09', '2010']
['30', '09', '2010']
['01', '04', '2011']
['02', '04', '2011']
['03', '04', '2011']
['04', '04', '2011']
['05', '04', '2011']
['06', '04', '2011']
['07', '04', '2011']
['08', '04', '2011']
['09', '04', '2011']
['10', '04', '2011']
['11', '04', '2011']
['12', '04', '2011']
['13', '04', '2011']
['14', '04', '2011']
['15', '04', '2011']
['16', '04', '2011']
['17', '04', '2011']
['18', '04', '2011']
['19', '04', '2011']
['20', '04', '2011']
['21', '04', '2011']
['22', '04', '2011']
['23', '04', '2011']
['24', '04', '2011']
['25', '04', '2011']
['26', '04', '2011']
['27', '04', '2011']
['28', '04', '2011']
['29', '04', '2011']
['30', '04', '2011']
['01', '08', '2011']
['02', '08', '2011']
['03', '08', '2011']
['04', '08', '2011']
['10', '08', '2011']
['11', '08', '2011']
['12', '08', '2011']
['13', '08', '2011']
['14', '08', '2011']
['16', '08', '2011']
['17', '08', '2011']
['18', '08', '2011']
['19', '08', '2011']
['20', '08', '2011']
['21', '08', '2011']
['22', '08', '2011']
['23', '08', '2011']
['24', '08', '2011']
['25', '08', '2011']
['26', '08', '2011']
['27', '08', '2011']
['28', '08', '2011']
['29', '08', '2011']
['30', '08', '2011']
['31', '08', '2011']
['01', '12', '2011']
['02', '12', '2011']
['03', '12', '2011']
['04', '12', '2011']
['05', '12', '2011']
['10', '12', '2011']
['11', '12', '2011']
['12', '12', '2011']
['14', '12', '2011']
['15', '12', '2011']
['16', '12', '2011']
['17', '12', '2011']
['19', '12', '2011']
['20', '12', '2011']
['21', '12', '2011']
['22', '12', '2011']
['23', '12', '2011']
['24', '12', '2011']
['25', '12', '2011']
['26', '12', '2011']
['27', '12', '2011']
['28', '12', '2011']
['30', '12', '2011']
['31', '12', '2011']
['01', '02', '2011']
['02', '02', '2011']
['03', '02', '2011']
['04', '02', '2011']
['05', '02', '2011']
['06', '02', '2011']
['07', '02', '2011']
['08', '02', '2011']
['09', '02', '2011']
['10', '02', '2011']
['11', '02', '2011']
['12', '02', '2011']
['13', '02', '2011']
['14', '02', '2011']
['15', '02', '2011']
['16', '02', '2011']
['17', '02', '2011']
['23', '02', '2011']
['24', '02', '2011']
['25', '02', '2011']
['26', '02', '2011']
['27', '02', '2011']
['28', '02', '2011']
['01', '01', '2011']
['02', '01', '2011']
['03', '01', '2011']
['04', '01', '2011']
['20', '01', '2011']
['21', '01', '2011']
['22', '01', '2011']
['23', '01', '2011']
['24', '01', '2011']
['25', '01', '2011']
['01', '07', '2011']
['02', '07', '2011']
['03', '07', '2011']
['04', '07', '2011']
['05', '07', '2011']
['06', '07', '2011']
['07', '07', '2011']
['08', '07', '2011']
['09', '07', '2011']
['10', '07', '2011']
['11', '07', '2011']
['12', '07', '2011']
['13', '07', '2011']
['14', '07', '2011']
['15', '07', '2011']
['16', '07', '2011']
['17', '07', '2011']
['18', '07', '2011']
['19', '07', '2011']
['20', '07', '2011']
['21', '07', '2011']
['22', '07', '2011']
['23', '07', '2011']
['24', '07', '2011']
['25', '07', '2011']
['26', '07', '2011']
['27', '07', '2011']
['28', '07', '2011']
['29', '07', '2011']
['30', '07', '2011']
['31', '07', '2011']
['01', '03', '2011']
['02', '03', '2011']
['03', '03', '2011']
['04', '03', '2011']
['05', '03', '2011']
['06', '03', '2011']
['07', '03', '2011']
['08', '03', '2011']
['09', '03', '2011']
['10', '03', '2011']
['11', '03', '2011']
['12', '03', '2011']
['13', '03', '2011']
['14', '03', '2011']
['15', '03', '2011']
['16', '03', '2011']
['17', '03', '2011']
['18', '03', '2011']
['19', '03', '2011']
['20', '03', '2011']
['21', '03', '2011']
['22', '03', '2011']
['23', '03', '2011']
['24', '03', '2011']
['25', '03', '2011']
['26', '03', '2011']
['27', '03', '2011']
['28', '03', '2011']
['29', '03', '2011']
['30', '03', '2011']
['31', '03', '2011']
['01', '05', '2011']
['02', '05', '2011']
['03', '05', '2011']
['04', '05', '2011']
['05', '05', '2011']
['06', '05', '2011']
['07', '05', '2011']
['08', '05', '2011']
['09', '05', '2011']
['10', '05', '2011']
['11', '05', '2011']
['12', '05', '2011']
['13', '05', '2011']
['14', '05', '2011']
['15', '05', '2011']
['16', '05', '2011']
['17', '05', '2011']
['18', '05', '2011']
['19', '05', '2011']
['20', '05', '2011']
['21', '05', '2011']
['22', '05', '2011']
['23', '05', '2011']
['24', '05', '2011']
['25', '05', '2011']
['26', '05', '2011']
['01', '11', '2011']
['02', '11', '2011']
['03', '11', '2011']
['04', '11', '2011']
['05', '11', '2011']
['06', '11', '2011']
['07', '11', '2011']
['08', '11', '2011']
['09', '11', '2011']
['10', '11', '2011']
['11', '11', '2011']
['12', '11', '2011']
['13', '11', '2011']
['14', '11', '2011']
['15', '11', '2011']
['16', '11', '2011']
['17', '11', '2011']
['18', '11', '2011']
['19', '11', '2011']
['20', '11', '2011']
['21', '11', '2011']
['22', '11', '2011']
['24', '11', '2011']
['26', '11', '2011']
['27', '11', '2011']
['28', '11', '2011']
['29', '11', '2011']
['30', '11', '2011']
['01', '10', '2011']
['02', '10', '2011']
['03', '10', '2011']
['05', '10', '2011']
['06', '10', '2011']
['07', '10', '2011']
['08', '10', '2011']
['09', '10', '2011']
['10', '10', '2011']
['11', '10', '2011']
['12', '10', '2011']
['13', '10', '2011']
['14', '10', '2011']
['15', '10', '2011']
['16', '10', '2011']
['17', '10', '2011']
['18', '10', '2011']
['19', '10', '2011']
['20', '10', '2011']
['21', '10', '2011']
['22', '10', '2011']
['23', '10', '2011']
['24', '10', '2011']
['25', '10', '2011']
['26', '10', '2011']
['27', '10', '2011']
['28', '10', '2011']
['29', '10', '2011']
['30', '10', '2011']
['31', '10', '2011']
['01', '09', '2011']
['02', '09', '2011']
['03', '09', '2011']
['04', '09', '2011']
['05', '09', '2011']
['06', '09', '2011']
['07', '09', '2011']
['08', '09', '2011']
['09', '09', '2011']
['10', '09', '2011']
['11', '09', '2011']
['12', '09', '2011']
['14', '09', '2011']
['15', '09', '2011']
['16', '09', '2011']
['17', '09', '2011']
['18', '09', '2011']
['19', '09', '2011']
['20', '09', '2011']
['21', '09', '2011']
['22', '09', '2011']
['23', '09', '2011']
['24', '09', '2011']
['25', '09', '2011']
['26', '09', '2011']
['27', '09', '2011']
['28', '09', '2011']
['29', '09', '2011']
['30', '09', '2011']
['01', '04', '2012']
['02', '04', '2012']
['03', '04', '2012']
['04', '04', '2012']
['05', '04', '2012']
['06', '04', '2012']
['09', '04', '2012']
['10', '04', '2012']
['11', '04', '2012']
['12', '04', '2012']
['13', '04', '2012']
['14', '04', '2012']
['15', '04', '2012']
['16', '04', '2012']
['17', '04', '2012']
['18', '04', '2012']
['19', '04', '2012']
['20', '04', '2012']
['21', '04', '2012']
['23', '04', '2012']
['24', '04', '2012']
['25', '04', '2012']
['26', '04', '2012']
['29', '04', '2012']
['30', '04', '2012']
['01', '08', '2012']
['02', '08', '2012']
['03', '08', '2012']
['06', '08', '2012']
['07', '08', '2012']
['08', '08', '2012']
['09', '08', '2012']
['10', '08', '2012']
['13', '08', '2012']
['14', '08', '2012']
['15', '08', '2012']
['16', '08', '2012']
['19', '08', '2012']
['20', '08', '2012']
['21', '08', '2012']
['22', '08', '2012']
['23', '08', '2012']
['24', '08', '2012']
['25', '08', '2012']
['26', '08', '2012']
['27', '08', '2012']
['28', '08', '2012']
['29', '08', '2012']
['30', '08', '2012']
['31', '08', '2012']
['01', '12', '2012']
['02', '12', '2012']
['03', '12', '2012']
['04', '12', '2012']
['05', '12', '2012']
['07', '12', '2012']
['08', '12', '2012']
['09', '12', '2012']
['10', '12', '2012']
['11', '12', '2012']
['12', '12', '2012']
['14', '12', '2012']
['15', '12', '2012']
['16', '12', '2012']
['17', '12', '2012']
['18', '12', '2012']
['19', '12', '2012']
['20', '12', '2012']
['21', '12', '2012']
['22', '12', '2012']
['01', '02', '2012']
['03', '02', '2012']
['04', '02', '2012']
['05', '02', '2012']
['09', '02', '2012']
['10', '02', '2012']
['11', '02', '2012']
['12', '02', '2012']
['13', '02', '2012']
['14', '02', '2012']
['15', '02', '2012']
['16', '02', '2012']
['17', '02', '2012']
['18', '02', '2012']
['19', '02', '2012']
['20', '02', '2012']
['21', '02', '2012']
['22', '02', '2012']
['23', '02', '2012']
['24', '02', '2012']
['25', '02', '2012']
['26', '02', '2012']
['27', '02', '2012']
['29', '02', '2012']
['05', '01', '2012']
['06', '01', '2012']
['07', '01', '2012']
['08', '01', '2012']
['09', '01', '2012']
['10', '01', '2012']
['11', '01', '2012']
['12', '01', '2012']
['13', '01', '2012']
['14', '01', '2012']
['15', '01', '2012']
['16', '01', '2012']
['17', '01', '2012']
['18', '01', '2012']
['19', '01', '2012']
['20', '01', '2012']
['21', '01', '2012']
['22', '01', '2012']
['23', '01', '2012']
['24', '01', '2012']
['25', '01', '2012']
['26', '01', '2012']
['27', '01', '2012']
['28', '01', '2012']
['29', '01', '2012']
['30', '01', '2012']
['31', '01', '2012']
['02', '07', '2012']
['03', '07', '2012']
['04', '07', '2012']
['05', '07', '2012']
['06', '07', '2012']
['09', '07', '2012']
['10', '07', '2012']
['11', '07', '2012']
['12', '07', '2012']
['13', '07', '2012']
['16', '07', '2012']
['17', '07', '2012']
['18', '07', '2012']
['19', '07', '2012']
['20', '07', '2012']
['23', '07', '2012']
['24', '07', '2012']
['25', '07', '2012']
['26', '07', '2012']
['27', '07', '2012']
['29', '07', '2012']
['30', '07', '2012']
['31', '07', '2012']
['01', '06', '2012']
['02', '06', '2012']
['04', '06', '2012']
['05', '06', '2012']
['06', '06', '2012']
['07', '06', '2012']
['08', '06', '2012']
['11', '06', '2012']
['12', '06', '2012']
['13', '06', '2012']
['14', '06', '2012']
['15', '06', '2012']
['16', '06', '2012']
['17', '06', '2012']
['18', '06', '2012']
['19', '06', '2012']
['20', '06', '2012']
['21', '06', '2012']
['22', '06', '2012']
['25', '06', '2012']
['26', '06', '2012']
['27', '06', '2012']
['28', '06', '2012']
['29', '06', '2012']
['01', '03', '2012']
['02', '03', '2012']
['03', '03', '2012']
['04', '03', '2012']
['05', '03', '2012']
['06', '03', '2012']
['07', '03', '2012']
['08', '03', '2012']
['09', '03', '2012']
['10', '03', '2012']
['11', '03', '2012']
['12', '03', '2012']
['13', '03', '2012']
['14', '03', '2012']
['15', '03', '2012']
['16', '03', '2012']
['17', '03', '2012']
['18', '03', '2012']
['19', '03', '2012']
['20', '03', '2012']
['21', '03', '2012']
['22', '03', '2012']
['23', '03', '2012']
['24', '03', '2012']
['25', '03', '2012']
['26', '03', '2012']
['27', '03', '2012']
['28', '03', '2012']
['29', '03', '2012']
['31', '03', '2012']
['01', '05', '2012']
['03', '05', '2012']
['04', '05', '2012']
['05', '05', '2012']
['07', '05', '2012']
['08', '05', '2012']
['09', '05', '2012']
['10', '05', '2012']
['11', '05', '2012']
['13', '05', '2012']
['15', '05', '2012']
['16', '05', '2012']
['17', '05', '2012']
['18', '05', '2012']
['21', '05', '2012']
['22', '05', '2012']
['23', '05', '2012']
['24', '05', '2012']
['25', '05', '2012']
['28', '05', '2012']
['29', '05', '2012']
['30', '05', '2012']
['31', '05', '2012']
['01', '11', '2012']
['02', '11', '2012']
['03', '11', '2012']
['04', '11', '2012']
['05', '11', '2012']
['06', '11', '2012']
['07', '11', '2012']
['08', '11', '2012']
['09', '11', '2012']
['10', '11', '2012']
['11', '11', '2012']
['26', '11', '2012']
['27', '11', '2012']
['28', '11', '2012']
['29', '11', '2012']
['30', '11', '2012']
['01', '10', '2012']
['02', '10', '2012']
['03', '10', '2012']
['04', '10', '2012']
['05', '10', '2012']
['06', '10', '2012']
['07', '10', '2012']
['08', '10', '2012']
['09', '10', '2012']
['10', '10', '2012']
['12', '10', '2012']
['13', '10', '2012']
['14', '10', '2012']
['15', '10', '2012']
['16', '10', '2012']
['17', '10', '2012']
['18', '10', '2012']
['20', '10', '2012']
['21', '10', '2012']
['22', '10', '2012']
['23', '10', '2012']
['24', '10', '2012']
['25', '10', '2012']
['26', '10', '2012']
['27', '10', '2012']
['28', '10', '2012']
['29', '10', '2012']
['30', '10', '2012']
['31', '10', '2012']
['01', '09', '2012']
['03', '09', '2012']
['04', '09', '2012']
['05', '09', '2012']
['06', '09', '2012']
['07', '09', '2012']
['08', '09', '2012']
['09', '09', '2012']
['10', '09', '2012']
['11', '09', '2012']
['12', '09', '2012']
['13', '09', '2012']
['14', '09', '2012']
['15', '09', '2012']
['16', '09', '2012']
['17', '09', '2012']
['18', '09', '2012']
['19', '09', '2012']
['23', '09', '2012']
['24', '09', '2012']
['25', '09', '2012']
['26', '09', '2012']
['27', '09', '2012']
['28', '09', '2012']
['01', '01', '2013']
['02', '01', '2013']

['30', '12', '2014']
['31', '12', '2014']
['17', '02', '2014']
['18', '02', '2014']
['19', '02', '2014']
['20', '02', '2014']
['21', '02', '2014']
['22', '02', '2014']
['24', '02', '2014']
['25', '02', '2014']
['26', '02', '2014']
['27', '02', '2014']
['28', '02', '2014']
['01', '07', '2014']
['02', '07', '2014']
['03', '07', '2014']
['04', '07', '2014']
['05', '07', '2014']
['07', '07', '2014']
['08', '07', '2014']
['09', '07', '2014']
['10', '07', '2014']
['11', '07', '2014']
['12', '07', '2014']
['14', '07', '2014']
['15', '07', '2014']
['16', '07', '2014']
['17', '07', '2014']
['18', '07', '2014']
['19', '07', '2014']
['20', '07', '2014']
['21', '07', '2014']
['22', '07', '2014']
['23', '07', '2014']
['24', '07', '2014']
['25', '07', '2014']
['26', '07', '2014']
['28', '07', '2014']
['30', '07', '2014']
['31', '07', '2014']
['02', '06', '2014']
['03', '06', '2014']
['04', '06', '2014']
['05', '06', '2014']
['06', '06', '2014']
['07', '06', '2014']
['09', '06', '2014']
['10', '06', '2014']
['11', '06', '2014']
['12', '06', '2014']
['13', '06', '2014']
['14', '06', '2014']
['16', '06', '2014']
['17', '06', '2014']
['18', '06', '2014']
['19', '06', '2014']
['20', '06', '2014']
['21', '06', '2014']
['23', '06', '2014']
['24', '06', '2014']
['25', '06', '2014']
['26', '06', '2014']
['27', '06', '2014']
['28', '06', '2014']
['30', '06', '2014']
['01', '03', '2014']
['03', '03', '2014']
['04', '03', '2014']
['05', '03', '2014']
['06', '03', '2014']
['07', '03', '2014']
['08', '03', '2014']
['10', '03', '2014']
['11', '03', '2014']
['12', '03', '2014']
['13', '03', '2014']
['14', '03', '2014']
['15', '03', '2014']
['17', '03', '2014']
['18', '03', '2014']
['19', '03', '2014']
['20', '03', '2014']
['21', '03', '2014']
['22', '03', '2014']
['24', '03', '2014']
['25', '03', '2014']
['26', '03', '2014']
['27', '03', '2014']
['28', '03', '2014']
['29', '03', '2014']
['31', '03', '2014']
['01', '05', '2014']
['02', '05', '2014']
['03', '05', '2014']
['05', '05', '2014']
['06', '05', '2014']
['07', '05', '2014']
['08', '05', '2014']
['09', '05', '2014']
['10', '05', '2014']
['13', '05', '2014']
['14', '05', '2014']
['15', '05', '2014']
['16', '05', '2014']
['17', '05', '2014']
['19', '05', '2014']
['20', '05', '2014']
['21', '05', '2014']
['22', '05', '2014']
['23', '05', '2014']
['24', '05', '2014']
['26', '05', '2014']
['27', '05', '2014']
['28', '05', '2014']
['29', '05', '2014']
['30', '05', '2014']
['31', '05', '2014']
['01', '11', '2014']
['03', '11', '2014']
['04', '11', '2014']
['05', '11', '2014']
['06', '11', '2014']
['07', '11', '2014']
['08', '11', '2014']
['10', '11', '2014']
['11', '11', '2014']
['12', '11', '2014']
['13', '11', '2014']
['14', '11', '2014']
['15', '11', '2014']
['17', '11', '2014']
['18', '11', '2014']
['19', '11', '2014']
['20', '11', '2014']
['21', '11', '2014']
['22', '11', '2014']
['24', '11', '2014']
['25', '11', '2014']
['26', '11', '2014']
['27', '11', '2014']
['28', '11', '2014']
['29', '11', '2014']
['01', '09', '2014']
['02', '09', '2014']
['03', '09', '2014']
['04', '09', '2014']
['05', '09', '2014']
['06', '09', '2014']
['08', '09', '2014']
['09', '09', '2014']
['10', '09', '2014']
['11', '09', '2014']
['12', '09', '2014']
['13', '09', '2014']
['15', '09', '2014']
['16', '09', '2014']
['17', '09', '2014']
['18', '09', '2014']
['19', '09', '2014']
['20', '09', '2014']
['22', '09', '2014']
['24', '09', '2014']
['25', '09', '2014']
['26', '09', '2014']
['27', '09', '2014']
['29', '09', '2014']
['01', '04', '2015']
['02', '04', '2015']
['03', '04', '2015']
['04', '04', '2015']
['06', '04', '2015']
['07', '04', '2015']
['08', '04', '2015']
['09', '04', '2015']
['10', '04', '2015']
['11', '04', '2015']
['13', '04', '2015']
['14', '04', '2015']
['15', '04', '2015']
['16', '04', '2015']
['17', '04', '2015']
['18', '04', '2015']
['20', '04', '2015']
['21', '04', '2015']
['22', '04', '2015']
['23', '04', '2015']
['24', '04', '2015']
['25', '04', '2015']
['27', '04', '2015']
['28', '04', '2015']
['29', '04', '2015']
['30', '04', '2015']
['03', '08', '2015']
['04', '08', '2015']
['05', '08', '2015']
['06', '08', '2015']
['07', '08', '2015']
['08', '08', '2015']
['10', '08', '2015']
['11', '08', '2015']
['12', '08', '2015']
['13', '08', '2015']
['14', '08', '2015']
['17', '08', '2015']
['18', '08', '2015']
['19', '08', '2015']
['20', '08', '2015']
['21', '08', '2015']
['24', '08', '2015']
['25', '08', '2015']
['31', '08', '2015']
['01', '12', '2015']
['02', '12', '2015']
['03', '12', '2015']
['07', '12', '2015']
['08', '12', '2015']
['09', '12', '2015']
['10', '12', '2015']
['11', '12', '2015']
['14', '12', '2015']
['15', '12', '2015']
['16', '12', '2015']
['17', '12', '2015']
['28', '12', '2015']
['29', '12', '2015']
['31', '12', '2015']
['02', '02', '2015']
['03', '02', '2015']
['04', '02', '2015']
['05', '02', '2015']
['06', '02', '2015']
['07', '02', '2015']
['09', '02', '2015']
['10', '02', '2015']
['11', '02', '2015']
['12', '02', '2015']
['13', '02', '2015']
['14', '02', '2015']
['16', '02', '2015']
['17', '02', '2015']
['18', '02', '2015']
['19', '02', '2015']
['20', '02', '2015']
['21', '02', '2015']
['23', '02', '2015']
['24', '02', '2015']
['25', '02', '2015']
['26', '02', '2015']
['27', '02', '2015']
['28', '02', '2015']
['01', '01', '2015']
['02', '01', '2015']
['03', '01', '2015']
['05', '01', '2015']
['06', '01', '2015']
['07', '01', '2015']
['08', '01', '2015']
['09', '01', '2015']
['10', '01', '2015']
['12', '01', '2015']
['13', '01', '2015']
['14', '01', '2015']
['15', '01', '2015']
['16', '01', '2015']
['17', '01', '2015']
['19', '01', '2015']
['20', '01', '2015']
['21', '01', '2015']
['22', '01', '2015']
['23', '01', '2015']
['24', '01', '2015']
['26', '01', '2015']
['27', '01', '2015']
['28', '01', '2015']
['29', '01', '2015']
['30', '01', '2015']
['31', '01', '2015']
['02', '07', '2015']
['03', '07', '2015']
['04', '07', '2015']
['06', '07', '2015']
['07', '07', '2015']
['08', '07', '2015']
['09', '07', '2015']
['10', '07', '2015']
['13', '07', '2015']
['14', '07', '2015']
['15', '07', '2015']
['16', '07', '2015']
['17', '07', '2015']
['18', '07', '2015']
['20', '07', '2015']
['21', '07', '2015']
['22', '07', '2015']
['23', '07', '2015']
['24', '07', '2015']
['27', '07', '2015']
['28', '07', '2015']
['29', '07', '2015']
['30', '07', '2015']
['31', '07', '2015']
['01', '06', '2015']
['02', '06', '2015']
['03', '06', '2015']
['04', '06', '2015']
['05', '06', '2015']
['06', '06', '2015']
['08', '06', '2015']
['09', '06', '2015']
['10', '06', '2015']
['11', '06', '2015']
['12', '06', '2015']
['13', '06', '2015']
['15', '06', '2015']
['16', '06', '2015']
['17', '06', '2015']
['18', '06', '2015']
['19', '06', '2015']
['20', '06', '2015']
['22', '06', '2015']
['23', '06', '2015']
['24', '06', '2015']
['25', '06', '2015']
['26', '06', '2015']
['27', '06', '2015']
['29', '06', '2015']
['02', '03', '2015']
['06', '03', '2015']
['07', '03', '2015']
['09', '03', '2015']
['10', '03', '2015']
['11', '03', '2015']
['12', '03', '2015']
['16', '03', '2015']
['17', '03', '2015']
['18', '03', '2015']
['19', '03', '2015']
['20', '03', '2015']
['21', '03', '2015']
['23', '03', '2015']
['24', '03', '2015']
['25', '03', '2015']
['26', '03', '2015']
['27', '03', '2015']
['28', '03', '2015']
['30', '03', '2015']
['31', '03', '2015']
['01', '05', '2015']
['02', '05', '2015']
['04', '05', '2015']
['05', '05', '2015']
['06', '05', '2015']
['07', '05', '2015']
['08', '05', '2015']
['09', '05', '2015']
['11', '05', '2015']
['12', '05', '2015']
['13', '05', '2015']
['14', '05', '2015']
['15', '05', '2015']
['16', '05', '2015']
['18', '05', '2015']
['19', '05', '2015']
['20', '05', '2015']
['21', '05', '2015']
['25', '05', '2015']
['26', '05', '2015']
['27', '05', '2015']
['28', '05', '2015']
['29', '05', '2015']
['30', '05', '2015']
['02', '11', '2015']
['03', '11', '2015']
['04', '11', '2015']
['05', '11', '2015']
['06', '11', '2015']
['09', '11', '2015']
['16', '11', '2015']
['17', '11', '2015']
['18', '11', '2015']
['19', '11', '2015']
['20', '11', '2015']
['23', '11', '2015']
['24', '11', '2015']
['25', '11', '2015']
['26', '11', '2015']
['27', '11', '2015']
['30', '11', '2015']
['01', '10', '2015']
['02', '10', '2015']
['03', '10', '2015']
['05', '10', '2015']
['06', '10', '2015']
['07', '10', '2015']
['08', '10', '2015']
['09', '10', '2015']
['12', '10', '2015']
['13', '10', '2015']
['14', '10', '2015']
['15', '10', '2015']
['16', '10', '2015']
['27', '10', '2015']
['28', '10', '2015']
['29', '10', '2015']
['30', '10', '2015']
['01', '09', '2015']
['03', '09', '2015']
['04', '09', '2015']
['05', '09', '2015']
['07', '09', '2015']
['08', '09', '2015']
['09', '09', '2015']
['10', '09', '2015']
['11', '09', '2015']
['12', '09', '2015']
['14', '09', '2015']
['17', '09', '2015']
['18', '09', '2015']
['21', '09', '2015']
['22', '09', '2015']
['23', '09', '2015']
['24', '09', '2015']
['28', '09', '2015']
['29', '09', '2015']
['03', '04', '2016']
['04', '04', '2016']
['05', '04', '2016']
['06', '04', '2016']
['07', '04', '2016']
['08', '04', '2016']
['09', '04', '2016']
['10', '04', '2016']
['11', '04', '2016']
['12', '04', '2016']
['13', '04', '2016']
['14', '04', '2016']
['15', '04', '2016']
['17', '04', '2016']
['18', '04', '2016']
['19', '04', '2016']
['24', '04', '2016']
['25', '04', '2016']
['26', '04', '2016']
['27', '04', '2016']
['28', '04', '2016']
['29', '04', '2016']
['01', '08', '2016']
['02', '08', '2016']
['03', '08', '2016']
['04', '08', '2016']
['05', '08', '2016']
['08', '08', '2016']
['09', '08', '2016']
['10', '08', '2016']
['11', '08', '2016']
['12', '08', '2016']
['15', '08', '2016']
['16', '08', '2016']
['17', '08', '2016']
['22', '08', '2016']
['23', '08', '2016']
['24', '08', '2016']
['25', '08', '2016']
['26', '08', '2016']
['29', '08', '2016']
['30', '08', '2016']
['01', '12', '2016']
['02', '12', '2016']
['05', '12', '2016']
['06', '12', '2016']
['07', '12', '2016']
['08', '12', '2016']
['09', '12', '2016']
['12', '12', '2016']
['13', '12', '2016']
['14', '12', '2016']
['15', '12', '2016']
['16', '12', '2016']
['19', '12', '2016']
['20', '12', '2016']
['21', '12', '2016']
['22', '12', '2016']
['23', '12', '2016']
['26', '12', '2016']
['27', '12', '2016']
['28', '12', '2016']
['01', '02', '2016']
['02', '02', '2016']
['03', '02', '2016']
['04', '02', '2016']
['08', '02', '2016']
['09', '02', '2016']
['10', '02', '2016']
['11', '02', '2016']
['12', '02', '2016']
['15', '02', '2016']
['16', '02', '2016']
['17', '02', '2016']
['18', '02', '2016']
['19', '02', '2016']
['22', '02', '2016']
['23', '02', '2016']
['24', '02', '2016']
['25', '02', '2016']
['04', '01', '2016']
['05', '01', '2016']
['06', '01', '2016']
['07', '01', '2016']
['08', '01', '2016']
['19', '01', '2016']
['20', '01', '2016']
['21', '01', '2016']
['22', '01', '2016']
['25', '01', '2016']
['27', '01', '2016']
['28', '01', '2016']
['29', '01', '2016']
['01', '07', '2016']
['07', '07', '2016']
['08', '07', '2016']
['09', '07', '2016']
['11', '07', '2016']
['13', '07', '2016']
['14', '07', '2016']
['15', '07', '2016']
['18', '07', '2016']
['19', '07', '2016']
['20', '07', '2016']
['21', '07', '2016']
['22', '07', '2016']
['25', '07', '2016']
['26', '07', '2016']
['27', '07', '2016']
['28', '07', '2016']
['01', '06', '2016']
['02', '06', '2016']
['03', '06', '2016']
['06', '06', '2016']
['09', '06', '2016']
['10', '06', '2016']
['13', '06', '2016']
['14', '06', '2016']
['15', '06', '2016']
['16', '06', '2016']
['20', '06', '2016']
['21', '06', '2016']
['22', '06', '2016']
['23', '06', '2016']
['24', '06', '2016']
['27', '06', '2016']
['28', '06', '2016']
['29', '06', '2016']
['01', '03', '2016']
['02', '03', '2016']
['03', '03', '2016']
['04', '03', '2016']
['10', '03', '2016']
['11', '03', '2016']
['14', '03', '2016']
['15', '03', '2016']
['16', '03', '2016']
['17', '03', '2016']
['18', '03', '2016']
['21', '03', '2016']
['22', '03', '2016']
['02', '05', '2016']
['03', '05', '2016']
['04', '05', '2016']
['05', '05', '2016']
['06', '05', '2016']
['09', '05', '2016']
['10', '05', '2016']
['11', '05', '2016']
['12', '05', '2016']
['13', '05', '2016']
['16', '05', '2016']
['17', '05', '2016']
['18', '05', '2016']
['19', '05', '2016']
['20', '05', '2016']
['23', '05', '2016']
['24', '05', '2016']
['25', '05', '2016']
['26', '05', '2016']
['27', '05', '2016']
['30', '05', '2016']
['31', '05', '2016']
['01', '11', '2016']
['02', '11', '2016']
['03', '11', '2016']
['04', '11', '2016']
['05', '11', '2016']
['07', '11', '2016']
['08', '11', '2016']
['09', '11', '2016']
['10', '11', '2016']
['11', '11', '2016']
['12', '11', '2016']
['14', '11', '2016']
['15', '11', '2016']
['16', '11', '2016']
['17', '11', '2016']
['18', '11', '2016']
['21', '11', '2016']
['22', '11', '2016']
['23', '11', '2016']
['24', '11', '2016']
['25', '11', '2016']
['28', '11', '2016']
['29', '11', '2016']
['03', '10', '2016']
['17', '10', '2016']
['18', '10', '2016']
['19', '10', '2016']
['20', '10', '2016']
['21', '10', '2016']
['24', '10', '2016']
['25', '10', '2016']
['26', '10', '2016']
['01', '09', '2016']
['02', '09', '2016']
['05', '09', '2016']
['06', '09', '2016']
['07', '09', '2016']
['09', '09', '2016']
['12', '09', '2016']
['14', '09', '2016']
['15', '09', '2016']
['16', '09', '2016']
['21', '09', '2016']
['22', '09', '2016']
['23', '09', '2016']
['27', '09', '2016']
['28', '09', '2016']
['29', '09', '2016']
['03', '04', '2017']
['04', '04', '2017']
['10', '04', '2017']
['11', '04', '2017']
['12', '04', '2017']
['13', '04', '2017']
['14', '04', '2017']
['17', '04', '2017']
['18', '04', '2017']
['19', '04', '2017']
['20', '04', '2017']
['21', '04', '2017']
['24', '04', '2017']
['25', '04', '2017']
['26', '04', '2017']
['27', '04', '2017']
['28', '04', '2017']
['29', '04', '2017']
['01', '08', '2017']
['02', '08', '2017']
['03', '08', '2017']
['04', '08', '2017']
['07', '08', '2017']
['08', '08', '2017']
['09', '08', '2017']
['10', '08', '2017']
['11', '08', '2017']
['14', '08', '2017']
['15', '08', '2017']
['16', '08', '2017']
['17', '08', '2017']
['18', '08', '2017']
['21', '08', '2017']
['22', '08', '2017']
['23', '08', '2017']
['24', '08', '2017']
['25', '08', '2017']
['28', '08', '2017']
['29', '08', '2017']
['04', '12', '2017']
['05', '12', '2017']
['07', '12', '2017']
['08', '12', '2017']
['13', '12', '2017']
['14', '12', '2017']
['15', '12', '2017']
['18', '12', '2017']
['19', '12', '2017']
['20', '12', '2017']
['21', '12', '2017']
['22', '12', '2017']
['27', '12', '2017']
['01', '02', '2017']
['02', '02', '2017']
['03', '02', '2017']
['06', '02', '2017']
['07', '02', '2017']
['08', '02', '2017']
['09', '02', '2017']
['10', '02', '2017']
['15', '02', '2017']
['16', '02', '2017']
['17', '02', '2017']
['20', '02', '2017']
['21', '02', '2017']
['22', '02', '2017']
['23', '02', '2017']
['27', '02', '2017']
['28', '02', '2017']
['02', '01', '2017']
['03', '01', '2017']
['04', '01', '2017']
['05', '01', '2017']
['06', '01', '2017']
['09', '01', '2017']
['10', '01', '2017']
['11', '01', '2017']
['12', '01', '2017']
['13', '01', '2017']
['16', '01', '2017']
['17', '01', '2017']
['18', '01', '2017']
['19', '01', '2017']
['20', '01', '2017']
['23', '01', '2017']
['24', '01', '2017']
['25', '01', '2017']
['27', '01', '2017']
['30', '01', '2017']
['31', '01', '2017']
['03', '07', '2017']
['04', '07', '2017']
['05', '07', '2017']
['06', '07', '2017']
['07', '07', '2017']
['11', '07', '2017']
['12', '07', '2017']
['13', '07', '2017']
['17', '07', '2017']
['18', '07', '2017']
['19', '07', '2017']
['20', '07', '2017']
['21', '07', '2017']
['24', '07', '2017']
['25', '07', '2017']
['26', '07', '2017']
['27', '07', '2017']
['28', '07', '2017']
['01', '06', '2017']
['02', '06', '2017']
['05', '06', '2017']
['06', '06', '2017']
['07', '06', '2017']
['08', '06', '2017']
['09', '06', '2017']
['12', '06', '2017']
['13', '06', '2017']
['14', '06', '2017']
['15', '06', '2017']
['16', '06', '2017']
['19', '06', '2017']
['20', '06', '2017']
['21', '06', '2017']
['22', '06', '2017']
['23', '06', '2017']
['27', '06', '2017']
['28', '06', '2017']
['29', '06', '2017']
['01', '03', '2017']
['02', '03', '2017']
['03', '03', '2017']
['06', '03', '2017']
['07', '03', '2017']
['08', '03', '2017']
['09', '03', '2017']
['10', '03', '2017']
['14', '03', '2017']
['15', '03', '2017']
['16', '03', '2017']
['17', '03', '2017']
['20', '03', '2017']
['21', '03', '2017']
['22', '03', '2017']
['23', '03', '2017']
['24', '03', '2017']
['27', '03', '2017']
['28', '03', '2017']
['29', '03', '2017']
['30', '03', '2017']
['01', '05', '2017']
['02', '05', '2017']
['03', '05', '2017']
['04', '05', '2017']
['05', '05', '2017']
['08', '05', '2017']
['09', '05', '2017']
['10', '05', '2017']
['15', '05', '2017']
['16', '05', '2017']
['17', '05', '2017']
['18', '05', '2017']
['19', '05', '2017']
['22', '05', '2017']
['23', '05', '2017']
['24', '05', '2017']
['25', '05', '2017']
['26', '05', '2017']
['29', '05', '2017']
['30', '05', '2017']
['01', '11', '2017']
['02', '11', '2017']
['03', '11', '2017']
['06', '11', '2017']
['07', '11', '2017']
['08', '11', '2017']
['09', '11', '2017']
['10', '11', '2017']
['11', '11', '2017']
['13', '11', '2017']
['14', '11', '2017']
['15', '11', '2017']
['16', '11', '2017']
['20', '11', '2017']
['21', '11', '2017']
['22', '11', '2017']
['23', '11', '2017']
['27', '11', '2017']
['28', '11', '2017']
['29', '11', '2017']
['01', '09', '2017']
['04', '09', '2017']
['05', '09', '2017']
['06', '09', '2017']
['07', '09', '2017']
['08', '09', '2017']
['11', '09', '2017']
['12', '09', '2017']
['13', '09', '2017']
['14', '09', '2017']
['15', '09', '2017']
['16', '09', '2017']
['18', '09', '2017']
['19', '09', '2017']
['20', '09', '2017']
['21', '09', '2017']
['22', '09', '2017']
['02', '04', '2018']
['03', '04', '2018']
['04', '04', '2018']
['05', '04', '2018']
['06', '04', '2018']
['09', '04', '2018']
['10', '04', '2018']
['11', '04', '2018']
['12', '04', '2018']
['13', '04', '2018']
['16', '04', '2018']
['17', '04', '2018']
['18', '04', '2018']
['19', '04', '2018']
['20', '04', '2018']
['23', '04', '2018']
['24', '04', '2018']
['25', '04', '2018']
['26', '04', '2018']
['27', '04', '2018']
['01', '08', '2018']
['02', '08', '2018']
['03', '08', '2018']
['04', '08', '2018']
['06', '08', '2018']
['07', '08', '2018']
['08', '08', '2018']
['09', '08', '2018']
['10', '08', '2018']
['13', '08', '2018']
['14', '08', '2018']
['15', '08', '2018']
['16', '08', '2018']
['17', '08', '2018']
['18', '08', '2018']
['20', '08', '2018']
['21', '08', '2018']
['22', '08', '2018']
['23', '08', '2018']
['24', '08', '2018']
['27', '08', '2018']
['28', '08', '2018']
['29', '08', '2018']
['01', '12', '2018']
['03', '12', '2018']
['04', '12', '2018']
['05', '12', '2018']
['06', '12', '2018']
['07', '12', '2018']
['08', '12', '2018']
['10', '12', '2018']
['11', '12', '2018']
['12', '12', '2018']
['13', '12', '2018']
['14', '12', '2018']
['15', '12', '2018']
['17', '12', '2018']
['18', '12', '2018']
['19', '12', '2018']
['20', '12', '2018']
['21', '12', '2018']
['22', '12', '2018']
['24', '12', '2018']
['25', '12', '2018']
['26', '12', '2018']
['27', '12', '2018']
['28', '12', '2018']
['31', '12', '2018']
['01', '02', '2018']
['02', '02', '2018']
['05', '02', '2018']
['06', '02', '2018']
['07', '02', '2018']
['08', '02', '2018']
['09', '02', '2018']
['12', '02', '2018']
['13', '02', '2018']
['14', '02', '2018']
['15', '02', '2018']
['16', '02', '2018']
['19', '02', '2018']
['20', '02', '2018']
['21', '02', '2018']
['22', '02', '2018']
['23', '02', '2018']
['26', '02', '2018']
['27', '02', '2018']
['28', '02', '2018']
['01', '01', '2018']
['02', '01', '2018']
['03', '01', '2018']
['04', '01', '2018']
['05', '01', '2018']
['08', '01', '2018']
['09', '01', '2018']
['10', '01', '2018']
['11', '01', '2018']
['15', '01', '2018']
['16', '01', '2018']
['17', '01', '2018']
['18', '01', '2018']
['19', '01', '2018']
['22', '01', '2018']
['23', '01', '2018']
['24', '01', '2018']
['25', '01', '2018']
['29', '01', '2018']
['30', '01', '2018']
['31', '01', '2018']
['02', '07', '2018']
['03', '07', '2018']

['15', '06', '2018']
['20', '06', '2018']
['21', '06', '2018']
['25', '06', '2018']
['26', '06', '2018']
['27', '06', '2018']
['28', '06', '2018']
['29', '06', '2018']
['30', '06', '2018']
['05', '03', '2018']
['06', '03', '2018']
['07', '03', '2018']
['08', '03', '2018']
['09', '03', '2018']
['12', '03', '2018']
['13', '03', '2018']
['14', '03', '2018']
['15', '03', '2018']
['16', '03', '2018']
['19', '03', '2018']
['20', '03', '2018']
['21', '03', '2018']
['22', '03', '2018']
['23', '03', '2018']
['26', '03', '2018']
['27', '03', '2018']
['28', '03', '2018']
['29', '03', '2018']
['02', '05', '2018']
['03', '05', '2018']
['04', '05', '2018']
['07', '05', '2018']
['08', '05', '2018']
['09', '05', '2018']
['10', '05', '2018']
['11', '05', '2018']
['14', '05', '2018']
['15', '05', '2018']
['16', '05', '2018']
['17', '05', '2018']
['18', '05', '2018']
['21', '05', '2018']
['22', '05', '2018']
['23', '05', '2018']
['24', '05', '2018']
['25', '05', '2018']
['28', '05', '2018']
['29', '05', '2018']
['30', '05', '2018']
['31', '05', '2018']
['01', '11', '2018']
['02', '11', '2018']
['05', '11', '2018']
['06', '11', '2018']
['07', '11', '2018']
['08', '11', '2018']
['09', '11', '2018']
['10', '11', '2018']
['12', '11', '2018']
['13', '11', '2018']
['14', '11', '2018']
['15', '11', '2018']
['16', '11', '2018']
['17', '11', '2018']
['19', '11', '2018']
['20', '11', '2018']
['21', '11', '2018']
['22', '11', '2018']
['23', '11', '2018']
['24', '11', '2018']
['26', '11', '2018']
['27', '11', '2018']
['28', '11', '2018']
['29', '11', '2018']
['30', '11', '2018']
['01', '10', '2018']
['02', '10', '2018']
['03', '10', '2018']
['04', '10', '2018']
['05', '10', '2018']
['06', '10', '2018']
['08', '10', '2018']
['09', '10', '2018']
['10', '10', '2018']
['11', '10', '2018']
['12', '10', '2018']
['13', '10', '2018']
['15', '10', '2018']
['16', '10', '2018']
['17', '10', '2018']
['18', '10', '2018']
['19', '10', '2018']
['20', '10', '2018']
['22', '10', '2018']
['23', '10', '2018']
['24', '10', '2018']
['25', '10', '2018']
['26', '10', '2018']
['29', '10', '2018']
['30', '10', '2018']
['31', '10', '2018']
['01', '09', '2018']
['03', '09', '2018']
['04', '09', '2018']
['05', '09', '2018']
['06', '09', '2018']
['07', '09', '2018']
['10', '09', '2018']
['11', '09', '2018']
['12', '09', '2018']
['13', '09', '2018']
['14', '09', '2018']
['15', '09', '2018']
['17', '09', '2018']
['18', '09', '2018']
['19', '09', '2018']
['20', '09', '2018']
['21', '09', '2018']
['24', '09', '2018']
['25', '09', '2018']
['26', '09', '2018']
['27', '09', '2018']
['28', '09', '2018']
['29', '09', '2018']
['01', '04', '2019']
['02', '04', '2019']
['03', '04', '2019']
['04', '04', '2019']
['05', '04', '2019']
['06', '04', '2019']
['08', '04', '2019']
['09', '04', '2019']
['10', '04', '2019']
['11', '04', '2019']
['12', '04', '2019']
['13', '04', '2019']
['15', '04', '2019']
['16', '04', '2019']
['17', '04', '2019']
['18', '04', '2019']
['19', '04', '2019']
['20', '04', '2019']
['22', '04', '2019']
['23', '04', '2019']
['24', '04', '2019']
['25', '04', '2019']
['26', '04', '2019']
['27', '04', '2019']
['29', '04', '2019']
['30', '04', '2019']
['01', '08', '2019']
['02', '08', '2019']
['03', '08', '2019']
['05', '08', '2019']
['06', '08', '2019']
['07', '08', '2019']
['08', '08', '2019']
['09', '08', '2019']
['10', '08', '2019']
['12', '08', '2019']
['13', '08', '2019']
['14', '08', '2019']
['15', '08', '2019']
['16', '08', '2019']
['17', '08', '2019']
['19', '08', '2019']
['20', '08', '2019']
['21', '08', '2019']
['22', '08', '2019']
['23', '08', '2019']
['24', '08', '2019']
['26', '08', '2019']
['27', '08', '2019']
['28', '08', '2019']
['29', '08', '2019']
['30', '08', '2019']
['02', '12', '2019']
['03', '12', '2019']
['04', '12', '2019']
['05', '12', '2019']
['06', '12', '2019']
['09', '12', '2019']
['10', '12', '2019']
['11', '12', '2019']
['12', '12', '2019']
['13', '12', '2019']
['14', '12', '2019']
['16', '12', '2019']
['17', '12', '2019']
['18', '12', '2019']
['19', '12', '2019']
['20', '12', '2019']
['21', '12', '2019']
['23', '12', '2019']
['24', '12', '2019']
['25', '12', '2019']
['26', '12', '2019']
['27', '12', '2019']
['28', '12', '2019']
['30', '12', '2019']
['31', '12', '2019']
['01', '02', '2019']
['02', '02', '2019']
['04', '02', '2019']
['05', '02', '2019']
['06', '02', '2019']
['07', '02', '2019']
['08', '02', '2019']
['09', '02', '2019']
['11', '02', '2019']
['12', '02', '2019']
['13', '02', '2019']
['14', '02', '2019']
['15', '02', '2019']
['16', '02', '2019']
['18', '02', '2019']
['19', '02', '2019']
['20', '02', '2019']
['21', '02', '2019']
['22', '02', '2019']
['23', '02', '2019']
['25', '02', '2019']
['26', '02', '2019']
['27', '02', '2019']
['28', '02', '2019']
['01', '01', '2019']
['02', '01', '2019']
['03', '01', '2019']
['04', '01', '2019']
['05', '01', '2019']
['07', '01', '2019']
['08', '01', '2019']
['09', '01', '2019']
['10', '01', '2019']
['11', '01', '2019']
['12', '01', '2019']
['14', '01', '2019']
['15', '01', '2019']
['16', '01', '2019']
['17', '01', '2019']
['18', '01', '2019']
['19', '01', '2019']
['21', '01', '2019']
['22', '01', '2019']
['23', '01', '2019']
['24', '01', '2019']
['25', '01', '2019']
['28', '01', '2019']
['29', '01', '2019']
['30', '01', '2019']
['31', '01', '2019']
['01', '07', '2019']
['02', '07', '2019']
['03', '07', '2019']
['04', '07', '2019']
['05', '07', '2019']
['08', '07', '2019']
['09', '07', '2019']
['10', '07', '2019']
['11', '07', '2019']
['12', '07', '2019']
['13', '07', '2019']
['15', '07', '2019']
['16', '07', '2019']
['17', '07', '2019']
['18', '07', '2019']
['19', '07', '2019']
['20', '07', '2019']
['22', '07', '2019']
['23', '07', '2019']
['24', '07', '2019']
['25', '07', '2019']
['26', '07', '2019']
['27', '07', '2019']
['29', '07', '2019']
['30', '07', '2019']
['31', '07', '2019']
['03', '06', '2019']
['04', '06', '2019']
['05', '06', '2019']
['06', '06', '2019']
['07', '06', '2019']
['10', '06', '2019']
['11', '06', '2019']
['12', '06', '2019']
['13', '06', '2019']
['14', '06', '2019']
['19', '06', '2019']
['20', '06', '2019']
['21', '06', '2019']
['22', '06', '2019']
['24', '06', '2019']
['25', '06', '2019']
['26', '06', '2019']
['27', '06', '2019']
['28', '06', '2019']
['29', '06', '2019']
['01', '03', '2019']
['02', '03', '2019']
['04', '03', '2019']
['05', '03', '2019']
['06', '03', '2019']
['07', '03', '2019']
['08', '03', '2019']
['09', '03', '2019']
['11', '03', '2019']
['12', '03', '2019']
['13', '03', '2019']
['14', '03', '2019']
['15', '03', '2019']
['16', '03', '2019']
['18', '03', '2019']
['19', '03', '2019']
['20', '03', '2019']
['21', '03', '2019']
['22', '03', '2019']
['23', '03', '2019']
['25', '03', '2019']
['26', '03', '2019']
['27', '03', '2019']
['28', '03', '2019']
['29', '03', '2019']
['01', '05', '2019']
['02', '05', '2019']
['03', '05', '2019']
['04', '05', '2019']
['06', '05', '2019']
['07', '05', '2019']
['08', '05', '2019']
['09', '05', '2019']
['10', '05', '2019']
['11', '05', '2019']
['13', '05', '2019']
['14', '05', '2019']
['15', '05', '2019']
['16', '05', '2019']
['17', '05', '2019']
['18', '05', '2019']
['20', '05', '2019']
['21', '05', '2019']
['22', '05', '2019']
['23', '05', '2019']
['24', '05', '2019']
['25', '05', '2019']
['27', '05', '2019']
['28', '05', '2019']
['29', '05', '2019']
['01', '11', '2019']
['02', '11', '2019']
['04', '11', '2019']
['05', '11', '2019']
['06', '11', '2019']
['07', '11', '2019']
['08', '11', '2019']
['09', '11', '2019']
['11', '11', '2019']
['12', '11', '2019']
['13', '11', '2019']
['14', '11', '2019']
['15', '11', '2019']
['16', '11', '2019']
['18', '11', '2019']
['19', '11', '2019']
['20', '11', '2019']
['21', '11', '2019']
['22', '11', '2019']
['23', '11', '2019']
['25', '11', '2019']
['26', '11', '2019']
['27', '11', '2019']
['28', '11', '2019']
['29', '11', '2019']
['01', '10', '2019']
['14', '10', '2019']
['15', '10', '2019']
['16', '10', '2019']
['17', '10', '2019']
['18', '10', '2019']
['19', '10', '2019']
['21', '10', '2019']
['22', '10', '2019']
['23', '10', '2019']
['24', '10', '2019']
['28', '10', '2019']
['29', '10', '2019']
['30', '10', '2019']
['31', '10', '2019']
['02', '09', '2019']
['03', '09', '2019']
['04', '09', '2019']
['05', '09', '2019']
['06', '09', '2019']
['07', '09', '2019']
['09', '09', '2019']
['10', '09', '2019']
['11', '09', '2019']
['12', '09', '2019']
['13', '09', '2019']
['14', '09', '2019']
['16', '09', '2019']
['17', '09', '2019']
['18', '09', '2019']
['19', '09', '2019']
['20', '09', '2019']
['21', '09', '2019']
['23', '09', '2019']
['24', '09', '2019']
['25', '09', '2019']
['26', '09', '2019']
['27', '09', '2019']
['28', '09', '2019']
['30', '09', '2019']

In [632]:
df['date']=l

In [633]:
df.head(2)

           0               1   2             3    4    5    6   7        date
316  Kalyani  [08, 04, 2008]  30  Chandermukhi  580  600  580 NaN  08/04/2008
318  Kalyani  [09, 04, 2008]  30  Chandermukhi  580  600  580 NaN  09/04/2008

In [634]:
idx=pd.date_range('2006-01-01','2019-12-31')
df.index=pd.to_datetime(df['date'],format="%d/%m/%Y")

In [635]:
df[df.index=='2019-03-12']

                  0               1    2      3    4    5    6   7        date
date
2019-03-12  Kalyani  [12, 03, 2019]  2.3  Jyoti  580  610  600 NaN  12/03/2019

In [636]:
df.head(5)

,0,1,2,3,4,5,6,7,date
date,,,,,,,,,
2008-04-08,Kalyani,"[08, 04, 2008]",30,Chandermukhi,580,600,580,NaN,08/04/2008
2008-04-09,Kalyani,"[09, 04, 2008]",30,Chandermukhi,580,600,580,NaN,09/04/2008
2008-04-10,Kalyani,"[10, 04, 2008]",30,Chandermukhi,580,600,580,NaN,10/04/2008
2008-04-11,Kalyani,"[11, 04, 2008]",30,Chandermukhi,580,600,580,NaN,11/04/2008
2008-04-12,Kalyani,"[12, 04, 2008]",30,Chandermukhi,580,600,580,NaN,12/04/2008

In [637]:
df1 = df.loc[~df.index.duplicated(keep='first')]

In [638]:
df1.head(5)

,0,1,2,3,4,5,6,7,date
date,,,,,,,,,
2008-04-08,Kalyani,"[08, 04, 2008]",30,Chandermukhi,580,600,580,NaN,08/04/2008
2008-04-09,Kalyani,"[09, 04, 2008]",30,Chandermukhi,580,600,580,NaN,09/04/2008
2008-04-10,Kalyani,"[10, 04, 2008]",30,Chandermukhi,580,600,580,NaN,10/04/2008
2008-04-11,Kalyani,"[11, 04, 2008]",30,Chandermukhi,580,600,580,NaN,11/04/2008
2008-04-12,Kalyani,"[12, 04, 2008]",30,Chandermukhi,580,600,580,NaN,12/04/2008

In [639]:
df1[df1.index=='2006-04-03']

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, date]
Index: []

In [640]:
df2=df1.reindex(idx,fill_value=np.nan)

In [641]:
df2.head(5)

              0    1    2    3    4    5    6   7 date
2006-01-01  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN
2006-01-02  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN
2006-01-03  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN
2006-01-04  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN
2006-01-05  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN

In [642]:
df2[df2.index=='2006-04-03']

              0    1    2    3    4    5    6   7 date
2006-04-03  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN

In [643]:
df2.replace('NR',np.nan,inplace=True)

In [644]:
df2[df2.index=='2006-04-03']

              0    1    2    3    4    5    6   7 date
2006-04-03  NaN  NaN  NaN  NaN  NaN  NaN  NaN NaN  NaN

In [645]:
df2.replace(np.nan,0.0,inplace=True)

In [646]:
df2[df2.index=='2006-04-03']

            0  1  2  3  4  5  6    7 date
2006-04-03  0  0  0  0  0  0  0  0.0    0

In [647]:
len(df2[df2[6]==0])

2719

In [648]:
price=df2[[6]]

In [649]:
price[1]=37

/home/ictd/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [650]:
price=price[[1,6]]

In [651]:
price.head(5)

             1  6
2006-01-01  37  0
2006-01-02  37  0
2006-01-03  37  0
2006-01-04  37  0
2006-01-05  37  0

In [652]:
price.to_csv('kalyani_mandi.csv',header=None)

In [653]:
len(price[price[6]==0])

2719

In [654]:
arrival=df2[[2]]

In [655]:
arrival[1]=37

/home/ictd/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [656]:
arrival=arrival[[1,2]]

In [657]:
arrival.head(5)

             1  2
2006-01-01  37  0
2006-01-02  37  0
2006-01-03  37  0
2006-01-04  37  0
2006-01-05  37  0

In [658]:
arrival.to_csv('kalyani_arrival.csv',header=None)

In [111]:
import pandas as pd
import numpy as np

In [112]:
df=pd.read_csv('maha2020.csv',header=None)

In [113]:
df=df[df[1]==146]

In [114]:
df.index=pd.to_datetime(df[0],errors='coerce')

In [115]:
df=df[1:]

In [116]:
idx = pd.date_range('2020-01-01','2020-02-15')

In [117]:
df=df.reindex(index=idx,fill_value=0)

In [118]:
df.replace(0,np.nan,inplace=True)

In [119]:
df

                     0      1       2    3      4     5     6     7
2020-01-01  2020-01-01  146.0  1803.0   NR    Red  1051  4600  3801
2020-01-02  2020-01-02  146.0  1789.0   NR    Red  1200  5031  4351
2020-01-03  2020-01-03  146.0  2029.0   NR    Red  1200  4799  4251
2020-01-04  2020-01-04  146.0   945.0   NR    Red  1400  4575  4000
2020-01-05         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-06  2020-01-06  146.0  1000.0   NR    NaN    NR    NR    NR
2020-01-07  2020-01-07  146.0  1629.0   NR    Red  1301  4752  4300
2020-01-08  2020-01-08  146.0  1801.0   NR    Red  1200  4650  3651
2020-01-09  2020-01-09  146.0  1780.0   NR  Other  1500  4342  3500
2020-01-10  2020-01-10  146.0  2134.0   NR    Red  1000  3540  2700
2020-01-11         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-12         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-13  2020-01-13  146.0  1100.0   NR    Red  1500  3195  2800
2020-01-14  2020-01-14  146.0  2017.0   NR    Red  1200  3800  3351
2020-01-15  2020-01-15  146.0  1784.0   NR    Red  1151  3900  3460
2020-01-16         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-17  2020-01-17  146.0  2277.0   NR    Red  1200  3720  3451
2020-01-18  2020-01-18  146.0  1000.0   NR    Red  1500  4000  3551
2020-01-19         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-20  2020-01-20  146.0  2061.0   NR    Red  1301  4855  4051
2020-01-21  2020-01-21  146.0  2097.0   NR    Red  1300  4223  3801
2020-01-22  2020-01-22  146.0  2087.0   NR    Red  1300  4107  3700
2020-01-23  2020-01-23  146.0  2640.0   NR    Red  1251  3815  3500
2020-01-24         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-25         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-26         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-01-27  2020-01-27  146.0  2312.0   NR    Red  1500  2930  2500
2020-01-28  2020-01-28  146.0  2390.0   NR    Red  1100  2990  2680
2020-01-29  2020-01-29  146.0  1807.0   NR    Red  1100  2991  2750
2020-01-30  2020-01-30  146.0  2216.0   NR    Red  1300  3026  2700
2020-01-31  2020-01-31  146.0  2674.0   NR    Red  1200  2932  2600
2020-02-01  2020-02-01  146.0  1196.0   NR    Red  1250  2847  2501
2020-02-02         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-02-03  2020-02-03  146.0  2335.0   NR    Red  1100  2637  2250
2020-02-04  2020-02-04  146.0  2865.0   NR    Red   900  2152  1800
2020-02-05  2020-02-05  146.0  2748.0   NR    Red  1000  1999  1770
2020-02-06  2020-02-06  146.0  2280.0   NR    Red  1000  2068  1740
2020-02-07  2020-02-07  146.0   700.0   NR    Red   900  1902  1600
2020-02-08  2020-02-08  146.0   448.0   NR    Red   800  1941  1780
2020-02-09         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN
2020-02-10  2020-02-10  146.0  1081.0   NR    Red  1051  2350  2101
2020-02-11  2020-02-11  146.0  2440.0   NR    Red  1000  2260  1850
2020-02-12  2020-02-12  146.0  2110.0   NR    Red   800  2200  1880
2020-02-13  2020-02-13  146.0  2058.0   NR    Red  1000  2140  1860
2020-02-14  2020-02-14  146.0   950.0   NR    Red  1000  2115  1850
2020-02-15         NaN    NaN     NaN  NaN    NaN   NaN   NaN   NaN

In [120]:
df[2]=df[2].interpolate(method='pchip')
df[7]=df[7].interpolate(method='pchip')

In [121]:
df

                     0      1            2    3      4     5     6     7
2020-01-01  2020-01-01  146.0  1803.000000   NR    Red  1051  4600  3801
2020-01-02  2020-01-02  146.0  1789.000000   NR    Red  1200  5031  4351
2020-01-03  2020-01-03  146.0  2029.000000   NR    Red  1200  4799  4251
2020-01-04  2020-01-04  146.0   945.000000   NR    Red  1400  4575  4000
2020-01-05         NaN    NaN   957.832815  NaN    NaN   NaN   NaN   NaN
2020-01-06  2020-01-06  146.0  1000.000000   NR    NaN    NR    NR    NR
2020-01-07  2020-01-07  146.0  1629.000000   NR    Red  1301  4752  4300
2020-01-08  2020-01-08  146.0  1801.000000   NR    Red  1200  4650  3651
2020-01-09  2020-01-09  146.0  1780.000000   NR  Other  1500  4342  3500
2020-01-10  2020-01-10  146.0  2134.000000   NR    Red  1000  3540  2700
2020-01-11         NaN    NaN  1865.925926  NaN    NaN   NaN   NaN   NaN
2020-01-12         NaN    NaN  1368.074074  NaN    NaN   NaN   NaN   NaN
2020-01-13  2020-01-13  146.0  1100.000000   NR    Red  1500  3195  2800
2020-01-14  2020-01-14  146.0  2017.000000   NR    Red  1200  3800  3351
2020-01-15  2020-01-15  146.0  1784.000000   NR    Red  1151  3900  3460
2020-01-16         NaN    NaN  2030.500000  NaN    NaN   NaN   NaN   NaN
2020-01-17  2020-01-17  146.0  2277.000000   NR    Red  1200  3720  3451
2020-01-18  2020-01-18  146.0  1000.000000   NR    Red  1500  4000  3551
2020-01-19         NaN    NaN  1515.134186  NaN    NaN   NaN   NaN   NaN
2020-01-20  2020-01-20  146.0  2061.000000   NR    Red  1301  4855  4051
2020-01-21  2020-01-21  146.0  2097.000000   NR    Red  1300  4223  3801
2020-01-22  2020-01-22  146.0  2087.000000   NR    Red  1300  4107  3700
2020-01-23  2020-01-23  146.0  2640.000000   NR    Red  1251  3815  3500
2020-01-24         NaN    NaN  2588.750000  NaN    NaN   NaN   NaN   NaN
2020-01-25         NaN    NaN  2476.000000  NaN    NaN   NaN   NaN   NaN
2020-01-26         NaN    NaN  2363.250000  NaN    NaN   NaN   NaN   NaN
2020-01-27  2020-01-27  146.0  2312.000000   NR    Red  1500  2930  2500
2020-01-28  2020-01-28  146.0  2390.000000   NR    Red  1100  2990  2680
2020-01-29  2020-01-29  146.0  1807.000000   NR    Red  1100  2991  2750
2020-01-30  2020-01-30  146.0  2216.000000   NR    Red  1300  3026  2700
2020-01-31  2020-01-31  146.0  2674.000000   NR    Red  1200  2932  2600
2020-02-01  2020-02-01  146.0  1196.000000   NR    Red  1250  2847  2501
2020-02-02         NaN    NaN  1628.785606  NaN    NaN   NaN   NaN   NaN
2020-02-03  2020-02-03  146.0  2335.000000   NR    Red  1100  2637  2250
2020-02-04  2020-02-04  146.0  2865.000000   NR    Red   900  2152  1800
2020-02-05  2020-02-05  146.0  2748.000000   NR    Red  1000  1999  1770
2020-02-06  2020-02-06  146.0  2280.000000   NR    Red  1000  2068  1740
2020-02-07  2020-02-07  146.0   700.000000   NR    Red   900  1902  1600
2020-02-08  2020-02-08  146.0   448.000000   NR    Red   800  1941  1780
2020-02-09         NaN    NaN   626.610440  NaN    NaN   NaN   NaN   NaN
2020-02-10  2020-02-10  146.0  1081.000000   NR    Red  1051  2350  2101
2020-02-11  2020-02-11  146.0  2440.000000   NR    Red  1000  2260  1850
2020-02-12  2020-02-12  146.0  2110.000000   NR    Red   800  2200  1880
2020-02-13  2020-02-13  146.0  2058.000000   NR    Red  1000  2140  1860
2020-02-14  2020-02-14  146.0   950.000000   NR    Red  1000  2115  1850
2020-02-15         NaN    NaN  -252.675862  NaN    NaN   NaN   NaN   NaN

In [122]:
arrival=df[[2]]

In [123]:
arrival.to_csv('maha2020arrival.csv')

In [124]:
mandi=df[[7]]

In [125]:
mandi.to_csv('maha2020mandi.csv')